CREATE OR REPLACE PROCEDURE DM.P_AST_STKPLG_M_D(IN @V_BIN_DATE INT)

BEGIN 
  
  /******************************************************************
  程序功能: 在GP中创建股票质押资产月表
  编写者: DCY
  创建日期: 2018-01-05
  简介：股票质押资产月表
  *********************************************************************
  修订记录： 修订日期       版本号    修订人             修改内容简要说明
           
  *********************************************************************/

--PART0 删除当月数据
  DELETE FROM DM.T_AST_STKPLG_M_D WHERE YEAR=SUBSTR(@V_BIN_DATE||'',1,4) AND MTH=SUBSTR(@V_BIN_DATE||'',5,2);

INSERT INTO DM.T_AST_STKPLG_M_D 
(
CUST_ID
,YEAR
,MTH
,CTR_NO
,NATRE_DAYS_MTH
,NATRE_DAYS_YEAR
,NATRE_DAY_MTHBEG
,YEAR_MTH
,YEAR_MTH_CUST_ID
,GUAR_SECU_MVAL_FINAL
,STKPLG_FIN_BAL_FINAL
,SH_GUAR_SECU_MVAL_FINAL
,SZ_GUAR_SECU_MVAL_FINAL
,SH_NOTS_GUAR_SECU_MVAL_FINAL
,SZ_NOTS_GUAR_SECU_MVAL_FINAL
,PROP_FINAC_OUT_SIDE_BAL_FINAL
,ASSM_FINAC_OUT_SIDE_BAL_FINAL
,SM_LOAN_FINAC_OUT_BAL_FINAL
,GUAR_SECU_MVAL_MDA
,STKPLG_FIN_BAL_MDA
,SH_GUAR_SECU_MVAL_MDA
,SZ_GUAR_SECU_MVAL_MDA
,SH_NOTS_GUAR_SECU_MVAL_MDA
,SZ_NOTS_GUAR_SECU_MVAL_MDA
,PROP_FINAC_OUT_SIDE_BAL_MDA
,ASSM_FINAC_OUT_SIDE_BAL_MDA
,SM_LOAN_FINAC_OUT_BAL_MDA
,GUAR_SECU_MVAL_YDA
,STKPLG_FIN_BAL_YDA
,SH_GUAR_SECU_MVAL_YDA
,SZ_GUAR_SECU_MVAL_YDA
,SH_NOTS_GUAR_SECU_MVAL_YDA
,SZ_NOTS_GUAR_SECU_MVAL_YDA
,PROP_FINAC_OUT_SIDE_BAL_YDA
,ASSM_FINAC_OUT_SIDE_BAL_YDA
,SM_LOAN_FINAC_OUT_BAL_YDA
,LOAD_DT
)
SELECT
	T1.CUST_ID AS 客户编码	
	,T_RQ.年
	,T_RQ.月
	,T1.CTR_NO AS 合同编号
	,T_RQ.自然天数_月
	,T_RQ.自然天数_年
	,T_RQ.自然日_月初
	,T_RQ.年||T_RQ.月 AS 年月
	,T_RQ.年||T_RQ.月||T1.CUST_ID AS 年月客户编码
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.GUAR_SECU_MVAL,0) ELSE 0 END) AS 担保证券市值_期末
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.STKPLG_FIN_BAL,0) ELSE 0 END) AS 股票质押融资余额_期末
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.SH_GUAR_SECU_MVAL,0) ELSE 0 END) AS 上海担保证券市值_期末
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.SZ_GUAR_SECU_MVAL,0) ELSE 0 END) AS 深圳担保证券市值_期末
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.SH_NOTS_GUAR_SECU_MVAL,0) ELSE 0 END) AS 上海限售股担保证券市值_期末
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.SZ_NOTS_GUAR_SECU_MVAL,0) ELSE 0 END) AS 深圳限售股担保证券市值_期末
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.PROP_FINAC_OUT_SIDE_BAL,0) ELSE 0 END) AS 自营融出方余额_期末
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.ASSM_FINAC_OUT_SIDE_BAL,0) ELSE 0 END) AS 资管融出方余额_期末
	,SUM(CASE WHEN T_RQ.日期=T_RQ.自然日_月末 THEN COALESCE(T1.SM_LOAN_FINAC_OUT_BAL,0) ELSE 0 END) AS 小额贷融出余额_期末

	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.GUAR_SECU_MVAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 担保证券市值_月日均
	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.STKPLG_FIN_BAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 股票质押融资余额_月日均
	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.SH_GUAR_SECU_MVAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 上海担保证券市值_月日均
	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.SZ_GUAR_SECU_MVAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 深圳担保证券市值_月日均
	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.SH_NOTS_GUAR_SECU_MVAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 上海限售股担保证券市值_月日均
	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.SZ_NOTS_GUAR_SECU_MVAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 深圳限售股担保证券市值_月日均
	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.PROP_FINAC_OUT_SIDE_BAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 自营融出方余额_月日均
	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.ASSM_FINAC_OUT_SIDE_BAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 资管融出方余额_月日均
	,SUM(CASE WHEN T_RQ.日期>=T_RQ.自然日_月初 THEN COALESCE(T1.SM_LOAN_FINAC_OUT_BAL,0) ELSE 0 END)/T_RQ.自然天数_月 AS 小额贷融出余额_月日均

	,SUM(COALESCE(T1.GUAR_SECU_MVAL,0))/T_RQ.自然天数_年 AS 担保证券市值_年日均
	,SUM(COALESCE(T1.STKPLG_FIN_BAL,0))/T_RQ.自然天数_年 AS 股票质押融资余额_年日均
	,SUM(COALESCE(T1.SH_GUAR_SECU_MVAL,0))/T_RQ.自然天数_年 AS 上海担保证券市值_年日均
	,SUM(COALESCE(T1.SZ_GUAR_SECU_MVAL,0))/T_RQ.自然天数_年 AS 深圳担保证券市值_年日均
	,SUM(COALESCE(T1.SH_NOTS_GUAR_SECU_MVAL,0))/T_RQ.自然天数_年 AS 上海限售股担保证券市值_年日均
	,SUM(COALESCE(T1.SZ_NOTS_GUAR_SECU_MVAL,0))/T_RQ.自然天数_年 AS 深圳限售股担保证券市值_年日均
	,SUM(COALESCE(T1.PROP_FINAC_OUT_SIDE_BAL,0))/T_RQ.自然天数_年 AS 自营融出方余额_年日均
	,SUM(COALESCE(T1.ASSM_FINAC_OUT_SIDE_BAL,0))/T_RQ.自然天数_年 AS 资管融出方余额_年日均
	,SUM(COALESCE(T1.SM_LOAN_FINAC_OUT_BAL,0))/T_RQ.自然天数_年 AS 小额贷融出余额_年日均
	,@V_BIN_DATE

FROM
(
	SELECT
		T1.YEAR AS 年
		,T2.MTH AS 月
		,T1.DT AS 日期
		,T1.TRD_DT AS 交易日期
		,T2.NATRE_DAY_MTHBEG AS 自然日_月初
		,T2.NATRE_DAY_MTHEND AS 自然日_月末
		,T2.TRD_DAY_MTHBEG AS 交易日_月初
		,T2.TRD_DAY_MTHEND AS 交易日_月末
		,T2.NATRE_DAY_YEARBGN AS 自然日_年初
		,T2.TRD_DAY_YEARBGN AS 交易日_年初
		,T2.NATRE_DAYS_MTH AS 自然天数_月
		,T2.TRD_DAYS_MTH AS 交易天数_月
		,T2.NATRE_DAYS_YEAR AS 自然天数_年
		,T2.TRD_DAYS_YEAR AS 交易天数_年
	FROM DM.T_PUB_DATE T1
	LEFT JOIN DM.T_PUB_DATE_M T2 ON T1.YEAR=T2.YEAR AND T1.MTH<=T2.MTH	
	WHERE T1.YEAR=SUBSTR(@V_BIN_DATE||'',1,4) AND T2.MTH=SUBSTR(@V_BIN_DATE||'',5,2)
) T_RQ
LEFT JOIN DM.T_AST_STKPLG T1 ON T_RQ.交易日期=T1.OCCUR_DT
GROUP BY
	T_RQ.年
	,T_RQ.月
	,T_RQ.自然天数_月
	,T_RQ.自然天数_年
	,T_RQ.自然日_月初
	,T1.CTR_NO
	,T1.CUST_ID
;

END
