CREATE TABLE T_EVT_EMP_BIS_M
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	ORG_NO               character varying(30) NOT NULL,
	CUST_STAT            character varying(30) NOT NULL,
	IF_SPCA_ACC          integer NOT NULL,
	IF_PROD_NEW_CUST     integer NOT NULL,
	IF_MTH_NA            integer NOT NULL,
	IF_YEAR_NA           integer NOT NULL,
	IF_CREDIT_CUST       integer NOT NULL,
	IF_CREDIT_MTH_NA     integer NOT NULL,
	IF_CREDIT_YEAR_NA    integer NOT NULL,
	IF_CREDIT_EFF_CUST   integer NOT NULL,
	IF_CREDIT_MTH_NA_EFF_ACT integer NOT NULL,
	IF_CREDIT_YEAR_NA_EFF_ACT integer NOT NULL,
	CUST_NUM             numeric(30) NULL,
	EFF_CUST_NUM         numeric(30) NULL,
	CREDIT_CUST_NUM      numeric(30) NULL,
	CREDIT_EFF_CUST_NUM  numeric(30) NULL,
	ODIAST_SCDY_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_STKF_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_A_SHR_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_NOTS_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_OFFUND_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_OPFUND_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_SB_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_IMGT_PD_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_BANK_CHRM_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_SECU_CHRM_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_PSTK_OPTN_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_B_SHR_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_OUTMARK_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_CPTL_BAL_FINAL numeric(38,8) NULL,
	ODIAST_NO_ARVD_CPTL_FINAL numeric(38,8) NULL,
	ODIAST_PTE_FUND_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_OVERSEA_TOTAST_FINAL numeric(38,8) NULL,
	ODIAST_FUTR_TOTAST_FINAL numeric(38,8) NULL,
	ODIAST_CPTL_BAL_RMB_FINAL numeric(38,8) NULL,
	ODIAST_CPTL_BAL_HKD_FINAL numeric(38,8) NULL,
	ODIAST_CPTL_BAL_USD_FINAL numeric(38,8) NULL,
	ODIAST_LOW_RISK_TOTAST_FINAL numeric(38,8) NULL,
	ODIAST_FUND_SPACCT_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_HGT_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_SGT_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_NET_AST_FINAL numeric(38,8) NULL,
	ODIAST_TOTAST_CONTAIN_NOTS_FINAL numeric(38,8) NULL,
	ODIAST_TOTAST_N_CONTAIN_NOTS_FINAL numeric(38,8) NULL,
	ODIAST_BOND_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_REPO_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_TREA_REPO_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_REPQ_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_SCDY_MVAL_MDA numeric(38,8) NULL,
	ODIAST_STKF_MVAL_MDA numeric(38,8) NULL,
	ODIAST_A_SHR_MVAL_MDA numeric(38,8) NULL,
	ODIAST_NOTS_MVAL_MDA numeric(38,8) NULL,
	ODIAST_OFFUND_MVAL_MDA numeric(38,8) NULL,
	ODIAST_OPFUND_MVAL_MDA numeric(38,8) NULL,
	ODIAST_SB_MVAL_MDA   numeric(38,8) NULL,
	ODIAST_IMGT_PD_MVAL_MDA numeric(38,8) NULL,
	ODIAST_BANK_CHRM_MVAL_MDA numeric(38,8) NULL,
	ODIAST_SECU_CHRM_MVAL_MDA numeric(38,8) NULL,
	ODIAST_PSTK_OPTN_MVAL_MDA numeric(38,8) NULL,
	ODIAST_B_SHR_MVAL_MDA numeric(38,8) NULL,
	ODIAST_OUTMARK_MVAL_MDA numeric(38,8) NULL,
	ODIAST_CPTL_BAL_MDA  numeric(38,8) NULL,
	ODIAST_NO_ARVD_CPTL_MDA numeric(38,8) NULL,
	ODIAST_PTE_FUND_MVAL_MDA numeric(38,8) NULL,
	ODIAST_OVERSEA_TOTAST_MDA numeric(38,8) NULL,
	ODIAST_FUTR_TOTAST_MDA numeric(38,8) NULL,
	ODIAST_CPTL_BAL_RMB_MDA numeric(38,8) NULL,
	ODIAST_CPTL_BAL_HKD_MDA numeric(38,8) NULL,
	ODIAST_CPTL_BAL_USD_MDA numeric(38,8) NULL,
	ODIAST_LOW_RISK_TOTAST_MDA numeric(38,8) NULL,
	ODIAST_FUND_SPACCT_MVAL_MDA numeric(38,8) NULL,
	ODIAST_HGT_MVAL_MDA  numeric(38,8) NULL,
	ODIAST_SGT_MVAL_MDA  numeric(38,8) NULL,
	ODIAST_NET_AST_MDA   numeric(38,8) NULL,
	ODIAST_TOTAST_CONTAIN_NOTS_MDA numeric(38,8) NULL,
	ODIAST_TOTAST_N_CONTAIN_NOTS_MDA numeric(38,8) NULL,
	ODIAST_BOND_MVAL_MDA numeric(38,8) NULL,
	ODIAST_REPO_MVAL_MDA numeric(38,8) NULL,
	ODIAST_TREA_REPO_MVAL_MDA numeric(38,8) NULL,
	ODIAST_REPQ_MVAL_MDA numeric(38,8) NULL,
	ODIAST_SCDY_MVAL_YDA numeric(38,8) NULL,
	ODIAST_STKF_MVAL_YDA numeric(38,8) NULL,
	ODIAST_A_SHR_MVAL_YDA numeric(38,8) NULL,
	ODIAST_NOTS_MVAL_YDA numeric(38,8) NULL,
	ODIAST_OFFUND_MVAL_YDA numeric(38,8) NULL,
	ODIAST_OPFUND_MVAL_YDA numeric(38,8) NULL,
	ODIAST_SB_MVAL_YDA   numeric(38,8) NULL,
	ODIAST_IMGT_PD_MVAL_YDA numeric(38,8) NULL,
	ODIAST_BANK_CHRM_MVAL_YDA numeric(38,8) NULL,
	ODIAST_SECU_CHRM_MVAL_YDA numeric(38,8) NULL,
	ODIAST_PSTK_OPTN_MVAL_YDA numeric(38,8) NULL,
	ODIAST_B_SHR_MVAL_YDA numeric(38,8) NULL,
	ODIAST_OUTMARK_MVAL_YDA numeric(38,8) NULL,
	ODIAST_CPTL_BAL_YDA  numeric(38,8) NULL,
	ODIAST_NO_ARVD_CPTL_YDA numeric(38,8) NULL,
	ODIAST_PTE_FUND_MVAL_YDA numeric(38,8) NULL,
	ODIAST_OVERSEA_TOTAST_YDA numeric(38,8) NULL,
	ODIAST_FUTR_TOTAST_YDA numeric(38,8) NULL,
	ODIAST_CPTL_BAL_RMB_YDA numeric(38,8) NULL,
	ODIAST_CPTL_BAL_HKD_YDA numeric(38,8) NULL,
	ODIAST_CPTL_BAL_USD_YDA numeric(38,8) NULL,
	ODIAST_LOW_RISK_TOTAST_YDA numeric(38,8) NULL,
	ODIAST_FUND_SPACCT_MVAL_YDA numeric(38,8) NULL,
	ODIAST_HGT_MVAL_YDA  numeric(38,8) NULL,
	ODIAST_SGT_MVAL_YDA  numeric(38,8) NULL,
	ODIAST_NET_AST_YDA   numeric(38,8) NULL,
	ODIAST_TOTAST_CONTAIN_NOTS_YDA numeric(38,8) NULL,
	ODIAST_TOTAST_N_CONTAIN_NOTS_YDA numeric(38,8) NULL,
	ODIAST_BOND_MVAL_YDA numeric(38,8) NULL,
	ODIAST_REPO_MVAL_YDA numeric(38,8) NULL,
	ODIAST_TREA_REPO_MVAL_YDA numeric(38,8) NULL,
	ODIAST_REPQ_MVAL_YDA numeric(38,8) NULL,
	ODIAST_PO_FUND_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_PO_FUND_MVAL_MDA numeric(38,8) NULL,
	ODIAST_PO_FUND_MVAL_YDA numeric(38,8) NULL,
	ODIAST_STKT_FUND_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_OTH_PROD_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_OTH_AST_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_APPTBUYB_PLG_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_STKT_FUND_MVAL_MDA numeric(38,8) NULL,
	ODIAST_OTH_PROD_MVAL_MDA numeric(38,8) NULL,
	ODIAST_OTH_AST_MVAL_MDA numeric(38,8) NULL,
	ODIAST_APPTBUYB_PLG_MVAL_MDA numeric(38,8) NULL,
	ODIAST_STKT_FUND_MVAL_YDA numeric(38,8) NULL,
	ODIAST_OTH_PROD_MVAL_YDA numeric(38,8) NULL,
	ODIAST_OTH_AST_MVAL_YDA numeric(38,8) NULL,
	ODIAST_APPTBUYB_PLG_MVAL_YDA numeric(38,8) NULL,
	ODIAST_CREDIT_NET_AST_FINAL numeric(38,8) NULL,
	ODIAST_CREDIT_MARG_FINAL numeric(38,8) NULL,
	ODIAST_CREDIT_BAL_FINAL numeric(38,8) NULL,
	ODIAST_CREDIT_NET_AST_MDA numeric(38,8) NULL,
	ODIAST_CREDIT_MARG_MDA numeric(38,8) NULL,
	ODIAST_CREDIT_BAL_MDA numeric(38,8) NULL,
	ODIAST_CREDIT_NET_AST_YDA numeric(38,8) NULL,
	ODIAST_CREDIT_MARG_YDA numeric(38,8) NULL,
	ODIAST_CREDIT_BAL_YDA numeric(38,8) NULL,
	ODIAST_PROD_TOT_MVAL_FINAL numeric(38,8) NULL,
	ODIAST_PROD_TOT_MVAL_MDA numeric(38,8) NULL,
	ODIAST_PROD_TOT_MVAL_YDA numeric(38,8) NULL,
	ODIAST_TOTAST_FINAL  numeric(38,8) NULL,
	ODIAST_TOTAST_MDA    numeric(38,8) NULL,
	ODIAST_TOTAST_YDA    numeric(38,8) NULL,
	CREDIT_TOT_LIAB_FINAL numeric(38,8) NULL,
	CREDIT_NET_AST_FINAL numeric(38,8) NULL,
	CREDIT_CRED_MARG_FINAL numeric(38,8) NULL,
	CREDIT_GUAR_SECMV_FINAL numeric(38,8) NULL,
	CREDIT_FIN_LIAB_FINAL numeric(38,8) NULL,
	CREDIT_CRDT_STK_LIAB_FINAL numeric(38,8) NULL,
	CREDIT_INTR_LIAB_FINAL numeric(38,8) NULL,
	CREDIT_FEE_LIAB_FINAL numeric(38,8) NULL,
	CREDIT_OTHLIAB_FINAL numeric(38,8) NULL,
	CREDIT_TOTAST_FINAL  numeric(38,8) NULL,
	CREDIT_TOT_LIAB_MDA  numeric(38,8) NULL,
	CREDIT_NET_AST_MDA   numeric(38,8) NULL,
	CREDIT_CRED_MARG_MDA numeric(38,8) NULL,
	CREDIT_GUAR_SECMV_MDA numeric(38,8) NULL,
	CREDIT_FIN_LIAB_MDA  numeric(38,8) NULL,
	CREDIT_CRDT_STK_LIAB_MDA numeric(38,8) NULL,
	CREDIT_INTR_LIAB_MDA numeric(38,8) NULL,
	CREDIT_FEE_LIAB_MDA  numeric(38,8) NULL,
	CREDIT_OTHLIAB_MDA   numeric(38,8) NULL,
	CREDIT_TOTAST_MDA    numeric(38,8) NULL,
	CREDIT_TOT_LIAB_YDA  numeric(38,8) NULL,
	CREDIT_NET_AST_YDA   numeric(38,8) NULL,
	CREDIT_CRED_MARG_YDA numeric(38,8) NULL,
	CREDIT_GUAR_SECMV_YDA numeric(38,8) NULL,
	CREDIT_FIN_LIAB_YDA  numeric(38,8) NULL,
	CREDIT_CRDT_STK_LIAB_YDA numeric(38,8) NULL,
	CREDIT_INTR_LIAB_YDA numeric(38,8) NULL,
	CREDIT_FEE_LIAB_YDA  numeric(38,8) NULL,
	CREDIT_OTHLIAB_YDA   numeric(38,8) NULL,
	CREDIT_TOTAST_YDA    numeric(38,8) NULL,
	ASTCHG_ODI_CPTL_INFLOW_MTD numeric(38,8) NULL,
	ASTCHG_ODI_CPTL_OUTFLOW_MTD numeric(38,8) NULL,
	ASTCHG_ODI_MVAL_INFLOW_MTD numeric(38,8) NULL,
	ASTCHG_ODI_MVAL_OUTFLOW_MTD numeric(38,8) NULL,
	ASTCHG_CREDIT_CPTL_INFLOW_MTD numeric(38,8) NULL,
	ASTCHG_CREDIT_CPTL_OUTFLOW_MTD numeric(38,8) NULL,
	ASTCHG_ODI_ACC_CPTL_NET_INFLOW_MTD numeric(38,8) NULL,
	ASTCHG_CREDIT_CPTL_NET_INFLOW_MTD numeric(38,8) NULL,
	ASTCHG_ODI_CPTL_INFLOW_YTD numeric(38,8) NULL,
	ASTCHG_ODI_CPTL_OUTFLOW_YTD numeric(38,8) NULL,
	ASTCHG_ODI_MVAL_INFLOW_YTD numeric(38,8) NULL,
	ASTCHG_ODI_MVAL_OUTFLOW_YTD numeric(38,8) NULL,
	ASTCHG_CREDIT_CPTL_INFLOW_YTD numeric(38,8) NULL,
	ASTCHG_CREDIT_CPTL_OUTFLOW_YTD numeric(38,8) NULL,
	ASTCHG_ODI_ACC_CPTL_NET_INFLOW_YTD numeric(38,8) NULL,
	ASTCHG_CREDIT_CPTL_NET_INFLOW_YTD numeric(38,8) NULL,
	APPTBUYB_GUAR_SECMV_FINAL numeric(38,8) NULL,
	APPTBUYB_APPTBUYB_BAL_FINAL numeric(38,8) NULL,
	APPTBUYB_SH_GUAR_SECMV_FINAL numeric(38,8) NULL,
	APPTBUYB_SZ_GUAR_SECMV_FINAL numeric(38,8) NULL,
	APPTBUYB_SH_NOTS_GUAR_SECMV_FINAL numeric(38,8) NULL,
	APPTBUYB_SZ_NOTS_GUAR_SECMV_FINAL numeric(38,8) NULL,
	APPTBUYB_PROP_FINOS_BAL_FINAL numeric(38,8) NULL,
	APPTBUYB_ASSM_FINOS_BAL_FINAL numeric(38,8) NULL,
	APPTBUYB_SM_LOAN_FINO_BAL_FINAL numeric(38,8) NULL,
	APPTBUYB_GUAR_SECMV_MDA numeric(38,8) NULL,
	APPTBUYB_APPTBUYB_BAL_MDA numeric(38,8) NULL,
	APPTBUYB_SH_GUAR_SECMV_MDA numeric(38,8) NULL,
	APPTBUYB_SZ_GUAR_SECMV_MDA numeric(38,8) NULL,
	APPTBUYB_SH_NOTS_GUAR_SECMV_MDA numeric(38,8) NULL,
	APPTBUYB_SZ_NOTS_GUAR_SECMV_MDA numeric(38,8) NULL,
	APPTBUYB_PROP_FINOS_BAL_MDA numeric(38,8) NULL,
	APPTBUYB_ASSM_FINOS_BAL_MDA numeric(38,8) NULL,
	APPTBUYB_SM_LOAN_FINO_BAL_MDA numeric(38,8) NULL,
	APPTBUYB_GUAR_SECMV_YDA numeric(38,8) NULL,
	APPTBUYB_APPTBUYB_BAL_YDA numeric(38,8) NULL,
	APPTBUYB_SH_GUAR_SECMV_YDA numeric(38,8) NULL,
	APPTBUYB_SZ_GUAR_SECMV_YDA numeric(38,8) NULL,
	APPTBUYB_SH_NOTS_GUAR_SECMV_YDA numeric(38,8) NULL,
	APPTBUYB_SZ_NOTS_GUAR_SECMV_YDA numeric(38,8) NULL,
	APPTBUYB_PROP_FINOS_BAL_YDA numeric(38,8) NULL,
	APPTBUYB_ASSM_FINOS_BAL_YDA numeric(38,8) NULL,
	APPTBUYB_SM_LOAN_FINO_BAL_YDA numeric(38,8) NULL,
	STKPLG_GUAR_SECMV_FINAL numeric(38,8) NULL,
	STKPLG_STKPLG_FIN_BAL_FINAL numeric(38,8) NULL,
	STKPLG_SH_GUAR_SECMV_FINAL numeric(38,8) NULL,
	STKPLG_SZ_GUAR_SECMV_FINAL numeric(38,8) NULL,
	STKPLG_SH_NOTS_GUAR_SECMV_FINAL numeric(38,8) NULL,
	STKPLG_SZ_NOTS_GUAR_SECMV_FINAL numeric(38,8) NULL,
	STKPLG_PROP_FINOS_BAL_FINAL numeric(38,8) NULL,
	STKPLG_ASSM_FINOS_BAL_FINAL numeric(38,8) NULL,
	STKPLG_SM_LOAN_FINO_BAL_FINAL numeric(38,8) NULL,
	STKPLG_GUAR_SECMV_MDA numeric(38,8) NULL,
	STKPLG_STKPLG_FIN_BAL_MDA numeric(38,8) NULL,
	STKPLG_SH_GUAR_SECMV_MDA numeric(38,8) NULL,
	STKPLG_SZ_GUAR_SECMV_MDA numeric(38,8) NULL,
	STKPLG_SH_NOTS_GUAR_SECMV_MDA numeric(38,8) NULL,
	STKPLG_SZ_NOTS_GUAR_SECMV_MDA numeric(38,8) NULL,
	STKPLG_PROP_FINOS_BAL_MDA numeric(38,8) NULL,
	STKPLG_ASSM_FINOS_BAL_MDA numeric(38,8) NULL,
	STKPLG_SM_LOAN_FINO_BAL_MDA numeric(38,8) NULL,
	STKPLG_GUAR_SECMV_YDA numeric(38,8) NULL,
	STKPLG_STKPLG_FIN_BAL_YDA numeric(38,8) NULL,
	STKPLG_SH_GUAR_SECMV_YDA numeric(38,8) NULL,
	STKPLG_SZ_GUAR_SECMV_YDA numeric(38,8) NULL,
	STKPLG_SH_NOTS_GUAR_SECMV_YDA numeric(38,8) NULL,
	STKPLG_SZ_NOTS_GUAR_SECMV_YDA numeric(38,8) NULL,
	STKPLG_PROP_FINOS_BAL_YDA numeric(38,8) NULL,
	STKPLG_ASSM_FINOS_BAL_YDA numeric(38,8) NULL,
	STKPLG_SM_LOAN_FINO_BAL_YDA numeric(38,8) NULL,
	LOAD_DT              numeric(8) NULL,
	AST_SGMTS            varchar(30) NOT NULL,
	AFA_SEC_EMPID        varchar(60) NOT NULL,
	ODI_TRD_SCDY_TRD_FREQ_MTD numeric(38,8) NULL,
	ODI_TRD_SCDY_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_SCDY_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_TRD_FREQ_YTD numeric(38,8) NULL,
	ODI_TRD_STKF_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_STKF_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_S_REPUR_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_R_REPUR_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_S_REPUR_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_R_REPUR_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_HGT_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_SGT_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_SGT_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_HGT_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_Y_RCT_STK_TRD_QTY numeric(38,8) NULL,
	ODI_TRD_SCDY_TRD_FREQ_YTD numeric(38,8) NULL,
	ODI_TRD_TRD_FREQ_MTD numeric(38,8) NULL,
	ODI_TRD_APPTBUYB_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_APPTBUYB_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_RCT_TRD_DT_M numeric(38,8) NULL,
	ODI_TRD_STKPLG_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_STKPLG_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_PSTK_OPTN_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_PSTK_OPTN_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_REPQ_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_REPQ_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_BGDL_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_BGDL_QTY_YTD numeric(38,8) NULL,
	CUST_TYPE            varchar(30) NOT NULL,
	ODIAST_STKPLG_GUAR_SECMV_FINAL_SCDY_DEDUCT numeric(38,8) NULL,
	ODIAST_STKPLG_GUAR_SECMV_MDA_SCDY_DEDUCT numeric(38,8) NULL,
	ODIAST_STKPLG_GUAR_SECMV_YDA_SCDY_DEDUCT numeric(38,8) NULL,
	ODIAST_STKPLG_LIAB_FINAL numeric(38,8) NULL,
	ODIAST_STKPLG_LIAB_MDA numeric(38,8) NULL,
	ODIAST_STKPLG_LIAB_YDA numeric(38,8) NULL,
	ODIAST_CREDIT_TOT_LIAB_FINAL numeric(38,8) NULL,
	ODIAST_CREDIT_TOT_LIAB_MDA numeric(38,8) NULL,
	ODIAST_CREDIT_TOT_LIAB_YDA numeric(38,8) NULL,
	ODIAST_APPTBUYB_BAL_FINAL numeric(38,8) NULL,
	ODIAST_APPTBUYB_BAL_MDA numeric(38,8) NULL,
	ODIAST_APPTBUYB_BAL_YDA numeric(38,8) NULL,
	ODIAST_CREDIT_TOTAST_FINAL numeric(38,8) NULL,
	ODIAST_CREDIT_TOTAST_MDA numeric(38,8) NULL,
	ODIAST_CREDIT_TOTAST_YDA numeric(38,8) NULL,
	ODIAST_STKPLG_GUAR_SECMV_FINAL numeric(38,8) NULL,
	ODIAST_STKPLG_GUAR_SECMV_MDA numeric(38,8) NULL,
	ODIAST_STKPLG_GUAR_SECMV_YDA numeric(38,8) NULL,
	CREDIT_A_SHR_MVAL_FINAL numeric(38,8) NULL,
	CREDIT_A_SHR_MVAL_MDA numeric(38,8) NULL,
	CREDIT_A_SHR_MVAL_YDA numeric(38,8) NULL,
	ODI_INCM_PB_TRD_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_MARG_SPR_INCM_MTD numeric(38,8) NULL,
	ODI_INCM_PB_TRD_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_MARG_SPR_INCM_YTD numeric(38,8) NULL,
	ODI_INCM_GROSS_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_TRAN_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_SCDY_TRAN_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_STP_TAX_MTD numeric(38,8) NULL,
	ODI_INCM_HANDLE_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_SEC_RGLT_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_OTH_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_STKF_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_STKF_TRAN_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_STKF_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_BOND_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_BOND_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_REPQ_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_REPQ_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_HGT_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_HGT_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_HGT_TRAN_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_SGT_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_SGT_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_SGT_TRAN_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_BGDL_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_BGDL_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_BGDL_TRAN_FEE_MTD numeric(38,8) NULL,
	ODI_INCM_PSTK_OPTN_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_PSTK_OPTN_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_SCDY_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_SCDY_NET_CMS_MTD numeric(38,8) NULL,
	ODI_INCM_GROSS_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_TRAN_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_SCDY_TRAN_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_STP_TAX_YTD numeric(38,8) NULL,
	ODI_INCM_HANDLE_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_SEC_RGLT_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_OTH_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_STKF_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_STKF_TRAN_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_STKF_NET_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_BOND_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_BOND_NET_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_REPQ_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_REPQ_NET_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_HGT_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_HGT_NET_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_HGT_TRAN_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_SGT_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_SGT_NET_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_SGT_TRAN_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_BGDL_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_NET_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_BGDL_NET_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_BGDL_TRAN_FEE_YTD numeric(38,8) NULL,
	ODI_INCM_PSTK_OPTN_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_PSTK_OPTN_NET_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_SCDY_CMS_YTD numeric(38,8) NULL,
	ODI_INCM_SCDY_NET_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_MARG_SPR_INCM_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_MARG_SPR_INCM_MTD numeric(38,8) NULL,
	CRED_INCM_GROSS_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_NET_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_TRAN_FEE_MTD numeric(38,8) NULL,
	CRED_INCM_STP_TAX_MTD numeric(38,8) NULL,
	CRED_INCM_ORDR_FEE_MTD numeric(38,8) NULL,
	CRED_INCM_HANDLE_FEE_MTD numeric(38,8) NULL,
	CRED_INCM_SEC_RGLT_FEE_MTD numeric(38,8) NULL,
	CRED_INCM_OTH_FEE_MTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_ODI_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_ODI_NET_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_ODI_TRAN_FEE_MTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_CRED_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_CRED_NET_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_CRED_TRAN_FEE_MTD numeric(38,8) NULL,
	CRED_INCM_STKPLG_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_STKPLG_NET_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_STKPLG_PAIDINT_MTD numeric(38,8) NULL,
	CRED_INCM_STKPLG_RECE_INT_MTD numeric(38,8) NULL,
	CRED_INCM_APPTBUYB_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_APPTBUYB_NET_CMS_MTD numeric(38,8) NULL,
	CRED_INCM_APPTBUYB_PAIDINT_MTD numeric(38,8) NULL,
	CRED_INCM_FIN_PAIDINT_MTD numeric(38,8) NULL,
	CRED_INCM_FIN_IE_MTD numeric(38,8) NULL,
	CRED_INCM_CRDT_STK_IE_MTD numeric(38,8) NULL,
	CRED_INCM_OTH_IE_MTD numeric(38,8) NULL,
	CRED_INCM_FIN_RECE_INT_MTD numeric(38,8) NULL,
	CRED_INCM_FEE_RECE_INT_MTD numeric(38,8) NULL,
	CRED_INCM_OTH_RECE_INT_MTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_CPTL_COST_MTD numeric(38,8) NULL,
	CRED_INCM_GROSS_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_NET_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_TRAN_FEE_YTD numeric(38,8) NULL,
	CRED_INCM_STP_TAX_YTD numeric(38,8) NULL,
	CRED_INCM_ORDR_FEE_YTD numeric(38,8) NULL,
	CRED_INCM_HANDLE_FEE_YTD numeric(38,8) NULL,
	CRED_INCM_SEC_RGLT_FEE_YTD numeric(38,8) NULL,
	CRED_INCM_OTH_FEE_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_ODI_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_ODI_NET_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_ODI_TRAN_FEE_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_CRED_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_CRED_NET_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_CRED_TRAN_FEE_YTD numeric(38,8) NULL,
	CRED_INCM_STKPLG_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_STKPLG_NET_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_STKPLG_PAIDINT_YTD numeric(38,8) NULL,
	CRED_INCM_STKPLG_RECE_INT_YTD numeric(38,8) NULL,
	CRED_INCM_APPTBUYB_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_APPTBUYB_NET_CMS_YTD numeric(38,8) NULL,
	CRED_INCM_APPTBUYB_PAIDINT_YTD numeric(38,8) NULL,
	CRED_INCM_FIN_PAIDINT_YTD numeric(38,8) NULL,
	CRED_INCM_FIN_IE_YTD numeric(38,8) NULL,
	CRED_INCM_CRDT_STK_IE_YTD numeric(38,8) NULL,
	CRED_INCM_OTH_IE_YTD numeric(38,8) NULL,
	CRED_INCM_FIN_RECE_INT_YTD numeric(38,8) NULL,
	CRED_INCM_FEE_RECE_INT_YTD numeric(38,8) NULL,
	CRED_INCM_OTH_RECE_INT_YTD numeric(38,8) NULL,
	CRED_INCM_CREDIT_CPTL_COST_YTD numeric(38,8) NULL,
	CREDIT_CRED_QUO      numeric(38,8) NULL,
	APPTBUYB_CRED_QUO    numeric(38,8) NULL,
	STKPLG_CRED_QUO      numeric(38,8) NULL,
	ODI_TRD_SB_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_SB_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_BOND_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_BOND_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_ITC_CRRC_FUND_TRD_QTY_MTD numeric(38,8) NULL,
	ODI_TRD_ITC_CRRC_FUND_TRD_QTY_YTD numeric(38,8) NULL,
	ODI_TRD_S_REPUR_NET_CMS_MTD numeric(38,8) NULL,
	ODI_TRD_S_REPUR_NET_CMS_YTD numeric(38,8) NULL,
	ODI_TRD_R_REPUR_NET_CMS_MTD numeric(38,8) NULL,
	ODI_TRD_R_REPUR_NET_CMS_YTD numeric(38,8) NULL,
	ODI_TRD_ITC_CRRC_FUND_NET_CMS_MTD numeric(38,8) NULL,
	ODI_TRD_ITC_CRRC_FUND_NET_CMS_YTD numeric(38,8) NULL
);



COMMENT ON TABLE T_EVT_EMP_BIS_M IS '员工业务数据月表';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.YEAR IS '年';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.MTH IS '月';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CUST_STAT IS '客户状态';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_SPCA_ACC IS '是否特殊账户';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_PROD_NEW_CUST IS '是否产品新客户';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_CREDIT_CUST IS '是否融资融券客户';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_CREDIT_MTH_NA IS '是否融资融券月新增';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_CREDIT_YEAR_NA IS '是否融资融券年新增';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_CREDIT_EFF_CUST IS '是否融资融券有效客户';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_CREDIT_MTH_NA_EFF_ACT IS '是否融资融券月新增有效户';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.IF_CREDIT_YEAR_NA_EFF_ACT IS '是否融资融券年新增有效户';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CUST_NUM IS '客户数';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.EFF_CUST_NUM IS '有效客户数';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_CUST_NUM IS '融资融券_客户数';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_EFF_CUST_NUM IS '融资融券_有效客户数';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SCDY_MVAL_FINAL IS '普通资产_二级市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKF_MVAL_FINAL IS '普通资产_股基市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_A_SHR_MVAL_FINAL IS '普通资产_A股市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NOTS_MVAL_FINAL IS '普通资产_限售股市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OFFUND_MVAL_FINAL IS '普通资产_场内基金市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OPFUND_MVAL_FINAL IS '普通资产_场外基金市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SB_MVAL_FINAL IS '普通资产_三板市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_IMGT_PD_MVAL_FINAL IS '普通资产_资管产品市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_BANK_CHRM_MVAL_FINAL IS '普通资产_银行理财市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SECU_CHRM_MVAL_FINAL IS '普通资产_证券理财市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PSTK_OPTN_MVAL_FINAL IS '普通资产_个股期权市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_B_SHR_MVAL_FINAL IS '普通资产_B股市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OUTMARK_MVAL_FINAL IS '普通资产_体外市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_FINAL IS '普通资产_资金余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NO_ARVD_CPTL_FINAL IS '普通资产_未到账资金_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PTE_FUND_MVAL_FINAL IS '普通资产_私募基金市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OVERSEA_TOTAST_FINAL IS '普通资产_海外总资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_FUTR_TOTAST_FINAL IS '普通资产_期货总资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_RMB_FINAL IS '普通资产_资金余额人民币_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_HKD_FINAL IS '普通资产_资金余额港币_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_USD_FINAL IS '普通资产_资金余额美元_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_LOW_RISK_TOTAST_FINAL IS '普通资产_低风险总资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_FUND_SPACCT_MVAL_FINAL IS '普通资产_基金专户市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_HGT_MVAL_FINAL IS '普通资产_沪港通市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SGT_MVAL_FINAL IS '普通资产_深港通市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NET_AST_FINAL IS '普通资产_净资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_CONTAIN_NOTS_FINAL IS '普通资产_总资产_含限售股_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_N_CONTAIN_NOTS_FINAL IS '普通资产_总资产_不含限售股_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_BOND_MVAL_FINAL IS '普通资产_债券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_REPO_MVAL_FINAL IS '普通资产_回购市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TREA_REPO_MVAL_FINAL IS '普通资产_国债回购市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_REPQ_MVAL_FINAL IS '普通资产_报价回购市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SCDY_MVAL_MDA IS '普通资产_二级市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKF_MVAL_MDA IS '普通资产_股基市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_A_SHR_MVAL_MDA IS '普通资产_A股市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NOTS_MVAL_MDA IS '普通资产_限售股市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OFFUND_MVAL_MDA IS '普通资产_场内基金市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OPFUND_MVAL_MDA IS '普通资产_场外基金市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SB_MVAL_MDA IS '普通资产_三板市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_IMGT_PD_MVAL_MDA IS '普通资产_资管产品市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_BANK_CHRM_MVAL_MDA IS '普通资产_银行理财市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SECU_CHRM_MVAL_MDA IS '普通资产_证券理财市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PSTK_OPTN_MVAL_MDA IS '普通资产_个股期权市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_B_SHR_MVAL_MDA IS '普通资产_B股市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OUTMARK_MVAL_MDA IS '普通资产_体外市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_MDA IS '普通资产_资金余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NO_ARVD_CPTL_MDA IS '普通资产_未到账资金_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PTE_FUND_MVAL_MDA IS '普通资产_私募基金市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OVERSEA_TOTAST_MDA IS '普通资产_海外总资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_FUTR_TOTAST_MDA IS '普通资产_期货总资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_RMB_MDA IS '普通资产_资金余额人民币_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_HKD_MDA IS '普通资产_资金余额港币_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_USD_MDA IS '普通资产_资金余额美元_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_LOW_RISK_TOTAST_MDA IS '普通资产_低风险总资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_FUND_SPACCT_MVAL_MDA IS '普通资产_基金专户市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_HGT_MVAL_MDA IS '普通资产_沪港通市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SGT_MVAL_MDA IS '普通资产_深港通市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NET_AST_MDA IS '普通资产_净资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_CONTAIN_NOTS_MDA IS '普通资产_总资产_含限售股_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_N_CONTAIN_NOTS_MDA IS '普通资产_总资产_不含限售股_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_BOND_MVAL_MDA IS '普通资产_债券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_REPO_MVAL_MDA IS '普通资产_回购市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TREA_REPO_MVAL_MDA IS '普通资产_国债回购市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_REPQ_MVAL_MDA IS '普通资产_报价回购市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SCDY_MVAL_YDA IS '普通资产_二级市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKF_MVAL_YDA IS '普通资产_股基市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_A_SHR_MVAL_YDA IS '普通资产_A股市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NOTS_MVAL_YDA IS '普通资产_限售股市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OFFUND_MVAL_YDA IS '普通资产_场内基金市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OPFUND_MVAL_YDA IS '普通资产_场外基金市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SB_MVAL_YDA IS '普通资产_三板市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_IMGT_PD_MVAL_YDA IS '普通资产_资管产品市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_BANK_CHRM_MVAL_YDA IS '普通资产_银行理财市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SECU_CHRM_MVAL_YDA IS '普通资产_证券理财市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PSTK_OPTN_MVAL_YDA IS '普通资产_个股期权市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_B_SHR_MVAL_YDA IS '普通资产_B股市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OUTMARK_MVAL_YDA IS '普通资产_体外市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_YDA IS '普通资产_资金余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NO_ARVD_CPTL_YDA IS '普通资产_未到账资金_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PTE_FUND_MVAL_YDA IS '普通资产_私募基金市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OVERSEA_TOTAST_YDA IS '普通资产_海外总资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_FUTR_TOTAST_YDA IS '普通资产_期货总资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_RMB_YDA IS '普通资产_资金余额人民币_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_HKD_YDA IS '普通资产_资金余额港币_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CPTL_BAL_USD_YDA IS '普通资产_资金余额美元_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_LOW_RISK_TOTAST_YDA IS '普通资产_低风险总资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_FUND_SPACCT_MVAL_YDA IS '普通资产_基金专户市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_HGT_MVAL_YDA IS '普通资产_沪港通市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_SGT_MVAL_YDA IS '普通资产_深港通市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_NET_AST_YDA IS '普通资产_净资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_CONTAIN_NOTS_YDA IS '普通资产_总资产_含限售股_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_N_CONTAIN_NOTS_YDA IS '普通资产_总资产_不含限售股_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_BOND_MVAL_YDA IS '普通资产_债券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_REPO_MVAL_YDA IS '普通资产_回购市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TREA_REPO_MVAL_YDA IS '普通资产_国债回购市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_REPQ_MVAL_YDA IS '普通资产_报价回购市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PO_FUND_MVAL_FINAL IS '普通资产_公募基金市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PO_FUND_MVAL_MDA IS '普通资产_公募基金市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PO_FUND_MVAL_YDA IS '普通资产_公募基金市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKT_FUND_MVAL_FINAL IS '普通资产_股票型基金市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OTH_PROD_MVAL_FINAL IS '普通资产_其他产品市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OTH_AST_MVAL_FINAL IS '普通资产_其他资产市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_APPTBUYB_PLG_MVAL_FINAL IS '普通资产_约定购回质押市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKT_FUND_MVAL_MDA IS '普通资产_股票型基金市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OTH_PROD_MVAL_MDA IS '普通资产_其他产品市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OTH_AST_MVAL_MDA IS '普通资产_其他资产市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_APPTBUYB_PLG_MVAL_MDA IS '普通资产_约定购回质押市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKT_FUND_MVAL_YDA IS '普通资产_股票型基金市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OTH_PROD_MVAL_YDA IS '普通资产_其他产品市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_OTH_AST_MVAL_YDA IS '普通资产_其他资产市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_APPTBUYB_PLG_MVAL_YDA IS '普通资产_约定购回质押市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_NET_AST_FINAL IS '普通资产_融资融券净资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_MARG_FINAL IS '普通资产_融资融券保证金_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_BAL_FINAL IS '普通资产_融资融券余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_NET_AST_MDA IS '普通资产_融资融券净资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_MARG_MDA IS '普通资产_融资融券保证金_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_BAL_MDA IS '普通资产_融资融券余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_NET_AST_YDA IS '普通资产_融资融券净资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_MARG_YDA IS '普通资产_融资融券保证金_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_BAL_YDA IS '普通资产_融资融券余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PROD_TOT_MVAL_FINAL IS '普通资产_产品总市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PROD_TOT_MVAL_MDA IS '普通资产_产品总市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_PROD_TOT_MVAL_YDA IS '普通资产_产品总市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_FINAL IS '普通资产_总资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_MDA IS '普通资产_总资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_TOTAST_YDA IS '普通资产_总资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_TOT_LIAB_FINAL IS '融资融券_总负债_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_NET_AST_FINAL IS '融资融券_净资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_CRED_MARG_FINAL IS '融资融券_信用保证金_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_GUAR_SECMV_FINAL IS '融资融券_担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_FIN_LIAB_FINAL IS '融资融券_融资负债_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_CRDT_STK_LIAB_FINAL IS '融资融券_融券负债_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_INTR_LIAB_FINAL IS '融资融券_利息负债_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_FEE_LIAB_FINAL IS '融资融券_费用负债_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_OTHLIAB_FINAL IS '融资融券_其他负债_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_TOTAST_FINAL IS '融资融券_总资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_TOT_LIAB_MDA IS '融资融券_总负债_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_NET_AST_MDA IS '融资融券_净资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_CRED_MARG_MDA IS '融资融券_信用保证金_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_GUAR_SECMV_MDA IS '融资融券_担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_FIN_LIAB_MDA IS '融资融券_融资负债_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_CRDT_STK_LIAB_MDA IS '融资融券_融券负债_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_INTR_LIAB_MDA IS '融资融券_利息负债_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_FEE_LIAB_MDA IS '融资融券_费用负债_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_OTHLIAB_MDA IS '融资融券_其他负债_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_TOTAST_MDA IS '融资融券_总资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_TOT_LIAB_YDA IS '融资融券_总负债_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_NET_AST_YDA IS '融资融券_净资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_CRED_MARG_YDA IS '融资融券_信用保证金_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_GUAR_SECMV_YDA IS '融资融券_担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_FIN_LIAB_YDA IS '融资融券_融资负债_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_CRDT_STK_LIAB_YDA IS '融资融券_融券负债_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_INTR_LIAB_YDA IS '融资融券_利息负债_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_FEE_LIAB_YDA IS '融资融券_费用负债_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_OTHLIAB_YDA IS '融资融券_其他负债_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_TOTAST_YDA IS '融资融券_总资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_CPTL_INFLOW_MTD IS '资产变动_普通资金流入_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_CPTL_OUTFLOW_MTD IS '资产变动_普通资金流出_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_MVAL_INFLOW_MTD IS '资产变动_普通市值流入_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_MVAL_OUTFLOW_MTD IS '资产变动_普通市值流出_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_CREDIT_CPTL_INFLOW_MTD IS '资产变动_两融资金流入_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_CREDIT_CPTL_OUTFLOW_MTD IS '资产变动_两融资金流出_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_ACC_CPTL_NET_INFLOW_MTD IS '资产变动_普通账户资金净流入_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_CREDIT_CPTL_NET_INFLOW_MTD IS '资产变动_两融资金净流入_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_CPTL_INFLOW_YTD IS '资产变动_普通资金流入_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_CPTL_OUTFLOW_YTD IS '资产变动_普通资金流出_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_MVAL_INFLOW_YTD IS '资产变动_普通市值流入_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_MVAL_OUTFLOW_YTD IS '资产变动_普通市值流出_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_CREDIT_CPTL_INFLOW_YTD IS '资产变动_两融资金流入_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_CREDIT_CPTL_OUTFLOW_YTD IS '资产变动_两融资金流出_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_ODI_ACC_CPTL_NET_INFLOW_YTD IS '资产变动_普通账户资金净流入_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ASTCHG_CREDIT_CPTL_NET_INFLOW_YTD IS '资产变动_两融资金净流入_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_GUAR_SECMV_FINAL IS '约定购回_担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_APPTBUYB_BAL_FINAL IS '约定购回_约定购回余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SH_GUAR_SECMV_FINAL IS '约定购回_上海担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SZ_GUAR_SECMV_FINAL IS '约定购回_深圳担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SH_NOTS_GUAR_SECMV_FINAL IS '约定购回_上海限售股担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SZ_NOTS_GUAR_SECMV_FINAL IS '约定购回_深圳限售股担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_PROP_FINOS_BAL_FINAL IS '约定购回_自营融出方余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_ASSM_FINOS_BAL_FINAL IS '约定购回_资管融出方余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SM_LOAN_FINO_BAL_FINAL IS '约定购回_小额贷融出余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_GUAR_SECMV_MDA IS '约定购回_担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_APPTBUYB_BAL_MDA IS '约定购回_约定购回余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SH_GUAR_SECMV_MDA IS '约定购回_上海担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SZ_GUAR_SECMV_MDA IS '约定购回_深圳担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SH_NOTS_GUAR_SECMV_MDA IS '约定购回_上海限售股担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SZ_NOTS_GUAR_SECMV_MDA IS '约定购回_深圳限售股担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_PROP_FINOS_BAL_MDA IS '约定购回_自营融出方余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_ASSM_FINOS_BAL_MDA IS '约定购回_资管融出方余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SM_LOAN_FINO_BAL_MDA IS '约定购回_小额贷融出余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_GUAR_SECMV_YDA IS '约定购回_担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_APPTBUYB_BAL_YDA IS '约定购回_约定购回余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SH_GUAR_SECMV_YDA IS '约定购回_上海担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SZ_GUAR_SECMV_YDA IS '约定购回_深圳担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SH_NOTS_GUAR_SECMV_YDA IS '约定购回_上海限售股担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SZ_NOTS_GUAR_SECMV_YDA IS '约定购回_深圳限售股担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_PROP_FINOS_BAL_YDA IS '约定购回_自营融出方余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_ASSM_FINOS_BAL_YDA IS '约定购回_资管融出方余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_SM_LOAN_FINO_BAL_YDA IS '约定购回_小额贷融出余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_GUAR_SECMV_FINAL IS '股票质押_担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_STKPLG_FIN_BAL_FINAL IS '股票质押_股票质押融资余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SH_GUAR_SECMV_FINAL IS '股票质押_上海担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SZ_GUAR_SECMV_FINAL IS '股票质押_深圳担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SH_NOTS_GUAR_SECMV_FINAL IS '股票质押_上海限售股担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SZ_NOTS_GUAR_SECMV_FINAL IS '股票质押_深圳限售股担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_PROP_FINOS_BAL_FINAL IS '股票质押_自营融出方余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_ASSM_FINOS_BAL_FINAL IS '股票质押_资管融出方余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SM_LOAN_FINO_BAL_FINAL IS '股票质押_小额贷融出余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_GUAR_SECMV_MDA IS '股票质押_担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_STKPLG_FIN_BAL_MDA IS '股票质押_股票质押融资余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SH_GUAR_SECMV_MDA IS '股票质押_上海担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SZ_GUAR_SECMV_MDA IS '股票质押_深圳担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SH_NOTS_GUAR_SECMV_MDA IS '股票质押_上海限售股担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SZ_NOTS_GUAR_SECMV_MDA IS '股票质押_深圳限售股担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_PROP_FINOS_BAL_MDA IS '股票质押_自营融出方余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_ASSM_FINOS_BAL_MDA IS '股票质押_资管融出方余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SM_LOAN_FINO_BAL_MDA IS '股票质押_小额贷融出余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_GUAR_SECMV_YDA IS '股票质押_担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_STKPLG_FIN_BAL_YDA IS '股票质押_股票质押融资余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SH_GUAR_SECMV_YDA IS '股票质押_上海担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SZ_GUAR_SECMV_YDA IS '股票质押_深圳担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SH_NOTS_GUAR_SECMV_YDA IS '股票质押_上海限售股担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SZ_NOTS_GUAR_SECMV_YDA IS '股票质押_深圳限售股担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_PROP_FINOS_BAL_YDA IS '股票质押_自营融出方余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_ASSM_FINOS_BAL_YDA IS '股票质押_资管融出方余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_SM_LOAN_FINO_BAL_YDA IS '股票质押_小额贷融出余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.LOAD_DT IS '清洗日期';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.AST_SGMTS IS '资产段';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_SCDY_TRD_FREQ_MTD IS '普通交易_二级交易次数_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_SCDY_TRD_QTY_MTD IS '普通交易_二级交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_SCDY_TRD_QTY_YTD IS '普通交易_二级交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_TRD_FREQ_YTD IS '普通交易_交易次数_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_STKF_TRD_QTY_MTD IS '普通交易_股基交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_STKF_TRD_QTY_YTD IS '普通交易_股基交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_S_REPUR_TRD_QTY_MTD IS '普通交易_正回购交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_R_REPUR_TRD_QTY_MTD IS '普通交易_逆回购交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_S_REPUR_TRD_QTY_YTD IS '普通交易_正回购交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_R_REPUR_TRD_QTY_YTD IS '普通交易_逆回购交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_HGT_TRD_QTY_MTD IS '普通交易_沪港通交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_SGT_TRD_QTY_MTD IS '普通交易_深港通交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_SGT_TRD_QTY_YTD IS '普通交易_深港通交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_HGT_TRD_QTY_YTD IS '普通交易_沪港通交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_Y_RCT_STK_TRD_QTY IS '普通交易_近12月股票交易量';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_SCDY_TRD_FREQ_YTD IS '普通交易_二级交易次数_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_TRD_FREQ_MTD IS '普通交易_交易次数_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_APPTBUYB_TRD_QTY_MTD IS '普通交易_约定购回交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_APPTBUYB_TRD_QTY_YTD IS '普通交易_约定购回交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_RCT_TRD_DT_M IS '普通交易_最近交易日期_本月';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_STKPLG_TRD_QTY_MTD IS '普通交易_股票质押交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_STKPLG_TRD_QTY_YTD IS '普通交易_股票质押交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_PSTK_OPTN_TRD_QTY_MTD IS '普通交易_个股期权交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_PSTK_OPTN_TRD_QTY_YTD IS '普通交易_个股期权交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_REPQ_TRD_QTY_MTD IS '普通交易_报价回购交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_REPQ_TRD_QTY_YTD IS '普通交易_报价回购交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_BGDL_QTY_MTD IS '普通交易_大宗交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_BGDL_QTY_YTD IS '普通交易_大宗交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CUST_TYPE IS '客户类型';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_GUAR_SECMV_FINAL_SCDY_DEDUCT IS '普通资产_股票质押担保证券市值_期末_二级扣减';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_GUAR_SECMV_MDA_SCDY_DEDUCT IS '普通资产_股票质押担保证券市值_月日均_二级扣减';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_GUAR_SECMV_YDA_SCDY_DEDUCT IS '普通资产_股票质押担保证券市值_年日均_二级扣减';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_LIAB_FINAL IS '普通资产_股票质押负债_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_LIAB_MDA IS '普通资产_股票质押负债_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_LIAB_YDA IS '普通资产_股票质押负债_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_TOT_LIAB_FINAL IS '普通资产_融资融券总负债_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_TOT_LIAB_MDA IS '普通资产_融资融券总负债_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_TOT_LIAB_YDA IS '普通资产_融资融券总负债_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_APPTBUYB_BAL_FINAL IS '普通资产_约定购回余额_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_APPTBUYB_BAL_MDA IS '普通资产_约定购回余额_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_APPTBUYB_BAL_YDA IS '普通资产_约定购回余额_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_TOTAST_FINAL IS '普通资产_融资融券总资产_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_TOTAST_MDA IS '普通资产_融资融券总资产_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_CREDIT_TOTAST_YDA IS '普通资产_融资融券总资产_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_GUAR_SECMV_FINAL IS '普通资产_股票质押担保证券市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_GUAR_SECMV_MDA IS '普通资产_股票质押担保证券市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODIAST_STKPLG_GUAR_SECMV_YDA IS '普通资产_股票质押担保证券市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_A_SHR_MVAL_FINAL IS '融资融券_A股市值_期末';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_A_SHR_MVAL_MDA IS '融资融券_A股市值_月日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_A_SHR_MVAL_YDA IS '融资融券_A股市值_年日均';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_PB_TRD_CMS_MTD IS '普通收入_PB交易佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_MARG_SPR_INCM_MTD IS '普通收入_保证金利差收入_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_PB_TRD_CMS_YTD IS '普通收入_PB交易佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_MARG_SPR_INCM_YTD IS '普通收入_保证金利差收入_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_GROSS_CMS_MTD IS '普通收入_毛佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_TRAN_FEE_MTD IS '普通收入_过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SCDY_TRAN_FEE_MTD IS '普通收入_二级过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_STP_TAX_MTD IS '普通收入_印花税_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_HANDLE_FEE_MTD IS '普通收入_经手费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SEC_RGLT_FEE_MTD IS '普通收入_证管费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_OTH_FEE_MTD IS '普通收入_其他费用_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_STKF_CMS_MTD IS '普通收入_股基佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_STKF_TRAN_FEE_MTD IS '普通收入_股基过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_STKF_NET_CMS_MTD IS '普通收入_股基净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BOND_CMS_MTD IS '普通收入_债券佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BOND_NET_CMS_MTD IS '普通收入_债券净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_REPQ_CMS_MTD IS '普通收入_报价回购佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_REPQ_NET_CMS_MTD IS '普通收入_报价回购净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_HGT_CMS_MTD IS '普通收入_沪港通佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_HGT_NET_CMS_MTD IS '普通收入_沪港通净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_HGT_TRAN_FEE_MTD IS '普通收入_沪港通过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SGT_CMS_MTD IS '普通收入_深港通佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SGT_NET_CMS_MTD IS '普通收入_深港通净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SGT_TRAN_FEE_MTD IS '普通收入_深港通过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BGDL_CMS_MTD IS '普通收入_大宗交易佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_NET_CMS_MTD IS '普通收入_净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BGDL_NET_CMS_MTD IS '普通收入_大宗交易净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BGDL_TRAN_FEE_MTD IS '普通收入_大宗交易过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_PSTK_OPTN_CMS_MTD IS '普通收入_个股期权佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_PSTK_OPTN_NET_CMS_MTD IS '普通收入_个股期权净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SCDY_CMS_MTD IS '普通收入_二级佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SCDY_NET_CMS_MTD IS '普通收入_二级净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_GROSS_CMS_YTD IS '普通收入_毛佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_TRAN_FEE_YTD IS '普通收入_过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SCDY_TRAN_FEE_YTD IS '普通收入_二级过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_STP_TAX_YTD IS '普通收入_印花税_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_HANDLE_FEE_YTD IS '普通收入_经手费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SEC_RGLT_FEE_YTD IS '普通收入_证管费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_OTH_FEE_YTD IS '普通收入_其他费用_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_STKF_CMS_YTD IS '普通收入_股基佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_STKF_TRAN_FEE_YTD IS '普通收入_股基过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_STKF_NET_CMS_YTD IS '普通收入_股基净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BOND_CMS_YTD IS '普通收入_债券佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BOND_NET_CMS_YTD IS '普通收入_债券净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_REPQ_CMS_YTD IS '普通收入_报价回购佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_REPQ_NET_CMS_YTD IS '普通收入_报价回购净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_HGT_CMS_YTD IS '普通收入_沪港通佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_HGT_NET_CMS_YTD IS '普通收入_沪港通净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_HGT_TRAN_FEE_YTD IS '普通收入_沪港通过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SGT_CMS_YTD IS '普通收入_深港通佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SGT_NET_CMS_YTD IS '普通收入_深港通净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SGT_TRAN_FEE_YTD IS '普通收入_深港通过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BGDL_CMS_YTD IS '普通收入_大宗交易佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_NET_CMS_YTD IS '普通收入_净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BGDL_NET_CMS_YTD IS '普通收入_大宗交易净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_BGDL_TRAN_FEE_YTD IS '普通收入_大宗交易过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_PSTK_OPTN_CMS_YTD IS '普通收入_个股期权佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_PSTK_OPTN_NET_CMS_YTD IS '普通收入_个股期权净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SCDY_CMS_YTD IS '普通收入_二级佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_INCM_SCDY_NET_CMS_YTD IS '普通收入_二级净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_MARG_SPR_INCM_YTD IS '信用收入_融资融券保证金利差收入_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_MARG_SPR_INCM_MTD IS '信用收入_融资融券保证金利差收入_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_GROSS_CMS_MTD IS '信用收入_毛佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_NET_CMS_MTD IS '信用收入_净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_TRAN_FEE_MTD IS '信用收入_过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STP_TAX_MTD IS '信用收入_印花税_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_ORDR_FEE_MTD IS '信用收入_委托费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_HANDLE_FEE_MTD IS '信用收入_经手费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_SEC_RGLT_FEE_MTD IS '信用收入_证管费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_OTH_FEE_MTD IS '信用收入_其他费用_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_ODI_CMS_MTD IS '信用收入_融资融券普通佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_ODI_NET_CMS_MTD IS '信用收入_融资融券普通净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_ODI_TRAN_FEE_MTD IS '信用收入_融资融券普通过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_CRED_CMS_MTD IS '信用收入_融资融券信用佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_CRED_NET_CMS_MTD IS '信用收入_融资融券信用净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_CRED_TRAN_FEE_MTD IS '信用收入_融资融券信用过户费_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STKPLG_CMS_MTD IS '信用收入_股票质押佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STKPLG_NET_CMS_MTD IS '信用收入_股票质押净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STKPLG_PAIDINT_MTD IS '信用收入_股票质押实收利息_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STKPLG_RECE_INT_MTD IS '信用收入_股票质押应收利息_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_APPTBUYB_CMS_MTD IS '信用收入_约定购回佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_APPTBUYB_NET_CMS_MTD IS '信用收入_约定购回净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_APPTBUYB_PAIDINT_MTD IS '信用收入_约定购回实收利息_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_FIN_PAIDINT_MTD IS '信用收入_融资实收利息_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_FIN_IE_MTD IS '信用收入_融资利息支出_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CRDT_STK_IE_MTD IS '信用收入_融券利息支出_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_OTH_IE_MTD IS '信用收入_其他利息支出_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_FIN_RECE_INT_MTD IS '信用收入_融资应收利息_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_FEE_RECE_INT_MTD IS '信用收入_费用应收利息_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_OTH_RECE_INT_MTD IS '信用收入_其他应收利息_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_CPTL_COST_MTD IS '信用收入_融资融券资金成本_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_GROSS_CMS_YTD IS '信用收入_毛佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_NET_CMS_YTD IS '信用收入_净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_TRAN_FEE_YTD IS '信用收入_过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STP_TAX_YTD IS '信用收入_印花税_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_ORDR_FEE_YTD IS '信用收入_委托费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_HANDLE_FEE_YTD IS '信用收入_经手费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_SEC_RGLT_FEE_YTD IS '信用收入_证管费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_OTH_FEE_YTD IS '信用收入_其他费用_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_ODI_CMS_YTD IS '信用收入_融资融券普通佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_ODI_NET_CMS_YTD IS '信用收入_融资融券普通净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_ODI_TRAN_FEE_YTD IS '信用收入_融资融券普通过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_CRED_CMS_YTD IS '信用收入_融资融券信用佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_CRED_NET_CMS_YTD IS '信用收入_融资融券信用净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_CRED_TRAN_FEE_YTD IS '信用收入_融资融券信用过户费_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STKPLG_CMS_YTD IS '信用收入_股票质押佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STKPLG_NET_CMS_YTD IS '信用收入_股票质押净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STKPLG_PAIDINT_YTD IS '信用收入_股票质押实收利息_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_STKPLG_RECE_INT_YTD IS '信用收入_股票质押应收利息_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_APPTBUYB_CMS_YTD IS '信用收入_约定购回佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_APPTBUYB_NET_CMS_YTD IS '信用收入_约定购回净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_APPTBUYB_PAIDINT_YTD IS '信用收入_约定购回实收利息_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_FIN_PAIDINT_YTD IS '信用收入_融资实收利息_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_FIN_IE_YTD IS '信用收入_融资利息支出_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CRDT_STK_IE_YTD IS '信用收入_融券利息支出_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_OTH_IE_YTD IS '信用收入_其他利息支出_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_FIN_RECE_INT_YTD IS '信用收入_融资应收利息_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_FEE_RECE_INT_YTD IS '信用收入_费用应收利息_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_OTH_RECE_INT_YTD IS '信用收入_其他应收利息_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CRED_INCM_CREDIT_CPTL_COST_YTD IS '信用收入_融资融券资金成本_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.CREDIT_CRED_QUO IS '融资融券授信额度';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.APPTBUYB_CRED_QUO IS '约定购回授信额度';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.STKPLG_CRED_QUO IS '股票质押授信额度';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_SB_TRD_QTY_MTD IS '普通交易_三板交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_SB_TRD_QTY_YTD IS '普通交易_三板交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_BOND_TRD_QTY_MTD IS '普通交易_债券交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_BOND_TRD_QTY_YTD IS '普通交易_债券交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_ITC_CRRC_FUND_TRD_QTY_MTD IS '普通交易_场内货币基金交易量_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_ITC_CRRC_FUND_TRD_QTY_YTD IS '普通交易_场内货币基金交易量_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_S_REPUR_NET_CMS_MTD IS '普通交易_正回购净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_S_REPUR_NET_CMS_YTD IS '普通交易_正回购净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_R_REPUR_NET_CMS_MTD IS '普通交易_逆回购净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_R_REPUR_NET_CMS_YTD IS '普通交易_逆回购净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_ITC_CRRC_FUND_NET_CMS_MTD IS '普通交易_场内货币基金净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMP_BIS_M.ODI_TRD_ITC_CRRC_FUND_NET_CMS_YTD IS '普通交易_场内货币基金净佣金_年累计';



ALTER TABLE T_EVT_EMP_BIS_M
	ADD PRIMARY KEY (YEAR,MTH,ORG_NO,AFA_SEC_EMPID,CUST_STAT,IF_SPCA_ACC,IF_PROD_NEW_CUST,IF_MTH_NA,IF_YEAR_NA,IF_CREDIT_CUST,IF_CREDIT_MTH_NA,IF_CREDIT_YEAR_NA,IF_CREDIT_EFF_CUST,IF_CREDIT_MTH_NA_EFF_ACT,IF_CREDIT_YEAR_NA_EFF_ACT,AST_SGMTS,CUST_TYPE);


