
CREATE TABLE T_AST_EMPCUS_APPTBUYB_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	WH_ORG_ID_CUST       character varying(100) NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	PERFM_RATI9_CREDIT   numeric(38,8) NULL,
	GUAR_SECMV_FINAL     numeric(38,8) NULL,
	APPTBUYB_BAL_FINAL   numeric(38,8) NULL,
	SH_GUAR_SECMV_FINAL  numeric(38,8) NULL,
	SZ_GUAR_SECMV_FINAL  numeric(38,8) NULL,
	SH_NOTS_GUAR_SECMV_FINAL numeric(38,8) NULL,
	SZ_NOTS_GUAR_SECMV_FINAL numeric(38,8) NULL,
	PROP_FINOS_BAL_FINAL numeric(38,8) NULL,
	ASSM_FINOS_BAL_FINAL numeric(38,8) NULL,
	SM_LOAN_FINO_BAL_FINAL numeric(38,8) NULL,
	GUAR_SECMV_MDA       numeric(38,8) NULL,
	APPTBUYB_BAL_MDA     numeric(38,8) NULL,
	SH_GUAR_SECMV_MDA    numeric(38,8) NULL,
	SZ_GUAR_SECMV_MDA    numeric(38,8) NULL,
	SH_NOTS_GUAR_SECMV_MDA numeric(38,8) NULL,
	SZ_NOTS_GUAR_SECMV_MDA numeric(38,8) NULL,
	PROP_FINOS_BAL_MDA   numeric(38,8) NULL,
	ASSM_FINOS_BAL_MDA   numeric(38,8) NULL,
	SM_LOAN_FINO_BAL_MDA numeric(38,8) NULL,
	GUAR_SECMV_YDA       numeric(38,8) NULL,
	APPTBUYB_BAL_YDA     numeric(38,8) NULL,
	SH_GUAR_SECMV_YDA    numeric(38,8) NULL,
	SZ_GUAR_SECMV_YDA    numeric(38,8) NULL,
	SH_NOTS_GUAR_SECMV_YDA numeric(38,8) NULL,
	SZ_NOTS_GUAR_SECMV_YDA numeric(38,8) NULL,
	PROP_FINOS_BAL_YDA   numeric(38,8) NULL,
	ASSM_FINOS_BAL_YDA   numeric(38,8) NULL,
	SM_LOAN_FINO_BAL_YDA numeric(38,8) NULL,
	LOAD_DT              numeric(8,0) NULL
);



COMMENT ON TABLE T_AST_EMPCUS_APPTBUYB_M_D IS '员工客户约定购回月表';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.YEAR IS '年';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.MTH IS '月';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.PERFM_RATI9_CREDIT IS '绩效比例9_融资融券';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.GUAR_SECMV_FINAL IS '担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.APPTBUYB_BAL_FINAL IS '约定购回余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SH_GUAR_SECMV_FINAL IS '上海担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SZ_GUAR_SECMV_FINAL IS '深圳担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SH_NOTS_GUAR_SECMV_FINAL IS '上海限售股担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SZ_NOTS_GUAR_SECMV_FINAL IS '深圳限售股担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.PROP_FINOS_BAL_FINAL IS '自营融出方余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.ASSM_FINOS_BAL_FINAL IS '资管融出方余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SM_LOAN_FINO_BAL_FINAL IS '小额贷融出余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.GUAR_SECMV_MDA IS '担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.APPTBUYB_BAL_MDA IS '约定购回余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SH_GUAR_SECMV_MDA IS '上海担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SZ_GUAR_SECMV_MDA IS '深圳担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SH_NOTS_GUAR_SECMV_MDA IS '上海限售股担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SZ_NOTS_GUAR_SECMV_MDA IS '深圳限售股担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.PROP_FINOS_BAL_MDA IS '自营融出方余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.ASSM_FINOS_BAL_MDA IS '资管融出方余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SM_LOAN_FINO_BAL_MDA IS '小额贷融出余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.GUAR_SECMV_YDA IS '担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.APPTBUYB_BAL_YDA IS '约定购回余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SH_GUAR_SECMV_YDA IS '上海担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SZ_GUAR_SECMV_YDA IS '深圳担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SH_NOTS_GUAR_SECMV_YDA IS '上海限售股担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SZ_NOTS_GUAR_SECMV_YDA IS '深圳限售股担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.PROP_FINOS_BAL_YDA IS '自营融出方余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.ASSM_FINOS_BAL_YDA IS '资管融出方余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.SM_LOAN_FINO_BAL_YDA IS '小额贷融出余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_APPTBUYB_M_D.LOAD_DT IS '清洗日期';



ALTER TABLE T_AST_EMPCUS_APPTBUYB_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID);



CREATE TABLE T_AST_EMPCUS_CPTL_CHG_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	WH_ORG_ID_CUST       character varying(100) NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	PERFM_RATI1_SCDY_AST numeric(38,8) NULL,
	PERFM_RATI9_CREDIT   numeric(38,8) NULL,
	ODI_CPTL_INFLOW_MTD  numeric(38,8) NULL,
	ODI_CPTL_OUTFLOW_MTD numeric(38,8) NULL,
	ODI_MVAL_INFLOW_MTD  numeric(38,8) NULL,
	ODI_MVAL_OUTFLOW_MTD numeric(38,8) NULL,
	CREDIT_CPTL_INFLOW_MTD numeric(38,8) NULL,
	CREDIT_CPTL_OUTFLOW_MTD numeric(38,8) NULL,
	ODI_ACC_CPTL_NET_INFLOW_MTD numeric(38,8) NULL,
	CREDIT_CPTL_NET_INFLOW_MTD numeric(38,8) NULL,
	ODI_CPTL_INFLOW_YTD  numeric(38,8) NULL,
	ODI_CPTL_OUTFLOW_YTD numeric(38,8) NULL,
	ODI_MVAL_INFLOW_YTD  numeric(38,8) NULL,
	ODI_MVAL_OUTFLOW_YTD numeric(38,8) NULL,
	CREDIT_CPTL_INFLOW_YTD numeric(38,8) NULL,
	CREDIT_CPTL_OUTFLOW_YTD numeric(38,8) NULL,
	ODI_ACC_CPTL_NET_INFLOW_YTD numeric(38,8) NULL,
	CREDIT_CPTL_NET_INFLOW_YTD numeric(38,8) NULL,
	LOAD_DT              numeric(8,0) NULL
);



COMMENT ON TABLE T_AST_EMPCUS_CPTL_CHG_M_D IS '员工客户资产变动月表';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.YEAR IS '年';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.MTH IS '月';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.PERFM_RATI1_SCDY_AST IS '绩效比例1_二级资产';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.PERFM_RATI9_CREDIT IS '绩效比例9_融资融券';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_CPTL_INFLOW_MTD IS '普通资金流入_月累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_CPTL_OUTFLOW_MTD IS '普通资金流出_月累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_MVAL_INFLOW_MTD IS '普通市值流入_月累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_MVAL_OUTFLOW_MTD IS '普通市值流出_月累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.CREDIT_CPTL_INFLOW_MTD IS '两融资金流入_月累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.CREDIT_CPTL_OUTFLOW_MTD IS '两融资金流出_月累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_ACC_CPTL_NET_INFLOW_MTD IS '普通账户资金净流入_月累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.CREDIT_CPTL_NET_INFLOW_MTD IS '两融资金净流入_月累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_CPTL_INFLOW_YTD IS '普通资金流入_年累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_CPTL_OUTFLOW_YTD IS '普通资金流出_年累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_MVAL_INFLOW_YTD IS '普通市值流入_年累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_MVAL_OUTFLOW_YTD IS '普通市值流出_年累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.CREDIT_CPTL_INFLOW_YTD IS '两融资金流入_年累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.CREDIT_CPTL_OUTFLOW_YTD IS '两融资金流出_年累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.ODI_ACC_CPTL_NET_INFLOW_YTD IS '普通账户资金净流入_年累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.CREDIT_CPTL_NET_INFLOW_YTD IS '两融资金净流入_年累计';




COMMENT ON COLUMN T_AST_EMPCUS_CPTL_CHG_M_D.LOAD_DT IS '清洗日期';



ALTER TABLE T_AST_EMPCUS_CPTL_CHG_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID);



CREATE TABLE T_AST_EMPCUS_CREDIT_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	WH_ORG_ID_CUST       character varying(100) NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	PERFM_RATI9_CREDIT   numeric(38,8) NULL,
	TOT_LIAB_FINAL       numeric(38,8) NULL,
	NET_AST_FINAL        numeric(38,8) NULL,
	CRED_MARG_FINAL      numeric(38,8) NULL,
	GUAR_SECMV_FINAL     numeric(38,8) NULL,
	FIN_LIAB_FINAL       numeric(38,8) NULL,
	CRDT_STK_LIAB_FINAL  numeric(38,8) NULL,
	INTR_LIAB_FINAL      numeric(38,8) NULL,
	FEE_LIAB_FINAL       numeric(38,8) NULL,
	OTHLIAB_FINAL        numeric(38,8) NULL,
	TOT_AST_FINAL        numeric(38,8) NULL,
	TOT_LIAB_MDA         numeric(38,8) NULL,
	NET_AST_MDA          numeric(38,8) NULL,
	CRED_MARG_MDA        numeric(38,8) NULL,
	GUAR_SECMV_MDA       numeric(38,8) NULL,
	FIN_LIAB_MDA         numeric(38,8) NULL,
	CRDT_STK_LIAB_MDA    numeric(38,8) NULL,
	INTR_LIAB_MDA        numeric(38,8) NULL,
	FEE_LIAB_MDA         numeric(38,8) NULL,
	OTHLIAB_MDA          numeric(38,8) NULL,
	TOT_AST_MDA          numeric(38,8) NULL,
	TOT_LIAB_YDA         numeric(38,8) NULL,
	NET_AST_YDA          numeric(38,8) NULL,
	CRED_MARG_YDA        numeric(38,8) NULL,
	GUAR_SECMV_YDA       numeric(38,8) NULL,
	FIN_LIAB_YDA         numeric(38,8) NULL,
	CRDT_STK_LIAB_YDA    numeric(38,8) NULL,
	INTR_LIAB_YDA        numeric(38,8) NULL,
	FEE_LIAB_YDA         numeric(38,8) NULL,
	OTHLIAB_YDA          numeric(38,8) NULL,
	TOT_AST_YDA          numeric(38,8) NULL,
	LOAD_DT              numeric(8,0) NULL,
	A_SHR_MVAL_FINAL     numeric(38,8) NULL,
	A_SHR_MVAL_MDA       numeric(38,8) NULL,
	A_SHR_MVAL_YDA       numeric(38,8) NULL
);



COMMENT ON TABLE T_AST_EMPCUS_CREDIT_M_D IS '员工客户融资融券月表';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.YEAR IS '年';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.MTH IS '月';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.PERFM_RATI9_CREDIT IS '绩效比例9_融资融券';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.TOT_LIAB_FINAL IS '总负债_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.NET_AST_FINAL IS '净资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.CRED_MARG_FINAL IS '信用保证金_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.GUAR_SECMV_FINAL IS '担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.FIN_LIAB_FINAL IS '融资负债_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.CRDT_STK_LIAB_FINAL IS '融券负债_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.INTR_LIAB_FINAL IS '利息负债_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.FEE_LIAB_FINAL IS '费用负债_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.OTHLIAB_FINAL IS '其他负债_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.TOT_AST_FINAL IS '总资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.TOT_LIAB_MDA IS '总负债_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.NET_AST_MDA IS '净资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.CRED_MARG_MDA IS '信用保证金_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.GUAR_SECMV_MDA IS '担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.FIN_LIAB_MDA IS '融资负债_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.CRDT_STK_LIAB_MDA IS '融券负债_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.INTR_LIAB_MDA IS '利息负债_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.FEE_LIAB_MDA IS '费用负债_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.OTHLIAB_MDA IS '其他负债_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.TOT_AST_MDA IS '总资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.TOT_LIAB_YDA IS '总负债_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.NET_AST_YDA IS '净资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.CRED_MARG_YDA IS '信用保证金_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.GUAR_SECMV_YDA IS '担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.FIN_LIAB_YDA IS '融资负债_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.CRDT_STK_LIAB_YDA IS '融券负债_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.INTR_LIAB_YDA IS '利息负债_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.FEE_LIAB_YDA IS '费用负债_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.OTHLIAB_YDA IS '其他负债_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.TOT_AST_YDA IS '总资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.LOAD_DT IS '清洗日期';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.A_SHR_MVAL_FINAL IS 'A股市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.A_SHR_MVAL_MDA IS 'A股市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_CREDIT_M_D.A_SHR_MVAL_YDA IS 'A股市值_年日均';



ALTER TABLE T_AST_EMPCUS_CREDIT_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID);



CREATE TABLE T_AST_EMPCUS_ODI_M_D
(	YEAR                 varchar(4) NOT NULL,
	MTH                  varchar(2) NOT NULL,
	CUST_ID              varchar(30) NOT NULL,
	YEAR_MTH             varchar(6) NULL,
	YEAR_MTH_CUST_ID     varchar(60) NULL,
	AFA_SEC_EMPID        varchar(60) NOT NULL,
	WH_ORG_ID_EMP        varchar(100) NULL,
	YEAR_MTH_PSN_JNO     varchar(60) NULL,
	SCDY_MVAL_FINAL      numeric(38,8) NULL,
	STKF_MVAL_FINAL      numeric(38,8) NULL,
	A_SHR_MVAL_FINAL     numeric(38,8) NULL,
	NOTS_MVAL_FINAL      numeric(38,8) NULL,
	OFFUND_MVAL_FINAL    numeric(38,8) NULL,
	OPFUND_MVAL_FINAL    numeric(38,8) NULL,
	SB_MVAL_FINAL        numeric(38,8) NULL,
	IMGT_PD_MVAL_FINAL   numeric(38,8) NULL,
	BANK_CHRM_MVAL_FINAL numeric(38,8) NULL,
	SECU_CHRM_MVAL_FINAL numeric(38,8) NULL,
	PSTK_OPTN_MVAL_FINAL numeric(38,8) NULL,
	B_SHR_MVAL_FINAL     numeric(38,8) NULL,
	OUTMARK_MVAL_FINAL   numeric(38,8) NULL,
	CPTL_BAL_FINAL       numeric(38,8) NULL,
	NO_ARVD_CPTL_FINAL   numeric(38,8) NULL,
	PTE_FUND_MVAL_FINAL  numeric(38,8) NULL,
	OVERSEA_TOT_AST_FINAL numeric(38,8) NULL,
	FUTR_TOT_AST_FINAL   numeric(38,8) NULL,
	CPTL_BAL_RMB_FINAL   numeric(38,8) NULL,
	CPTL_BAL_HKD_FINAL   numeric(38,8) NULL,
	CPTL_BAL_USD_FINAL   numeric(38,8) NULL,
	LOW_RISK_TOT_AST_FINAL numeric(38,8) NULL,
	FUND_SPACCT_MVAL_FINAL numeric(38,8) NULL,
	HGT_MVAL_FINAL       numeric(38,8) NULL,
	SGT_MVAL_FINAL       numeric(38,8) NULL,
	NET_AST_FINAL        numeric(38,8) NULL,
	TOT_AST_CONTAIN_NOTS_FINAL numeric(38,8) NULL,
	TOT_AST_N_CONTAIN_NOTS_FINAL numeric(38,8) NULL,
	BOND_MVAL_FINAL      numeric(38,8) NULL,
	REPO_MVAL_FINAL      numeric(38,8) NULL,
	TREA_REPO_MVAL_FINAL numeric(38,8) NULL,
	REPQ_MVAL_FINAL      numeric(38,8) NULL,
	SCDY_MVAL_MDA        numeric(38,8) NULL,
	STKF_MVAL_MDA        numeric(38,8) NULL,
	A_SHR_MVAL_MDA       numeric(38,8) NULL,
	NOTS_MVAL_MDA        numeric(38,8) NULL,
	OFFUND_MVAL_MDA      numeric(38,8) NULL,
	OPFUND_MVAL_MDA      numeric(38,8) NULL,
	SB_MVAL_MDA          numeric(38,8) NULL,
	IMGT_PD_MVAL_MDA     numeric(38,8) NULL,
	BANK_CHRM_MVAL_MDA   numeric(38,8) NULL,
	SECU_CHRM_MVAL_MDA   numeric(38,8) NULL,
	PSTK_OPTN_MVAL_MDA   numeric(38,8) NULL,
	B_SHR_MVAL_MDA       numeric(38,8) NULL,
	OUTMARK_MVAL_MDA     numeric(38,8) NULL,
	CPTL_BAL_MDA         numeric(38,8) NULL,
	NO_ARVD_CPTL_MDA     numeric(38,8) NULL,
	PTE_FUND_MVAL_MDA    numeric(38,8) NULL,
	OVERSEA_TOT_AST_MDA  numeric(38,8) NULL,
	FUTR_TOT_AST_MDA     numeric(38,8) NULL,
	CPTL_BAL_RMB_MDA     numeric(38,8) NULL,
	CPTL_BAL_HKD_MDA     numeric(38,8) NULL,
	CPTL_BAL_USD_MDA     numeric(38,8) NULL,
	LOW_RISK_TOT_AST_MDA numeric(38,8) NULL,
	FUND_SPACCT_MVAL_MDA numeric(38,8) NULL,
	HGT_MVAL_MDA         numeric(38,8) NULL,
	SGT_MVAL_MDA         numeric(38,8) NULL,
	NET_AST_MDA          numeric(38,8) NULL,
	TOT_AST_CONTAIN_NOTS_MDA numeric(38,8) NULL,
	TOT_AST_N_CONTAIN_NOTS_MDA numeric(38,8) NULL,
	BOND_MVAL_MDA        numeric(38,8) NULL,
	REPO_MVAL_MDA        numeric(38,8) NULL,
	TREA_REPO_MVAL_MDA   numeric(38,8) NULL,
	REPQ_MVAL_MDA        numeric(38,8) NULL,
	SCDY_MVAL_YDA        numeric(38,8) NULL,
	STKF_MVAL_YDA        numeric(38,8) NULL,
	A_SHR_MVAL_YDA       numeric(38,8) NULL,
	NOTS_MVAL_YDA        numeric(38,8) NULL,
	OFFUND_MVAL_YDA      numeric(38,8) NULL,
	OPFUND_MVAL_YDA      numeric(38,8) NULL,
	SB_MVAL_YDA          numeric(38,8) NULL,
	IMGT_PD_MVAL_YDA     numeric(38,8) NULL,
	BANK_CHRM_MVAL_YDA   numeric(38,8) NULL,
	SECU_CHRM_MVAL_YDA   numeric(38,8) NULL,
	PSTK_OPTN_MVAL_YDA   numeric(38,8) NULL,
	B_SHR_MVAL_YDA       numeric(38,8) NULL,
	OUTMARK_MVAL_YDA     numeric(38,8) NULL,
	CPTL_BAL_YDA         numeric(38,8) NULL,
	NO_ARVD_CPTL_YDA     numeric(38,8) NULL,
	PTE_FUND_MVAL_YDA    numeric(38,8) NULL,
	OVERSEA_TOT_AST_YDA  numeric(38,8) NULL,
	FUTR_TOT_AST_YDA     numeric(38,8) NULL,
	CPTL_BAL_RMB_YDA     numeric(38,8) NULL,
	CPTL_BAL_HKD_YDA     numeric(38,8) NULL,
	CPTL_BAL_USD_YDA     numeric(38,8) NULL,
	LOW_RISK_TOT_AST_YDA numeric(38,8) NULL,
	FUND_SPACCT_MVAL_YDA numeric(38,8) NULL,
	HGT_MVAL_YDA         numeric(38,8) NULL,
	SGT_MVAL_YDA         numeric(38,8) NULL,
	NET_AST_YDA          numeric(38,8) NULL,
	TOT_AST_CONTAIN_NOTS_YDA numeric(38,8) NULL,
	TOT_AST_N_CONTAIN_NOTS_YDA numeric(38,8) NULL,
	BOND_MVAL_YDA        numeric(38,8) NULL,
	REPO_MVAL_YDA        numeric(38,8) NULL,
	TREA_REPO_MVAL_YDA   numeric(38,8) NULL,
	REPQ_MVAL_YDA        numeric(38,8) NULL,
	PO_FUND_MVAL_FINAL   numeric(38,8) NULL,
	PO_FUND_MVAL_MDA     numeric(38,8) NULL,
	PO_FUND_MVAL_YDA     numeric(38,8) NULL,
	STKT_FUND_MVAL_FINAL numeric(38,8) NULL,
	OTH_PROD_MVAL_FINAL  numeric(38,8) NULL,
	OTH_AST_MVAL_FINAL   numeric(38,8) NULL,
	APPTBUYB_PLG_MVAL_FINAL numeric(38,8) NULL,
	STKT_FUND_MVAL_MDA   numeric(38,8) NULL,
	OTH_PROD_MVAL_MDA    numeric(38,8) NULL,
	OTH_AST_MVAL_MDA     numeric(38,8) NULL,
	APPTBUYB_PLG_MVAL_MDA numeric(38,8) NULL,
	STKT_FUND_MVAL_YDA   numeric(38,8) NULL,
	OTH_PROD_MVAL_YDA    numeric(38,8) NULL,
	OTH_AST_MVAL_YDA     numeric(38,8) NULL,
	APPTBUYB_PLG_MVAL_YDA numeric(38,8) NULL,
	CREDIT_NET_AST_FINAL numeric(38,8) NULL,
	CREDIT_MARG_FINAL    numeric(38,8) NULL,
	CREDIT_BAL_FINAL     numeric(38,8) NULL,
	CREDIT_NET_AST_MDA   numeric(38,8) NULL,
	CREDIT_MARG_MDA      numeric(38,8) NULL,
	CREDIT_BAL_MDA       numeric(38,8) NULL,
	CREDIT_NET_AST_YDA   numeric(38,8) NULL,
	CREDIT_MARG_YDA      numeric(38,8) NULL,
	CREDIT_BAL_YDA       numeric(38,8) NULL,
	PROD_TOT_MVAL_FINAL  numeric(38,8) NULL,
	PROD_TOT_MVAL_MDA    numeric(38,8) NULL,
	PROD_TOT_MVAL_YDA    numeric(38,8) NULL,
	TOT_AST_FINAL        numeric(38,8) NULL,
	TOT_AST_MDA          numeric(38,8) NULL,
	TOT_AST_YDA          numeric(38,8) NULL,
	WH_ORG_ID_CUST       varchar(100) NULL,
	LOAD_DT              numeric(8,0) NULL,
	STKPLG_GUAR_SECMV_FINAL_SCDY_DEDUCT numeric(38,8) NULL,
	STKPLG_GUAR_SECMV_MDA_SCDY_DEDUCT numeric(38,8) NULL,
	STKPLG_GUAR_SECMV_YDA_SCDY_DEDUCT numeric(38,8) NULL,
	STKPLG_LIAB_FINAL    numeric(38,8) NULL,
	STKPLG_LIAB_MDA      numeric(38,8) NULL,
	STKPLG_LIAB_YDA      numeric(38,8) NULL,
	CREDIT_TOT_LIAB_FINAL numeric(38,8) NULL,
	CREDIT_TOT_LIAB_MDA  numeric(38,8) NULL,
	CREDIT_TOT_LIAB_YDA  numeric(38,8) NULL,
	APPTBUYB_BAL_FINAL   numeric(38,8) NULL,
	APPTBUYB_BAL_MDA     numeric(38,8) NULL,
	APPTBUYB_BAL_YDA     numeric(38,8) NULL,
	CREDIT_TOT_AST_FINAL numeric(38,8) NULL,
	CREDIT_TOT_AST_MDA   numeric(38,8) NULL,
	CREDIT_TOT_AST_YDA   numeric(38,8) NULL,
	STKPLG_GUAR_SECMV_FINAL numeric(38,8) NULL,
	STKPLG_GUAR_SECMV_MDA numeric(38,8) NULL,
	STKPLG_GUAR_SECMV_YDA numeric(38,8) NULL
);



COMMENT ON TABLE T_AST_EMPCUS_ODI_M_D IS '员工客户普通资产月表';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.YEAR IS '年';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.MTH IS '月';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SCDY_MVAL_FINAL IS '二级市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKF_MVAL_FINAL IS '股基市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.A_SHR_MVAL_FINAL IS 'A股市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NOTS_MVAL_FINAL IS '限售股市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OFFUND_MVAL_FINAL IS '场内基金市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OPFUND_MVAL_FINAL IS '场外基金市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SB_MVAL_FINAL IS '三板市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.IMGT_PD_MVAL_FINAL IS '资管产品市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.BANK_CHRM_MVAL_FINAL IS '银行理财市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SECU_CHRM_MVAL_FINAL IS '证券理财市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PSTK_OPTN_MVAL_FINAL IS '个股期权市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.B_SHR_MVAL_FINAL IS 'B股市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OUTMARK_MVAL_FINAL IS '体外市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_FINAL IS '资金余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NO_ARVD_CPTL_FINAL IS '未到账资金_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PTE_FUND_MVAL_FINAL IS '私募基金市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OVERSEA_TOT_AST_FINAL IS '海外总资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.FUTR_TOT_AST_FINAL IS '期货总资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_RMB_FINAL IS '资金余额人民币_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_HKD_FINAL IS '资金余额港币_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_USD_FINAL IS '资金余额美元_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.LOW_RISK_TOT_AST_FINAL IS '低风险总资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.FUND_SPACCT_MVAL_FINAL IS '基金专户市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.HGT_MVAL_FINAL IS '沪港通市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SGT_MVAL_FINAL IS '深港通市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NET_AST_FINAL IS '净资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_CONTAIN_NOTS_FINAL IS '总资产_含限售股_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_N_CONTAIN_NOTS_FINAL IS '总资产_不含限售股_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.BOND_MVAL_FINAL IS '债券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.REPO_MVAL_FINAL IS '回购市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TREA_REPO_MVAL_FINAL IS '国债回购市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.REPQ_MVAL_FINAL IS '报价回购市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SCDY_MVAL_MDA IS '二级市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKF_MVAL_MDA IS '股基市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.A_SHR_MVAL_MDA IS 'A股市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NOTS_MVAL_MDA IS '限售股市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OFFUND_MVAL_MDA IS '场内基金市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OPFUND_MVAL_MDA IS '场外基金市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SB_MVAL_MDA IS '三板市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.IMGT_PD_MVAL_MDA IS '资管产品市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.BANK_CHRM_MVAL_MDA IS '银行理财市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SECU_CHRM_MVAL_MDA IS '证券理财市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PSTK_OPTN_MVAL_MDA IS '个股期权市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.B_SHR_MVAL_MDA IS 'B股市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OUTMARK_MVAL_MDA IS '体外市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_MDA IS '资金余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NO_ARVD_CPTL_MDA IS '未到账资金_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PTE_FUND_MVAL_MDA IS '私募基金市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OVERSEA_TOT_AST_MDA IS '海外总资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.FUTR_TOT_AST_MDA IS '期货总资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_RMB_MDA IS '资金余额人民币_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_HKD_MDA IS '资金余额港币_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_USD_MDA IS '资金余额美元_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.LOW_RISK_TOT_AST_MDA IS '低风险总资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.FUND_SPACCT_MVAL_MDA IS '基金专户市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.HGT_MVAL_MDA IS '沪港通市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SGT_MVAL_MDA IS '深港通市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NET_AST_MDA IS '净资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_CONTAIN_NOTS_MDA IS '总资产_含限售股_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_N_CONTAIN_NOTS_MDA IS '总资产_不含限售股_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.BOND_MVAL_MDA IS '债券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.REPO_MVAL_MDA IS '回购市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TREA_REPO_MVAL_MDA IS '国债回购市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.REPQ_MVAL_MDA IS '报价回购市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SCDY_MVAL_YDA IS '二级市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKF_MVAL_YDA IS '股基市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.A_SHR_MVAL_YDA IS 'A股市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NOTS_MVAL_YDA IS '限售股市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OFFUND_MVAL_YDA IS '场内基金市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OPFUND_MVAL_YDA IS '场外基金市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SB_MVAL_YDA IS '三板市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.IMGT_PD_MVAL_YDA IS '资管产品市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.BANK_CHRM_MVAL_YDA IS '银行理财市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SECU_CHRM_MVAL_YDA IS '证券理财市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PSTK_OPTN_MVAL_YDA IS '个股期权市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.B_SHR_MVAL_YDA IS 'B股市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OUTMARK_MVAL_YDA IS '体外市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_YDA IS '资金余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NO_ARVD_CPTL_YDA IS '未到账资金_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PTE_FUND_MVAL_YDA IS '私募基金市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OVERSEA_TOT_AST_YDA IS '海外总资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.FUTR_TOT_AST_YDA IS '期货总资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_RMB_YDA IS '资金余额人民币_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_HKD_YDA IS '资金余额港币_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CPTL_BAL_USD_YDA IS '资金余额美元_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.LOW_RISK_TOT_AST_YDA IS '低风险总资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.FUND_SPACCT_MVAL_YDA IS '基金专户市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.HGT_MVAL_YDA IS '沪港通市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.SGT_MVAL_YDA IS '深港通市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.NET_AST_YDA IS '净资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_CONTAIN_NOTS_YDA IS '总资产_含限售股_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_N_CONTAIN_NOTS_YDA IS '总资产_不含限售股_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.BOND_MVAL_YDA IS '债券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.REPO_MVAL_YDA IS '回购市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TREA_REPO_MVAL_YDA IS '国债回购市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.REPQ_MVAL_YDA IS '报价回购市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PO_FUND_MVAL_FINAL IS '公募基金市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PO_FUND_MVAL_MDA IS '公募基金市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PO_FUND_MVAL_YDA IS '公募基金市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKT_FUND_MVAL_FINAL IS '股票型基金市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OTH_PROD_MVAL_FINAL IS '其他产品市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OTH_AST_MVAL_FINAL IS '其他资产市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.APPTBUYB_PLG_MVAL_FINAL IS '约定购回质押市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKT_FUND_MVAL_MDA IS '股票型基金市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OTH_PROD_MVAL_MDA IS '其他产品市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OTH_AST_MVAL_MDA IS '其他资产市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.APPTBUYB_PLG_MVAL_MDA IS '约定购回质押市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKT_FUND_MVAL_YDA IS '股票型基金市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OTH_PROD_MVAL_YDA IS '其他产品市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.OTH_AST_MVAL_YDA IS '其他资产市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.APPTBUYB_PLG_MVAL_YDA IS '约定购回质押市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_NET_AST_FINAL IS '融资融券净资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_MARG_FINAL IS '融资融券保证金_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_BAL_FINAL IS '融资融券余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_NET_AST_MDA IS '融资融券净资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_MARG_MDA IS '融资融券保证金_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_BAL_MDA IS '融资融券余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_NET_AST_YDA IS '融资融券净资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_MARG_YDA IS '融资融券保证金_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_BAL_YDA IS '融资融券余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PROD_TOT_MVAL_FINAL IS '产品总市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PROD_TOT_MVAL_MDA IS '产品总市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.PROD_TOT_MVAL_YDA IS '产品总市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_FINAL IS '总资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_MDA IS '总资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.TOT_AST_YDA IS '总资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.WH_ORG_ID_CUST IS '仓库机构编码客户';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.LOAD_DT IS '清洗日期';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_GUAR_SECMV_FINAL_SCDY_DEDUCT IS '股票质押担保证券市值_期末_二级扣减';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_GUAR_SECMV_MDA_SCDY_DEDUCT IS '股票质押担保证券市值_月日均_二级扣减';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_GUAR_SECMV_YDA_SCDY_DEDUCT IS '股票质押担保证券市值_年日均_二级扣减';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_LIAB_FINAL IS '股票质押负债_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_LIAB_MDA IS '股票质押负债_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_LIAB_YDA IS '股票质押负债_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_TOT_LIAB_FINAL IS '融资融券总负债_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_TOT_LIAB_MDA IS '融资融券总负债_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_TOT_LIAB_YDA IS '融资融券总负债_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.APPTBUYB_BAL_FINAL IS '约定购回余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.APPTBUYB_BAL_MDA IS '约定购回余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.APPTBUYB_BAL_YDA IS '约定购回余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_TOT_AST_FINAL IS '融资融券总资产_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_TOT_AST_MDA IS '融资融券总资产_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.CREDIT_TOT_AST_YDA IS '融资融券总资产_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_GUAR_SECMV_FINAL IS '股票质押担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_GUAR_SECMV_MDA IS '股票质押担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_ODI_M_D.STKPLG_GUAR_SECMV_YDA IS '股票质押担保证券市值_年日均';



ALTER TABLE T_AST_EMPCUS_ODI_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID);



CREATE INDEX IDV_T_AST_EMPCUS_ODI_M_WH_ORG_ID_CUST ON T_AST_EMPCUS_ODI_M_D
(
	WH_ORG_ID_CUST        ASC
);



CREATE INDEX IDV_T_AST_EMPCUS_ODI_M_WH_ORG_ID_EMP ON T_AST_EMPCUS_ODI_M_D
(
	WH_ORG_ID_EMP         ASC
);



CREATE INDEX IDV_T_AST_EMPCUS_ODI_M_YEAR_MTH ON T_AST_EMPCUS_ODI_M_D
(
	YEAR_MTH              ASC
);



CREATE INDEX IDV_T_AST_EMPCUS_ODI_M_YEAR_MTH_CUST_ID ON T_AST_EMPCUS_ODI_M_D
(
	YEAR_MTH_CUST_ID      ASC
);



CREATE INDEX IDV_T_AST_EMPCUS_ODI_M_YEAR_MTH_PSN_JNO ON T_AST_EMPCUS_ODI_M_D
(
	YEAR_MTH_PSN_JNO      ASC
);



CREATE TABLE T_AST_EMPCUS_STKPLG_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	CTR_NO               character varying(100) NOT NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	WH_ORG_ID_CUST       character varying(100) NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	GUAR_SECMV_FINAL     numeric(38,8) NULL,
	STKPLG_FIN_BAL_FINAL numeric(38,8) NULL,
	SH_GUAR_SECMV_FINAL  numeric(38,8) NULL,
	SZ_GUAR_SECMV_FINAL  numeric(38,8) NULL,
	SH_NOTS_GUAR_SECMV_FINAL numeric(38,8) NULL,
	SZ_NOTS_GUAR_SECMV_FINAL numeric(38,8) NULL,
	PROP_FINOS_BAL_FINAL numeric(38,8) NULL,
	ASSM_FINOS_BAL_FINAL numeric(38,8) NULL,
	SM_LOAN_FINO_BAL_FINAL numeric(38,8) NULL,
	GUAR_SECMV_MDA       numeric(38,8) NULL,
	STKPLG_FIN_BAL_MDA   numeric(38,8) NULL,
	SH_GUAR_SECMV_MDA    numeric(38,8) NULL,
	SZ_GUAR_SECMV_MDA    numeric(38,8) NULL,
	SH_NOTS_GUAR_SECMV_MDA numeric(38,8) NULL,
	SZ_NOTS_GUAR_SECMV_MDA numeric(38,8) NULL,
	PROP_FINOS_BAL_MDA   numeric(38,8) NULL,
	ASSM_FINOS_BAL_MDA   numeric(38,8) NULL,
	SM_LOAN_FINO_BAL_MDA numeric(38,8) NULL,
	GUAR_SECMV_YDA       numeric(38,8) NULL,
	STKPLG_FIN_BAL_YDA   numeric(38,8) NULL,
	SH_GUAR_SECMV_YDA    numeric(38,8) NULL,
	SZ_GUAR_SECMV_YDA    numeric(38,8) NULL,
	SH_NOTS_GUAR_SECMV_YDA numeric(38,8) NULL,
	SZ_NOTS_GUAR_SECMV_YDA numeric(38,8) NULL,
	PROP_FINOS_BAL_YDA   numeric(38,8) NULL,
	ASSM_FINOS_BAL_YDA   numeric(38,8) NULL,
	SM_LOAN_FINO_BAL_YDA numeric(38,8) NULL,
	LOAD_DT              numeric(8,0) NULL
);



COMMENT ON TABLE T_AST_EMPCUS_STKPLG_M_D IS '员工客户股票质押月表';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.YEAR IS '年';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.MTH IS '月';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.CTR_NO IS '合同编号';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.GUAR_SECMV_FINAL IS '担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.STKPLG_FIN_BAL_FINAL IS '股票质押融资余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SH_GUAR_SECMV_FINAL IS '上海担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SZ_GUAR_SECMV_FINAL IS '深圳担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SH_NOTS_GUAR_SECMV_FINAL IS '上海限售股担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SZ_NOTS_GUAR_SECMV_FINAL IS '深圳限售股担保证券市值_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.PROP_FINOS_BAL_FINAL IS '自营融出方余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.ASSM_FINOS_BAL_FINAL IS '资管融出方余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SM_LOAN_FINO_BAL_FINAL IS '小额贷融出余额_期末';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.GUAR_SECMV_MDA IS '担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.STKPLG_FIN_BAL_MDA IS '股票质押融资余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SH_GUAR_SECMV_MDA IS '上海担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SZ_GUAR_SECMV_MDA IS '深圳担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SH_NOTS_GUAR_SECMV_MDA IS '上海限售股担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SZ_NOTS_GUAR_SECMV_MDA IS '深圳限售股担保证券市值_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.PROP_FINOS_BAL_MDA IS '自营融出方余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.ASSM_FINOS_BAL_MDA IS '资管融出方余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SM_LOAN_FINO_BAL_MDA IS '小额贷融出余额_月日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.GUAR_SECMV_YDA IS '担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.STKPLG_FIN_BAL_YDA IS '股票质押融资余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SH_GUAR_SECMV_YDA IS '上海担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SZ_GUAR_SECMV_YDA IS '深圳担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SH_NOTS_GUAR_SECMV_YDA IS '上海限售股担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SZ_NOTS_GUAR_SECMV_YDA IS '深圳限售股担保证券市值_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.PROP_FINOS_BAL_YDA IS '自营融出方余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.ASSM_FINOS_BAL_YDA IS '资管融出方余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.SM_LOAN_FINO_BAL_YDA IS '小额贷融出余额_年日均';




COMMENT ON COLUMN T_AST_EMPCUS_STKPLG_M_D.LOAD_DT IS '清洗日期';



ALTER TABLE T_AST_EMPCUS_STKPLG_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID,CTR_NO);



CREATE TABLE T_EVT_EMPCUS_CRED_INCM_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	MAIN_CPTL_ACCT       character varying(30) NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	WH_ORG_ID_CUST       character varying(100) NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	LOAD_DT              numeric(8,0) NULL,
	GROSS_CMS_MTD        numeric(38,8) NULL,
	NET_CMS_MTD          numeric(38,8) NULL,
	TRAN_FEE_MTD         numeric(38,8) NULL,
	STP_TAX_MTD          numeric(38,8) NULL,
	ORDR_FEE_MTD         numeric(38,8) NULL,
	HANDLE_FEE_MTD       numeric(38,8) NULL,
	SEC_RGLT_FEE_MTD     numeric(38,8) NULL,
	OTH_FEE_MTD          numeric(38,8) NULL,
	CREDIT_ODI_CMS_MTD   numeric(38,8) NULL,
	CREDIT_ODI_NET_CMS_MTD numeric(38,8) NULL,
	CREDIT_ODI_TRAN_FEE_MTD numeric(38,8) NULL,
	CREDIT_CRED_CMS_MTD  numeric(38,8) NULL,
	CREDIT_CRED_NET_CMS_MTD numeric(38,8) NULL,
	CREDIT_CRED_TRAN_FEE_MTD numeric(38,8) NULL,
	STKPLG_CMS_MTD       numeric(38,8) NULL,
	STKPLG_NET_CMS_MTD   numeric(38,8) NULL,
	STKPLG_PAIDINT_MTD   numeric(38,8) NULL,
	STKPLG_RECE_INT_MTD  numeric(38,8) NULL,
	APPTBUYB_CMS_MTD     numeric(38,8) NULL,
	APPTBUYB_NET_CMS_MTD numeric(38,8) NULL,
	APPTBUYB_PAIDINT_MTD numeric(38,8) NULL,
	FIN_PAIDINT_MTD      numeric(38,8) NULL,
	FIN_IE_MTD           numeric(38,8) NULL,
	CRDT_STK_IE_MTD      numeric(38,8) NULL,
	OTH_IE_MTD           numeric(38,8) NULL,
	FIN_RECE_INT_MTD     numeric(38,8) NULL,
	FEE_RECE_INT_MTD     numeric(38,8) NULL,
	OTH_RECE_INT_MTD     numeric(38,8) NULL,
	CREDIT_CPTL_COST_MTD numeric(38,8) NULL,
	GROSS_CMS_YTD        numeric(38,8) NULL,
	NET_CMS_YTD          numeric(38,8) NULL,
	TRAN_FEE_YTD         numeric(38,8) NULL,
	STP_TAX_YTD          numeric(38,8) NULL,
	ORDR_FEE_YTD         numeric(38,8) NULL,
	HANDLE_FEE_YTD       numeric(38,8) NULL,
	SEC_RGLT_FEE_YTD     numeric(38,8) NULL,
	OTH_FEE_YTD          numeric(38,8) NULL,
	CREDIT_ODI_CMS_YTD   numeric(38,8) NULL,
	CREDIT_ODI_NET_CMS_YTD numeric(38,8) NULL,
	CREDIT_ODI_TRAN_FEE_YTD numeric(38,8) NULL,
	CREDIT_CRED_CMS_YTD  numeric(38,8) NULL,
	CREDIT_CRED_NET_CMS_YTD numeric(38,8) NULL,
	CREDIT_CRED_TRAN_FEE_YTD numeric(38,8) NULL,
	STKPLG_CMS_YTD       numeric(38,8) NULL,
	STKPLG_NET_CMS_YTD   numeric(38,8) NULL,
	STKPLG_PAIDINT_YTD   numeric(38,8) NULL,
	STKPLG_RECE_INT_YTD  numeric(38,8) NULL,
	APPTBUYB_CMS_YTD     numeric(38,8) NULL,
	APPTBUYB_NET_CMS_YTD numeric(38,8) NULL,
	APPTBUYB_PAIDINT_YTD numeric(38,8) NULL,
	FIN_PAIDINT_YTD      numeric(38,8) NULL,
	FIN_IE_YTD           numeric(38,8) NULL,
	CRDT_STK_IE_YTD      numeric(38,8) NULL,
	OTH_IE_YTD           numeric(38,8) NULL,
	FIN_RECE_INT_YTD     numeric(38,8) NULL,
	FEE_RECE_INT_YTD     numeric(38,8) NULL,
	OTH_RECE_INT_YTD     numeric(38,8) NULL,
	CREDIT_CPTL_COST_YTD numeric(38,8) NULL,
	CREDIT_MARG_SPR_INCM_MTD numeric(38,8) NULL,
	CREDIT_MARG_SPR_INCM_YTD numeric(38,8) NULL
);



COMMENT ON TABLE T_EVT_EMPCUS_CRED_INCM_M_D IS '员工客户信用收入月表';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.YEAR IS '年';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.MTH IS '月';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.MAIN_CPTL_ACCT IS '主资金账号';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.LOAD_DT IS '清洗日期';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.GROSS_CMS_MTD IS '毛佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.NET_CMS_MTD IS '净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.TRAN_FEE_MTD IS '过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STP_TAX_MTD IS '印花税_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.ORDR_FEE_MTD IS '委托费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.HANDLE_FEE_MTD IS '经手费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.SEC_RGLT_FEE_MTD IS '证管费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.OTH_FEE_MTD IS '其他费用_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_ODI_CMS_MTD IS '融资融券普通佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_ODI_NET_CMS_MTD IS '融资融券普通净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_ODI_TRAN_FEE_MTD IS '融资融券普通过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_CRED_CMS_MTD IS '融资融券信用佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_CRED_NET_CMS_MTD IS '融资融券信用净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_CRED_TRAN_FEE_MTD IS '融资融券信用过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STKPLG_CMS_MTD IS '股票质押佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STKPLG_NET_CMS_MTD IS '股票质押净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STKPLG_PAIDINT_MTD IS '股票质押实收利息_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STKPLG_RECE_INT_MTD IS '股票质押应收利息_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.APPTBUYB_CMS_MTD IS '约定购回佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.APPTBUYB_NET_CMS_MTD IS '约定购回净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.APPTBUYB_PAIDINT_MTD IS '约定购回实收利息_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.FIN_PAIDINT_MTD IS '融资实收利息_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.FIN_IE_MTD IS '融资利息支出_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CRDT_STK_IE_MTD IS '融券利息支出_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.OTH_IE_MTD IS '其他利息支出_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.FIN_RECE_INT_MTD IS '融资应收利息_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.FEE_RECE_INT_MTD IS '费用应收利息_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.OTH_RECE_INT_MTD IS '其他应收利息_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_CPTL_COST_MTD IS '融资融券资金成本_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.GROSS_CMS_YTD IS '毛佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.NET_CMS_YTD IS '净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.TRAN_FEE_YTD IS '过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STP_TAX_YTD IS '印花税_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.ORDR_FEE_YTD IS '委托费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.HANDLE_FEE_YTD IS '经手费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.SEC_RGLT_FEE_YTD IS '证管费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.OTH_FEE_YTD IS '其他费用_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_ODI_CMS_YTD IS '融资融券普通佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_ODI_NET_CMS_YTD IS '融资融券普通净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_ODI_TRAN_FEE_YTD IS '融资融券普通过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_CRED_CMS_YTD IS '融资融券信用佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_CRED_NET_CMS_YTD IS '融资融券信用净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_CRED_TRAN_FEE_YTD IS '融资融券信用过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STKPLG_CMS_YTD IS '股票质押佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STKPLG_NET_CMS_YTD IS '股票质押净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STKPLG_PAIDINT_YTD IS '股票质押实收利息_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.STKPLG_RECE_INT_YTD IS '股票质押应收利息_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.APPTBUYB_CMS_YTD IS '约定购回佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.APPTBUYB_NET_CMS_YTD IS '约定购回净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.APPTBUYB_PAIDINT_YTD IS '约定购回实收利息_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.FIN_PAIDINT_YTD IS '融资实收利息_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.FIN_IE_YTD IS '融资利息支出_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CRDT_STK_IE_YTD IS '融券利息支出_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.OTH_IE_YTD IS '其他利息支出_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.FIN_RECE_INT_YTD IS '融资应收利息_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.FEE_RECE_INT_YTD IS '费用应收利息_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.OTH_RECE_INT_YTD IS '其他应收利息_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_CPTL_COST_YTD IS '融资融券资金成本_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_MARG_SPR_INCM_MTD IS '融资融券保证金利差收入_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_CRED_INCM_M_D.CREDIT_MARG_SPR_INCM_YTD IS '融资融券保证金利差收入_年累计';



ALTER TABLE T_EVT_EMPCUS_CRED_INCM_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID);



CREATE TABLE T_EVT_EMPCUS_NUM_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	IF_MTH_NA            integer NULL,
	IF_YEAR_NA           integer NULL,
	CUST_NUM             numeric(30) NULL,
	CUST_NUM_CRED        numeric(30) NULL,
	WH_ORG_ID_CUST       varchar(100) NULL,
	LOAD_DT              numeric(8,0) NULL
);




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.YEAR IS '年';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.MTH IS '月';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.CUST_NUM IS '客户数';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.CUST_NUM_CRED IS '客户数_信用';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_EVT_EMPCUS_NUM_M_D.LOAD_DT IS '清洗日期';



ALTER TABLE T_EVT_EMPCUS_NUM_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID);



CREATE INDEX IDX_T_EVT_EMPCUS_NUM_WH_ORG_ID_CUST ON T_EVT_EMPCUS_NUM_M_D
(
	WH_ORG_ID_CUST        ASC
);



CREATE INDEX IDX_T_EVT_EMPCUS_NUM_WH_org_id_emp ON T_EVT_EMPCUS_NUM_M_D
(
	WH_ORG_ID_EMP         ASC
);



CREATE INDEX IDX_T_EVT_EMPCUS_NUM_YEAR_MTH ON T_EVT_EMPCUS_NUM_M_D
(
	YEAR_MTH              ASC
);



CREATE INDEX IDX_T_EVT_EMPCUS_NUM_YEAR_MTH_CUST_ID ON T_EVT_EMPCUS_NUM_M_D
(
	YEAR_MTH_CUST_ID      ASC
);



CREATE INDEX IDX_T_EVT_EMPCUS_NUM_YEAR_MTH_PSN_JNO ON T_EVT_EMPCUS_NUM_M_D
(
	YEAR_MTH_PSN_JNO      ASC
);



CREATE TABLE T_EVT_EMPCUS_ODI_INCM_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	MAIN_CPTL_ACCT       character varying(30) NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	WH_ORG_ID_CUST       character varying(100) NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	LOAD_DT              numeric(8,0) NULL,
	GROSS_CMS_MTD        numeric(38,8) NULL,
	TRAN_FEE_MTD         numeric(38,8) NULL,
	SCDY_TRAN_FEE_MTD    numeric(38,8) NULL,
	STP_TAX_MTD          numeric(38,8) NULL,
	HANDLE_FEE_MTD       numeric(38,8) NULL,
	SEC_RGLT_FEE_MTD     numeric(38,8) NULL,
	OTH_FEE_MTD          numeric(38,8) NULL,
	STKF_CMS_MTD         numeric(38,8) NULL,
	STKF_TRAN_FEE_MTD    numeric(38,8) NULL,
	STKF_NET_CMS_MTD     numeric(38,8) NULL,
	BOND_CMS_MTD         numeric(38,8) NULL,
	BOND_NET_CMS_MTD     numeric(38,8) NULL,
	REPQ_CMS_MTD         numeric(38,8) NULL,
	REPQ_NET_CMS_MTD     numeric(38,8) NULL,
	HGT_CMS_MTD          numeric(38,8) NULL,
	HGT_NET_CMS_MTD      numeric(38,8) NULL,
	HGT_TRAN_FEE_MTD     numeric(38,8) NULL,
	SGT_CMS_MTD          numeric(38,8) NULL,
	SGT_NET_CMS_MTD      numeric(38,8) NULL,
	SGT_TRAN_FEE_MTD     numeric(38,8) NULL,
	BGDL_CMS_MTD         numeric(38,8) NULL,
	NET_CMS_MTD          numeric(38,8) NULL,
	BGDL_NET_CMS_MTD     numeric(38,8) NULL,
	BGDL_TRAN_FEE_MTD    numeric(38,8) NULL,
	PSTK_OPTN_CMS_MTD    numeric(38,8) NULL,
	PSTK_OPTN_NET_CMS_MTD numeric(38,8) NULL,
	SCDY_CMS_MTD         numeric(38,8) NULL,
	SCDY_NET_CMS_MTD     numeric(38,8) NULL,
	GROSS_CMS_YTD        numeric(38,8) NULL,
	TRAN_FEE_YTD         numeric(38,8) NULL,
	SCDY_TRAN_FEE_YTD    numeric(38,8) NULL,
	STP_TAX_YTD          numeric(38,8) NULL,
	HANDLE_FEE_YTD       numeric(38,8) NULL,
	SEC_RGLT_FEE_YTD     numeric(38,8) NULL,
	OTH_FEE_YTD          numeric(38,8) NULL,
	STKF_CMS_YTD         numeric(38,8) NULL,
	STKF_TRAN_FEE_YTD    numeric(38,8) NULL,
	STKF_NET_CMS_YTD     numeric(38,8) NULL,
	BOND_CMS_YTD         numeric(38,8) NULL,
	BOND_NET_CMS_YTD     numeric(38,8) NULL,
	REPQ_CMS_YTD         numeric(38,8) NULL,
	REPQ_NET_CMS_YTD     numeric(38,8) NULL,
	HGT_CMS_YTD          numeric(38,8) NULL,
	HGT_NET_CMS_YTD      numeric(38,8) NULL,
	HGT_TRAN_FEE_YTD     numeric(38,8) NULL,
	SGT_CMS_YTD          numeric(38,8) NULL,
	SGT_NET_CMS_YTD      numeric(38,8) NULL,
	SGT_TRAN_FEE_YTD     numeric(38,8) NULL,
	BGDL_CMS_YTD         numeric(38,8) NULL,
	NET_CMS_YTD          numeric(38,8) NULL,
	BGDL_NET_CMS_YTD     numeric(38,8) NULL,
	BGDL_TRAN_FEE_YTD    numeric(38,8) NULL,
	PSTK_OPTN_CMS_YTD    numeric(38,8) NULL,
	PSTK_OPTN_NET_CMS_YTD numeric(38,8) NULL,
	SCDY_CMS_YTD         numeric(38,8) NULL,
	SCDY_NET_CMS_YTD     numeric(38,8) NULL,
	PB_TRD_CMS_MTD       numeric(38,8) NULL,
	MARG_SPR_INCM_MTD    numeric(38,8) NULL,
	PB_TRD_CMS_YTD       numeric(38,8) NULL,
	MARG_SPR_INCM_YTD    numeric(38,8) NULL
);



COMMENT ON TABLE T_EVT_EMPCUS_ODI_INCM_M_D IS '员工客户普通收入月表';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.YEAR IS '年';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.MTH IS '月';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.MAIN_CPTL_ACCT IS '主资金账号';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.LOAD_DT IS '清洗日期';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.GROSS_CMS_MTD IS '毛佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.TRAN_FEE_MTD IS '过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SCDY_TRAN_FEE_MTD IS '二级过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.STP_TAX_MTD IS '印花税_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.HANDLE_FEE_MTD IS '经手费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SEC_RGLT_FEE_MTD IS '证管费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.OTH_FEE_MTD IS '其他费用_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.STKF_CMS_MTD IS '股基佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.STKF_TRAN_FEE_MTD IS '股基过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.STKF_NET_CMS_MTD IS '股基净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BOND_CMS_MTD IS '债券佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BOND_NET_CMS_MTD IS '债券净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.REPQ_CMS_MTD IS '报价回购佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.REPQ_NET_CMS_MTD IS '报价回购净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.HGT_CMS_MTD IS '沪港通佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.HGT_NET_CMS_MTD IS '沪港通净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.HGT_TRAN_FEE_MTD IS '沪港通过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SGT_CMS_MTD IS '深港通佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SGT_NET_CMS_MTD IS '深港通净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SGT_TRAN_FEE_MTD IS '深港通过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BGDL_CMS_MTD IS '大宗交易佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.NET_CMS_MTD IS '净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BGDL_NET_CMS_MTD IS '大宗交易净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BGDL_TRAN_FEE_MTD IS '大宗交易过户费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.PSTK_OPTN_CMS_MTD IS '个股期权佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.PSTK_OPTN_NET_CMS_MTD IS '个股期权净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SCDY_CMS_MTD IS '二级佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SCDY_NET_CMS_MTD IS '二级净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.GROSS_CMS_YTD IS '毛佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.TRAN_FEE_YTD IS '过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SCDY_TRAN_FEE_YTD IS '二级过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.STP_TAX_YTD IS '印花税_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.HANDLE_FEE_YTD IS '经手费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SEC_RGLT_FEE_YTD IS '证管费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.OTH_FEE_YTD IS '其他费用_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.STKF_CMS_YTD IS '股基佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.STKF_TRAN_FEE_YTD IS '股基过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.STKF_NET_CMS_YTD IS '股基净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BOND_CMS_YTD IS '债券佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BOND_NET_CMS_YTD IS '债券净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.REPQ_CMS_YTD IS '报价回购佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.REPQ_NET_CMS_YTD IS '报价回购净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.HGT_CMS_YTD IS '沪港通佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.HGT_NET_CMS_YTD IS '沪港通净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.HGT_TRAN_FEE_YTD IS '沪港通过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SGT_CMS_YTD IS '深港通佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SGT_NET_CMS_YTD IS '深港通净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SGT_TRAN_FEE_YTD IS '深港通过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BGDL_CMS_YTD IS '大宗交易佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.NET_CMS_YTD IS '净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BGDL_NET_CMS_YTD IS '大宗交易净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.BGDL_TRAN_FEE_YTD IS '大宗交易过户费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.PSTK_OPTN_CMS_YTD IS '个股期权佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.PSTK_OPTN_NET_CMS_YTD IS '个股期权净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SCDY_CMS_YTD IS '二级佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.SCDY_NET_CMS_YTD IS '二级净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.PB_TRD_CMS_MTD IS 'PB交易佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.MARG_SPR_INCM_MTD IS '保证金利差收入_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.PB_TRD_CMS_YTD IS 'PB交易佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_INCM_M_D.MARG_SPR_INCM_YTD IS '保证金利差收入_年累计';



ALTER TABLE T_EVT_EMPCUS_ODI_INCM_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID);



CREATE TABLE T_EVT_EMPCUS_ODI_TRD_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	MAIN_CPTL_ACCT       character varying(30) NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	WH_ORG_ID_CUST       character varying(100) NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	EQT_CLAS_KEPP_PERCN  numeric(38,8) NULL,
	SCDY_TRD_FREQ_MTD    numeric(38,8) NULL,
	RCT_TRD_DT_GT        numeric(38,8) NULL,
	SCDY_TRD_QTY_YTD     numeric(38,8) NULL,
	TRD_FREQ_YTD         numeric(38,8) NULL,
	STKF_TRD_QTY_MDA     numeric(38,8) NULL,
	STKF_TRD_QTY_YDA     numeric(38,8) NULL,
	S_REPUR_TRD_QTY_MDA  numeric(38,8) NULL,
	R_REPUR_TRD_QTY_MDA  numeric(38,8) NULL,
	S_REPUR_TRD_QTY_YDA  numeric(38,8) NULL,
	R_REPUR_TRD_QTY_YDA  numeric(38,8) NULL,
	HGT_TRD_QTY_MTD      numeric(38,8) NULL,
	SGT_TRD_QTY_MTD      numeric(38,8) NULL,
	SGT_TRD_QTY_YTD      numeric(38,8) NULL,
	HGT_TRD_QTY_YTD      numeric(38,8) NULL,
	Y_RCT_STK_TRD_QTY    numeric(38,8) NULL,
	SCDY_TRD_FREQ_YTD    numeric(38,8) NULL,
	TRD_FREQ_MTD         numeric(38,8) NULL,
	APPTBUYB_TRD_QTY_MTD numeric(38,8) NULL,
	APPTBUYB_TRD_QTY_YTD numeric(38,8) NULL,
	RCT_TRD_DT_M         numeric(38,8) NULL,
	STKPLG_TRD_QTY_MTD   numeric(38,8) NULL,
	STKPLG_TRD_QTY_YTD   numeric(38,8) NULL,
	PSTK_OPTN_TRD_QTY_MTD numeric(38,8) NULL,
	PSTK_OPTN_TRD_QTY_YTD numeric(38,8) NULL,
	REPQ_TRD_QTY_MTD     numeric(38,8) NULL,
	REPQ_TRD_QTY_YTD     numeric(38,8) NULL,
	BGDL_QTY_MTD         numeric(38,8) NULL,
	BGDL_QTY_YTD         numeric(38,8) NULL,
	LOAD_DT              numeric(8,0) NULL,
	NATRE_DAYS_MTH       integer NULL,
	NATRE_DAYS_YEAR      integer NULL,
	CREDIT_ODI_TRD_QTY_MDA numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY_MDA numeric(38,8) NULL,
	STKF_TRD_QTY_MTD     numeric(38,8) NULL,
	SCDY_TRD_QTY_MTD     numeric(38,8) NULL,
	SCDY_TRD_QTY_MDA     numeric(38,8) NULL,
	S_REPUR_TRD_QTY_MTD  numeric(38,8) NULL,
	R_REPUR_TRD_QTY_MTD  numeric(38,8) NULL,
	CREDIT_TRD_QTY_MTD   numeric(38,8) NULL,
	OFFUND_TRD_QTY_MTD   numeric(38,8) NULL,
	OPFUND_TRD_QTY_MTD   numeric(38,8) NULL,
	BANK_CHRM_TRD_QTY_MTD numeric(38,8) NULL,
	SECU_CHRM_TRD_QTY_MTD numeric(38,8) NULL,
	CREDIT_ODI_TRD_QTY_MTD numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY_MTD numeric(38,8) NULL,
	FIN_AMT_MTD          numeric(38,8) NULL,
	CRDT_STK_AMT_MTD     numeric(38,8) NULL,
	STKPLG_BUYB_AMT_MTD  numeric(38,8) NULL,
	GROSS_CMS_MTD        numeric(38,8) NULL,
	NET_CMS_MTD          numeric(38,8) NULL,
	STKPLG_BUYB_CNT_MTD  numeric(38,8) NULL,
	CCB_AMT_MTD          numeric(38,8) NULL,
	CCB_CNT_MTD          numeric(38,8) NULL,
	FIN_SELL_AMT_MTD     numeric(38,8) NULL,
	FIN_SELL_CNT_MTD     numeric(38,8) NULL,
	CRDT_STK_BUYIN_AMT_MTD numeric(38,8) NULL,
	CRDT_STK_BUYIN_CNT_MTD numeric(38,8) NULL,
	CSS_AMT_MTD          numeric(38,8) NULL,
	CSS_CNT_MTD          numeric(38,8) NULL,
	FIN_RTN_AMT_MTD      numeric(38,8) NULL,
	APPTBUYB_REP_AMT_MTD numeric(38,8) NULL,
	APPTBUYB_BUYB_AMT_MTD numeric(38,8) NULL,
	APPTBUYB_TRD_AMT_MTD numeric(38,8) NULL,
	SCDY_TRD_QTY_YDA     numeric(38,8) NULL,
	CREDIT_ODI_TRD_QTY_YDA numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY_YDA numeric(38,8) NULL,
	STKF_TRD_QTY_YTD     numeric(38,8) NULL,
	S_REPUR_TRD_QTY_YTD  numeric(38,8) NULL,
	R_REPUR_TRD_QTY_YTD  numeric(38,8) NULL,
	CREDIT_TRD_QTY_YTD   numeric(38,8) NULL,
	OFFUND_TRD_QTY_YTD   numeric(38,8) NULL,
	OPFUND_TRD_QTY_YTD   numeric(38,8) NULL,
	BANK_CHRM_TRD_QTY_YTD numeric(38,8) NULL,
	SECU_CHRM_TRD_QTY_YTD numeric(38,8) NULL,
	CREDIT_ODI_TRD_QTY_YTD numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY_YTD numeric(38,8) NULL,
	FIN_AMT_YTD          numeric(38,8) NULL,
	CRDT_STK_AMT_YTD     numeric(38,8) NULL,
	STKPLG_BUYB_AMT_YTD  numeric(38,8) NULL,
	GROSS_CMS_YTD        numeric(38,8) NULL,
	NET_CMS_YTD          numeric(38,8) NULL,
	STKPLG_BUYB_CNT_YTD  numeric(38,8) NULL,
	CCB_AMT_YTD          numeric(38,8) NULL,
	CCB_CNT_YTD          numeric(38,8) NULL,
	FIN_SELL_AMT_YTD     numeric(38,8) NULL,
	FIN_SELL_CNT_YTD     numeric(38,8) NULL,
	CRDT_STK_BUYIN_AMT_YTD numeric(38,8) NULL,
	CRDT_STK_BUYIN_CNT_YTD numeric(38,8) NULL,
	CSS_AMT_YTD          numeric(38,8) NULL,
	CSS_CNT_YTD          numeric(38,8) NULL,
	FIN_RTN_AMT_YTD      numeric(38,8) NULL,
	APPTBUYB_REP_AMT_YTD numeric(38,8) NULL,
	APPTBUYB_BUYB_AMT_YTD numeric(38,8) NULL,
	APPTBUYB_TRD_AMT_YTD numeric(38,8) NULL,
	SB_TRD_QTY_MTD       numeric(38,8) NULL,
	SB_TRD_QTY_YTD       numeric(38,8) NULL,
	BOND_TRD_QTY_MTD     numeric(38,8) NULL,
	BOND_TRD_QTY_YTD     numeric(38,8) NULL,
	ITC_CRRC_FUND_TRD_QTY_MTD numeric(38,8) NULL,
	ITC_CRRC_FUND_TRD_QTY_YTD numeric(38,8) NULL,
	S_REPUR_NET_CMS_MTD  numeric(38,8) NULL,
	S_REPUR_NET_CMS_YTD  numeric(38,8) NULL,
	R_REPUR_NET_CMS_MTD  numeric(38,8) NULL,
	R_REPUR_NET_CMS_YTD  numeric(38,8) NULL,
	ITC_CRRC_FUND_NET_CMS_MTD numeric(38,8) NULL,
	ITC_CRRC_FUND_NET_CMS_YTD numeric(38,8) NULL,
	PB_TRD_QTY_MTD       numeric(38,8) NULL
);



COMMENT ON TABLE T_EVT_EMPCUS_ODI_TRD_M_D IS '员工客户普通交易月表';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.YEAR IS '年';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.MTH IS '月';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.MAIN_CPTL_ACCT IS '主资金账号';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.EQT_CLAS_KEPP_PERCN IS '权益类持仓占比';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SCDY_TRD_FREQ_MTD IS '二级交易次数_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.RCT_TRD_DT_GT IS '最近交易日期_累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SCDY_TRD_QTY_YTD IS '二级交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.TRD_FREQ_YTD IS '交易次数_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKF_TRD_QTY_MDA IS '股基交易量_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKF_TRD_QTY_YDA IS '股基交易量_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.S_REPUR_TRD_QTY_MDA IS '正回购交易量_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.R_REPUR_TRD_QTY_MDA IS '逆回购交易量_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.S_REPUR_TRD_QTY_YDA IS '正回购交易量_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.R_REPUR_TRD_QTY_YDA IS '逆回购交易量_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.HGT_TRD_QTY_MTD IS '沪港通交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SGT_TRD_QTY_MTD IS '深港通交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SGT_TRD_QTY_YTD IS '深港通交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.HGT_TRD_QTY_YTD IS '沪港通交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.Y_RCT_STK_TRD_QTY IS '近12月股票交易量';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SCDY_TRD_FREQ_YTD IS '二级交易次数_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.TRD_FREQ_MTD IS '交易次数_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.APPTBUYB_TRD_QTY_MTD IS '约定购回交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.APPTBUYB_TRD_QTY_YTD IS '约定购回交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.RCT_TRD_DT_M IS '最近交易日期_本月';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKPLG_TRD_QTY_MTD IS '股票质押交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKPLG_TRD_QTY_YTD IS '股票质押交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.PSTK_OPTN_TRD_QTY_MTD IS '个股期权交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.PSTK_OPTN_TRD_QTY_YTD IS '个股期权交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.REPQ_TRD_QTY_MTD IS '报价回购交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.REPQ_TRD_QTY_YTD IS '报价回购交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.BGDL_QTY_MTD IS '大宗交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.BGDL_QTY_YTD IS '大宗交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.LOAD_DT IS '清洗日期';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.NATRE_DAYS_MTH IS '自然天数_月';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.NATRE_DAYS_YEAR IS '自然天数_年';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_ODI_TRD_QTY_MDA IS '信用账户普通交易量_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_CRED_TRD_QTY_MDA IS '信用账户信用交易量_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKF_TRD_QTY_MTD IS '股基交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SCDY_TRD_QTY_MTD IS '二级交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SCDY_TRD_QTY_MDA IS '二级交易量_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.S_REPUR_TRD_QTY_MTD IS '正回购交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.R_REPUR_TRD_QTY_MTD IS '逆回购交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_TRD_QTY_MTD IS '融资融券交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.OFFUND_TRD_QTY_MTD IS '场内基金交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.OPFUND_TRD_QTY_MTD IS '场外基金交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.BANK_CHRM_TRD_QTY_MTD IS '银行理财交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SECU_CHRM_TRD_QTY_MTD IS '证券理财交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_ODI_TRD_QTY_MTD IS '信用账户普通交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_CRED_TRD_QTY_MTD IS '信用账户信用交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.FIN_AMT_MTD IS '融资金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CRDT_STK_AMT_MTD IS '融券金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKPLG_BUYB_AMT_MTD IS '股票质押购回金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.GROSS_CMS_MTD IS '毛佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.NET_CMS_MTD IS '净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKPLG_BUYB_CNT_MTD IS '股票质押购回笔数_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CCB_AMT_MTD IS '融资买入金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CCB_CNT_MTD IS '融资买入笔数_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.FIN_SELL_AMT_MTD IS '融资卖出金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.FIN_SELL_CNT_MTD IS '融资卖出笔数_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CRDT_STK_BUYIN_AMT_MTD IS '融券买入金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CRDT_STK_BUYIN_CNT_MTD IS '融券买入笔数_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CSS_AMT_MTD IS '融券卖出金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CSS_CNT_MTD IS '融券卖出笔数_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.FIN_RTN_AMT_MTD IS '融资归还金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.APPTBUYB_REP_AMT_MTD IS '约定购回还款金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.APPTBUYB_BUYB_AMT_MTD IS '约定购回购回金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.APPTBUYB_TRD_AMT_MTD IS '约定购回交易金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SCDY_TRD_QTY_YDA IS '二级交易量_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_ODI_TRD_QTY_YDA IS '信用账户普通交易量_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_CRED_TRD_QTY_YDA IS '信用账户信用交易量_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKF_TRD_QTY_YTD IS '股基交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.S_REPUR_TRD_QTY_YTD IS '正回购交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.R_REPUR_TRD_QTY_YTD IS '逆回购交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_TRD_QTY_YTD IS '融资融券交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.OFFUND_TRD_QTY_YTD IS '场内基金交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.OPFUND_TRD_QTY_YTD IS '场外基金交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.BANK_CHRM_TRD_QTY_YTD IS '银行理财交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SECU_CHRM_TRD_QTY_YTD IS '证券理财交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_ODI_TRD_QTY_YTD IS '信用账户普通交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CREDIT_CRED_TRD_QTY_YTD IS '信用账户信用交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.FIN_AMT_YTD IS '融资金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CRDT_STK_AMT_YTD IS '融券金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKPLG_BUYB_AMT_YTD IS '股票质押购回金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.GROSS_CMS_YTD IS '毛佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.NET_CMS_YTD IS '净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.STKPLG_BUYB_CNT_YTD IS '股票质押购回笔数_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CCB_AMT_YTD IS '融资买入金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CCB_CNT_YTD IS '融资买入笔数_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.FIN_SELL_AMT_YTD IS '融资卖出金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.FIN_SELL_CNT_YTD IS '融资卖出笔数_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CRDT_STK_BUYIN_AMT_YTD IS '融券买入金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CRDT_STK_BUYIN_CNT_YTD IS '融券买入笔数_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CSS_AMT_YTD IS '融券卖出金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.CSS_CNT_YTD IS '融券卖出笔数_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.FIN_RTN_AMT_YTD IS '融资归还金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.APPTBUYB_REP_AMT_YTD IS '约定购回还款金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.APPTBUYB_BUYB_AMT_YTD IS '约定购回购回金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.APPTBUYB_TRD_AMT_YTD IS '约定购回交易金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SB_TRD_QTY_MTD IS '三板交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.SB_TRD_QTY_YTD IS '三板交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.BOND_TRD_QTY_MTD IS '债券交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.BOND_TRD_QTY_YTD IS '债券交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.ITC_CRRC_FUND_TRD_QTY_MTD IS '场内货币基金交易量_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.ITC_CRRC_FUND_TRD_QTY_YTD IS '场内货币基金交易量_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.S_REPUR_NET_CMS_MTD IS '正回购净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.S_REPUR_NET_CMS_YTD IS '正回购净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.R_REPUR_NET_CMS_MTD IS '逆回购净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.R_REPUR_NET_CMS_YTD IS '逆回购净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.ITC_CRRC_FUND_NET_CMS_MTD IS '场内货币基金净佣金_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.ITC_CRRC_FUND_NET_CMS_YTD IS '场内货币基金净佣金_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_ODI_TRD_M_D.PB_TRD_QTY_MTD IS 'PB交易量_月累计';



ALTER TABLE T_EVT_EMPCUS_ODI_TRD_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,AFA_SEC_EMPID);



CREATE TABLE T_EVT_EMPCUS_PROD_TRD_M_D
(	YEAR                 character varying(4) NOT NULL,
	MTH                  character varying(2) NOT NULL,
	YEAR_MTH             character varying(6) NULL,
	CUST_ID              character varying(30) NOT NULL,
	PROD_CD              character varying(30) NOT NULL,
	PROD_TYPE            character varying(30) NOT NULL,
	YEAR_MTH_CUST_ID     character varying(60) NULL,
	YEAR_MTH_CUST_ID_PROD_CD character varying(60) NULL,
	AFA_SEC_EMPID        character varying(60) NOT NULL,
	WH_ORG_ID_CUST       character varying(100) NULL,
	WH_ORG_ID_EMP        character varying(100) NULL,
	YEAR_MTH_PSN_JNO     character varying(60) NULL,
	ITC_RETAIN_AMT_FINAL numeric(38,8) NULL,
	OTC_RETAIN_AMT_FINAL numeric(38,8) NULL,
	ITC_RETAIN_SHAR_FINAL numeric(38,8) NULL,
	OTC_RETAIN_SHAR_FINAL numeric(38,8) NULL,
	ITC_RETAIN_AMT_MDA   numeric(38,8) NULL,
	OTC_RETAIN_AMT_MDA   numeric(38,8) NULL,
	ITC_RETAIN_SHAR_MDA  numeric(38,8) NULL,
	OTC_RETAIN_SHAR_MDA  numeric(38,8) NULL,
	ITC_RETAIN_AMT_YDA   numeric(38,8) NULL,
	OTC_RETAIN_AMT_YDA   numeric(38,8) NULL,
	ITC_RETAIN_SHAR_YDA  numeric(38,8) NULL,
	OTC_RETAIN_SHAR_YDA  numeric(38,8) NULL,
	ITC_SUBS_AMT_MTD     numeric(38,8) NULL,
	ITC_PURS_AMT_MTD     numeric(38,8) NULL,
	ITC_BUYIN_AMT_MTD    numeric(38,8) NULL,
	ITC_REDP_AMT_MTD     numeric(38,8) NULL,
	ITC_SELL_AMT_MTD     numeric(38,8) NULL,
	OTC_SUBS_AMT_MTD     numeric(38,8) NULL,
	OTC_PURS_AMT_MTD     numeric(38,8) NULL,
	OTC_CASTSL_AMT_MTD   numeric(38,8) NULL,
	OTC_COVT_IN_AMT_MTD  numeric(38,8) NULL,
	OTC_REDP_AMT_MTD     numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_MTD numeric(38,8) NULL,
	ITC_SUBS_SHAR_MTD    numeric(38,8) NULL,
	ITC_PURS_SHAR_MTD    numeric(38,8) NULL,
	ITC_BUYIN_SHAR_MTD   numeric(38,8) NULL,
	ITC_REDP_SHAR_MTD    numeric(38,8) NULL,
	ITC_SELL_SHAR_MTD    numeric(38,8) NULL,
	OTC_SUBS_SHAR_MTD    numeric(38,8) NULL,
	OTC_PURS_SHAR_MTD    numeric(38,8) NULL,
	OTC_CASTSL_SHAR_MTD  numeric(38,8) NULL,
	OTC_COVT_IN_SHAR_MTD numeric(38,8) NULL,
	OTC_REDP_SHAR_MTD    numeric(38,8) NULL,
	OTC_COVT_OUT_SHAR_MTD numeric(38,8) NULL,
	ITC_SUBS_CHAG_MTD    numeric(38,8) NULL,
	ITC_PURS_CHAG_MTD    numeric(38,8) NULL,
	ITC_BUYIN_CHAG_MTD   numeric(38,8) NULL,
	ITC_REDP_CHAG_MTD    numeric(38,8) NULL,
	ITC_SELL_CHAG_MTD    numeric(38,8) NULL,
	OTC_SUBS_CHAG_MTD    numeric(38,8) NULL,
	OTC_PURS_CHAG_MTD    numeric(38,8) NULL,
	OTC_CASTSL_CHAG_MTD  numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_MTD numeric(38,8) NULL,
	OTC_REDP_CHAG_MTD    numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_MTD numeric(38,8) NULL,
	ITC_SUBS_AMT_YTD     numeric(38,8) NULL,
	ITC_PURS_AMT_YTD     numeric(38,8) NULL,
	ITC_BUYIN_AMT_YTD    numeric(38,8) NULL,
	ITC_REDP_AMT_YTD     numeric(38,8) NULL,
	ITC_SELL_AMT_YTD     numeric(38,8) NULL,
	OTC_SUBS_AMT_YTD     numeric(38,8) NULL,
	OTC_PURS_AMT_YTD     numeric(38,8) NULL,
	OTC_CASTSL_AMT_YTD   numeric(38,8) NULL,
	OTC_COVT_IN_AMT_YTD  numeric(38,8) NULL,
	OTC_REDP_AMT_YTD     numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_YTD numeric(38,8) NULL,
	ITC_SUBS_SHAR_YTD    numeric(38,8) NULL,
	ITC_PURS_SHAR_YTD    numeric(38,8) NULL,
	ITC_BUYIN_SHAR_YTD   numeric(38,8) NULL,
	ITC_REDP_SHAR_YTD    numeric(38,8) NULL,
	ITC_SELL_SHAR_YTD    numeric(38,8) NULL,
	OTC_SUBS_SHAR_YTD    numeric(38,8) NULL,
	OTC_PURS_SHAR_YTD    numeric(38,8) NULL,
	OTC_CASTSL_SHAR_YTD  numeric(38,8) NULL,
	OTC_COVT_IN_SHAR_YTD numeric(38,8) NULL,
	OTC_REDP_SHAR_YTD    numeric(38,8) NULL,
	OTC_COVT_OUT_SHAR_YTD numeric(38,8) NULL,
	ITC_SUBS_CHAG_YTD    numeric(38,8) NULL,
	ITC_PURS_CHAG_YTD    numeric(38,8) NULL,
	ITC_BUYIN_CHAG_YTD   numeric(38,8) NULL,
	ITC_REDP_CHAG_YTD    numeric(38,8) NULL,
	ITC_SELL_CHAG_YTD    numeric(38,8) NULL,
	OTC_SUBS_CHAG_YTD    numeric(38,8) NULL,
	OTC_PURS_CHAG_YTD    numeric(38,8) NULL,
	OTC_CASTSL_CHAG_YTD  numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_YTD numeric(38,8) NULL,
	OTC_REDP_CHAG_YTD    numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_YTD numeric(38,8) NULL,
	LOAD_DT              numeric(8,0) NULL,
	CONTD_SALE_SHAR_MTD  numeric(38,8) NULL,
	CONTD_SALE_AMT_MTD   numeric(38,8) NULL,
	CONTD_SALE_SHAR_YTD  numeric(38,8) NULL,
	CONTD_SALE_AMT_YTD   numeric(38,8) NULL
);



COMMENT ON TABLE T_EVT_EMPCUS_PROD_TRD_M_D IS '员工客户产品交易月表';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.YEAR IS '年';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.MTH IS '月';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.CUST_ID IS '客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.PROD_CD IS '产品代码';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.PROD_TYPE IS '产品类型';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.YEAR_MTH_CUST_ID IS '年月客户编码';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.YEAR_MTH_CUST_ID_PROD_CD IS '年月客户编码产品代码';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.AFA_SEC_EMPID IS 'AFA_二期员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.WH_ORG_ID_CUST IS '仓库机构编码_客户';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.WH_ORG_ID_EMP IS '仓库机构编码_员工';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.YEAR_MTH_PSN_JNO IS '年月员工号';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_RETAIN_AMT_FINAL IS '场内保有金额_期末';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_RETAIN_AMT_FINAL IS '场外保有金额_期末';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_RETAIN_SHAR_FINAL IS '场内保有份额_期末';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_RETAIN_SHAR_FINAL IS '场外保有份额_期末';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_RETAIN_AMT_MDA IS '场内保有金额_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_RETAIN_AMT_MDA IS '场外保有金额_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_RETAIN_SHAR_MDA IS '场内保有份额_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_RETAIN_SHAR_MDA IS '场外保有份额_月日均';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_RETAIN_AMT_YDA IS '场内保有金额_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_RETAIN_AMT_YDA IS '场外保有金额_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_RETAIN_SHAR_YDA IS '场内保有份额_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_RETAIN_SHAR_YDA IS '场外保有份额_年日均';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SUBS_AMT_MTD IS '场内认购金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_PURS_AMT_MTD IS '场内申购金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_BUYIN_AMT_MTD IS '场内买入金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_REDP_AMT_MTD IS '场内赎回金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SELL_AMT_MTD IS '场内卖出金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_SUBS_AMT_MTD IS '场外认购金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_PURS_AMT_MTD IS '场外申购金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_CASTSL_AMT_MTD IS '场外定投金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_IN_AMT_MTD IS '场外转换入金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_REDP_AMT_MTD IS '场外赎回金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_OUT_AMT_MTD IS '场外转换出金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SUBS_SHAR_MTD IS '场内认购份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_PURS_SHAR_MTD IS '场内申购份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_BUYIN_SHAR_MTD IS '场内买入份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_REDP_SHAR_MTD IS '场内赎回份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SELL_SHAR_MTD IS '场内卖出份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_SUBS_SHAR_MTD IS '场外认购份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_PURS_SHAR_MTD IS '场外申购份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_CASTSL_SHAR_MTD IS '场外定投份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_IN_SHAR_MTD IS '场外转换入份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_REDP_SHAR_MTD IS '场外赎回份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_OUT_SHAR_MTD IS '场外转换出份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SUBS_CHAG_MTD IS '场内认购手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_PURS_CHAG_MTD IS '场内申购手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_BUYIN_CHAG_MTD IS '场内买入手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_REDP_CHAG_MTD IS '场内赎回手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SELL_CHAG_MTD IS '场内卖出手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_SUBS_CHAG_MTD IS '场外认购手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_PURS_CHAG_MTD IS '场外申购手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_CASTSL_CHAG_MTD IS '场外定投手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_IN_CHAG_MTD IS '场外转换入手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_REDP_CHAG_MTD IS '场外赎回手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_OUT_CHAG_MTD IS '场外转换出手续费_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SUBS_AMT_YTD IS '场内认购金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_PURS_AMT_YTD IS '场内申购金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_BUYIN_AMT_YTD IS '场内买入金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_REDP_AMT_YTD IS '场内赎回金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SELL_AMT_YTD IS '场内卖出金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_SUBS_AMT_YTD IS '场外认购金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_PURS_AMT_YTD IS '场外申购金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_CASTSL_AMT_YTD IS '场外定投金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_IN_AMT_YTD IS '场外转换入金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_REDP_AMT_YTD IS '场外赎回金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_OUT_AMT_YTD IS '场外转换出金额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SUBS_SHAR_YTD IS '场内认购份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_PURS_SHAR_YTD IS '场内申购份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_BUYIN_SHAR_YTD IS '场内买入份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_REDP_SHAR_YTD IS '场内赎回份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SELL_SHAR_YTD IS '场内卖出份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_SUBS_SHAR_YTD IS '场外认购份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_PURS_SHAR_YTD IS '场外申购份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_CASTSL_SHAR_YTD IS '场外定投份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_IN_SHAR_YTD IS '场外转换入份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_REDP_SHAR_YTD IS '场外赎回份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_OUT_SHAR_YTD IS '场外转换出份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SUBS_CHAG_YTD IS '场内认购手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_PURS_CHAG_YTD IS '场内申购手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_BUYIN_CHAG_YTD IS '场内买入手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_REDP_CHAG_YTD IS '场内赎回手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.ITC_SELL_CHAG_YTD IS '场内卖出手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_SUBS_CHAG_YTD IS '场外认购手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_PURS_CHAG_YTD IS '场外申购手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_CASTSL_CHAG_YTD IS '场外定投手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_IN_CHAG_YTD IS '场外转换入手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_REDP_CHAG_YTD IS '场外赎回手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.OTC_COVT_OUT_CHAG_YTD IS '场外转换出手续费_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.LOAD_DT IS '清洗日期';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.CONTD_SALE_SHAR_MTD IS '续作销售份额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.CONTD_SALE_AMT_MTD IS '续作销售金额_月累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.CONTD_SALE_SHAR_YTD IS '续作销售份额_年累计';




COMMENT ON COLUMN T_EVT_EMPCUS_PROD_TRD_M_D.CONTD_SALE_AMT_YTD IS '续作销售金额_年累计';



ALTER TABLE T_EVT_EMPCUS_PROD_TRD_M_D
	ADD PRIMARY KEY (YEAR,MTH,CUST_ID,PROD_CD,PROD_TYPE,AFA_SEC_EMPID);

