
CREATE TABLE dm.T_EVT_PROD_TRD_D_BRH
(	OCCUR_DT             numeric(8,0) NOT NULL,
	BRH_ID               varchar(30) NOT NULL,
	PROD_CD              varchar(30) NOT NULL,
	PROD_TYPE            varchar(30) NOT NULL,
	ITC_RETAIN_AMT       numeric(38,8) NULL,
	OTC_RETAIN_AMT       numeric(38,8) NULL,
	ITC_RETAIN_SHAR      numeric(38,8) NULL,
	OTC_RETAIN_SHAR      numeric(38,8) NULL,
	ITC_SUBS_AMT         numeric(38,8) NULL,
	ITC_PURS_AMT         numeric(38,8) NULL,
	ITC_BUYIN_AMT        numeric(38,8) NULL,
	ITC_REDP_AMT         numeric(38,8) NULL,
	ITC_SELL_AMT         numeric(38,8) NULL,
	OTC_SUBS_AMT         numeric(38,8) NULL,
	OTC_PURS_AMT         numeric(38,8) NULL,
	OTC_CASTSL_AMT       numeric(38,8) NULL,
	OTC_COVT_IN_AMT      numeric(38,8) NULL,
	OTC_REDP_AMT         numeric(38,8) NULL,
	OTC_COVT_OUT_AMT     numeric(38,8) NULL,
	ITC_SUBS_SHAR        numeric(38,8) NULL,
	ITC_PURS_SHAR        numeric(38,8) NULL,
	ITC_BUYIN_SHAR       numeric(38,8) NULL,
	ITC_REDP_SHAR        numeric(38,8) NULL,
	ITC_SELL_SHAR        numeric(38,8) NULL,
	OTC_SUBS_SHAR        numeric(38,8) NULL,
	OTC_PURS_SHAR        numeric(38,8) NULL,
	OTC_CASTSL_SHAR      numeric(38,8) NULL,
	OTC_COVT_IN_SHAR     numeric(38,8) NULL,
	OTC_REDP_SHAR        numeric(38,8) NULL,
	OTC_COVT_OUT_SHAR    numeric(38,8) NULL,
	ITC_SUBS_CHAG        numeric(38,8) NULL,
	ITC_PURS_CHAG        numeric(38,8) NULL,
	ITC_BUYIN_CHAG       numeric(38,8) NULL,
	ITC_REDP_CHAG        numeric(38,8) NULL,
	ITC_SELL_CHAG        numeric(38,8) NULL,
	OTC_SUBS_CHAG        numeric(38,8) NULL,
	OTC_PURS_CHAG        numeric(38,8) NULL,
	OTC_CASTSL_CHAG      numeric(38,8) NULL,
	OTC_COVT_IN_CHAG     numeric(38,8) NULL,
	OTC_REDP_CHAG        numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG    numeric(38,8) NULL,
	CONTD_SALE_SHAR      numeric(38,8) NULL,
	CONTD_SALE_AMT       numeric(38,8) NULL
);



COMMENT ON TABLE dm.T_EVT_PROD_TRD_D_BRH IS '营业部产品交易_日表';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OCCUR_DT IS '业务日期';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.PROD_CD IS '产品代码';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.PROD_TYPE IS '产品类型';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_RETAIN_AMT IS '场内保有金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_RETAIN_AMT IS '场外保有金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_RETAIN_SHAR IS '场内保有份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_RETAIN_SHAR IS '场外保有份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_SUBS_AMT IS '场内认购金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_PURS_AMT IS '场内申购金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_BUYIN_AMT IS '场内买入金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_REDP_AMT IS '场内赎回金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_SELL_AMT IS '场内卖出金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_SUBS_AMT IS '场外认购金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_PURS_AMT IS '场外申购金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_CASTSL_AMT IS '场外定投金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_COVT_IN_AMT IS '场外转换入金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_REDP_AMT IS '场外赎回金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_COVT_OUT_AMT IS '场外转换出金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_SUBS_SHAR IS '场内认购份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_PURS_SHAR IS '场内申购份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_BUYIN_SHAR IS '场内买入份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_REDP_SHAR IS '场内赎回份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_SELL_SHAR IS '场内卖出份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_SUBS_SHAR IS '场外认购份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_PURS_SHAR IS '场外申购份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_CASTSL_SHAR IS '场外定投份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_COVT_IN_SHAR IS '场外转换入份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_REDP_SHAR IS '场外赎回份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_COVT_OUT_SHAR IS '场外转换出份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_SUBS_CHAG IS '场内认购手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_PURS_CHAG IS '场内申购手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_BUYIN_CHAG IS '场内买入手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_REDP_CHAG IS '场内赎回手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.ITC_SELL_CHAG IS '场内卖出手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_SUBS_CHAG IS '场外认购手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_PURS_CHAG IS '场外申购手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_CASTSL_CHAG IS '场外定投手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_COVT_IN_CHAG IS '场外转换入手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_REDP_CHAG IS '场外赎回手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.OTC_COVT_OUT_CHAG IS '场外转换出手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.CONTD_SALE_SHAR IS '续作销售份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.CONTD_SALE_AMT IS '续作销售金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_BRH.BRH_ID IS '营业部编码';



ALTER TABLE dm.T_EVT_PROD_TRD_D_BRH
	ADD PRIMARY KEY (OCCUR_DT,BRH_ID,PROD_CD,PROD_TYPE);



CREATE TABLE dm.T_EVT_PROD_TRD_M_BRH
(	YEAR                 varchar(4) NOT NULL,
	MTH                  varchar(2) NOT NULL,
	BRH_ID               varchar(30) NOT NULL,
	PROD_CD              varchar(30) NOT NULL,
	PROD_TYPE            varchar(30) NOT NULL,
	OCCUR_DT             numeric(8,0) NULL,
	ITC_RETAIN_AMT_MDA   numeric(38,8) NULL,
	OTC_RETAIN_AMT_MDA   numeric(38,8) NULL,
	ITC_RETAIN_SHAR_MDA  numeric(38,8) NULL,
	OTC_RETAIN_SHAR_MDA  numeric(38,8) NULL,
	ITC_RETAIN_AMT_YDA   numeric(38,8) NULL,
	OTC_RETAIN_AMT_YDA   numeric(38,8) NULL,
	ITC_RETAIN_SHAR_YDA  numeric(38,8) NULL,
	OTC_RETAIN_SHAR_YDA  numeric(38,8) NULL,
	OTC_SUBS_AMT_M       numeric(38,8) NULL,
	ITC_PURS_AMT_M       numeric(38,8) NULL,
	ITC_BUYIN_AMT_M      numeric(38,8) NULL,
	ITC_REDP_AMT_M       numeric(38,8) NULL,
	ITC_SELL_AMT_M       numeric(38,8) NULL,
	OTC_PURS_AMT_M       numeric(38,8) NULL,
	OTC_CASTSL_AMT_M     numeric(38,8) NULL,
	OTC_COVT_IN_AMT_M    numeric(38,8) NULL,
	OTC_REDP_AMT_M       numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_M   numeric(38,8) NULL,
	ITC_SUBS_SHAR_M      numeric(38,8) NULL,
	ITC_PURS_SHAR_M      numeric(38,8) NULL,
	ITC_BUYIN_SHAR_M     numeric(38,8) NULL,
	ITC_REDP_SHAR_M      numeric(38,8) NULL,
	ITC_SELL_SHAR_M      numeric(38,8) NULL,
	OTC_SUBS_SHAR_M      numeric(38,8) NULL,
	OTC_PURS_SHAR_M      numeric(38,8) NULL,
	OTC_CASTSL_SHAR_M    numeric(38,8) NULL,
	OTC_COVT_IN_SHAR_M   numeric(38,8) NULL,
	OTC_REDP_SHAR_M      numeric(38,8) NULL,
	OTC_COVT_OUT_SHAR_M  numeric(38,8) NULL,
	ITC_SUBS_CHAG_M      numeric(38,8) NULL,
	ITC_PURS_CHAG_M      numeric(38,8) NULL,
	ITC_BUYIN_CHAG_M     numeric(38,8) NULL,
	ITC_REDP_CHAG_M      numeric(38,8) NULL,
	ITC_SELL_CHAG_M      numeric(38,8) NULL,
	OTC_SUBS_CHAG_M      numeric(38,8) NULL,
	OTC_PURS_CHAG_M      numeric(38,8) NULL,
	OTC_CASTSL_CHAG_M    numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_M   numeric(38,8) NULL,
	OTC_REDP_CHAG_M      numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_M  numeric(38,8) NULL,
	CONTD_SALE_SHAR_M    numeric(38,8) NULL,
	CONTD_SALE_AMT_M     numeric(38,8) NULL,
	OTC_SUBS_AMT_TY      numeric(38,8) NULL,
	ITC_PURS_AMT_TY      numeric(38,8) NULL,
	ITC_BUYIN_AMT_TY     numeric(38,8) NULL,
	ITC_REDP_AMT_TY      numeric(38,8) NULL,
	ITC_SELL_AMT_TY      numeric(38,8) NULL,
	OTC_PURS_AMT_TY      numeric(38,8) NULL,
	OTC_CASTSL_AMT_TY    numeric(38,8) NULL,
	OTC_COVT_IN_AMT_TY   numeric(38,8) NULL,
	OTC_REDP_AMT_TY      numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_TY  numeric(38,8) NULL,
	ITC_SUBS_SHAR_TY     numeric(38,8) NULL,
	ITC_PURS_SHAR_TY     numeric(38,8) NULL,
	ITC_BUYIN_SHAR_TY    numeric(38,8) NULL,
	ITC_REDP_SHAR_TY     numeric(38,8) NULL,
	ITC_SELL_SHAR_TY     numeric(38,8) NULL,
	OTC_SUBS_SHAR_TY     numeric(38,8) NULL,
	OTC_PURS_SHAR_TY     numeric(38,8) NULL,
	OTC_CASTSL_SHAR_TY   numeric(38,8) NULL,
	OTC_COVT_IN_SHAR_TY  numeric(38,8) NULL,
	OTC_REDP_SHAR_TY     numeric(38,8) NULL,
	OTC_COVT_OUT_SHAR_TY numeric(38,8) NULL,
	ITC_SUBS_CHAG_TY     numeric(38,8) NULL,
	ITC_PURS_CHAG_TY     numeric(38,8) NULL,
	ITC_BUYIN_CHAG_TY    numeric(38,8) NULL,
	ITC_REDP_CHAG_TY     numeric(38,8) NULL,
	ITC_SELL_CHAG_TY     numeric(38,8) NULL,
	OTC_SUBS_CHAG_TY     numeric(38,8) NULL,
	OTC_PURS_CHAG_TY     numeric(38,8) NULL,
	OTC_CASTSL_CHAG_TY   numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_TY  numeric(38,8) NULL,
	OTC_REDP_CHAG_TY     numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_TY numeric(38,8) NULL,
	CONTD_SALE_SHAR_TY   numeric(38,8) NULL,
	CONTD_SALE_AMT_TY    numeric(38,8) NULL
);



COMMENT ON TABLE dm.T_EVT_PROD_TRD_M_BRH IS '营业部产品交易_月表';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.YEAR IS '年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.MTH IS '月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.PROD_TYPE IS '产品类型';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.PROD_CD IS '产品代码';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OCCUR_DT IS '业务日期';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_RETAIN_AMT_MDA IS '场内保有金额_月日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_RETAIN_AMT_MDA IS '场外保有金额_月日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_RETAIN_SHAR_MDA IS '场内保有份额_月日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_RETAIN_SHAR_MDA IS '场外保有份额_月日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_RETAIN_AMT_YDA IS '场内保有金额_年日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_RETAIN_AMT_YDA IS '场外保有金额_年日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_RETAIN_SHAR_YDA IS '场内保有份额_年日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_RETAIN_SHAR_YDA IS '场外保有份额_年日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_SUBS_AMT_M IS '场外认购金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_PURS_AMT_M IS '场内申购金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_BUYIN_AMT_M IS '场内买入金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_REDP_AMT_M IS '场内赎回金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SELL_AMT_M IS '场内卖出金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_PURS_AMT_M IS '场外申购金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_CASTSL_AMT_M IS '场外定投金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_IN_AMT_M IS '场外转换入金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_REDP_AMT_M IS '场外赎回金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_OUT_AMT_M IS '场外转换出金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SUBS_SHAR_M IS '场内认购份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_PURS_SHAR_M IS '场内申购份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_BUYIN_SHAR_M IS '场内买入份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_REDP_SHAR_M IS '场内赎回份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SELL_SHAR_M IS '场内卖出份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_SUBS_SHAR_M IS '场外认购份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_PURS_SHAR_M IS '场外申购份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_CASTSL_SHAR_M IS '场外定投份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_IN_SHAR_M IS '场外转换入份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_REDP_SHAR_M IS '场外赎回份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_OUT_SHAR_M IS '场外转换出份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SUBS_CHAG_M IS '场内认购手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_PURS_CHAG_M IS '场内申购手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_BUYIN_CHAG_M IS '场内买入手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_REDP_CHAG_M IS '场内赎回手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SELL_CHAG_M IS '场内卖出手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_SUBS_CHAG_M IS '场外认购手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_PURS_CHAG_M IS '场外申购手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_CASTSL_CHAG_M IS '场外定投手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_IN_CHAG_M IS '场外转换入手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_REDP_CHAG_M IS '场外赎回手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_OUT_CHAG_M IS '场外转换出手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.CONTD_SALE_SHAR_M IS '续作销售份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.CONTD_SALE_AMT_M IS '续作销售金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_SUBS_AMT_TY IS '场外认购金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_PURS_AMT_TY IS '场内申购金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_BUYIN_AMT_TY IS '场内买入金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_REDP_AMT_TY IS '场内赎回金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SELL_AMT_TY IS '场内卖出金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_PURS_AMT_TY IS '场外申购金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_CASTSL_AMT_TY IS '场外定投金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_IN_AMT_TY IS '场外转换入金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_REDP_AMT_TY IS '场外赎回金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_OUT_AMT_TY IS '场外转换出金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SUBS_SHAR_TY IS '场内认购份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_PURS_SHAR_TY IS '场内申购份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_BUYIN_SHAR_TY IS '场内买入份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_REDP_SHAR_TY IS '场内赎回份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SELL_SHAR_TY IS '场内卖出份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_SUBS_SHAR_TY IS '场外认购份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_PURS_SHAR_TY IS '场外申购份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_CASTSL_SHAR_TY IS '场外定投份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_IN_SHAR_TY IS '场外转换入份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_REDP_SHAR_TY IS '场外赎回份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_OUT_SHAR_TY IS '场外转换出份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SUBS_CHAG_TY IS '场内认购手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_PURS_CHAG_TY IS '场内申购手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_BUYIN_CHAG_TY IS '场内买入手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_REDP_CHAG_TY IS '场内赎回手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.ITC_SELL_CHAG_TY IS '场内卖出手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_SUBS_CHAG_TY IS '场外认购手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_PURS_CHAG_TY IS '场外申购手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_CASTSL_CHAG_TY IS '场外定投手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_IN_CHAG_TY IS '场外转换入手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_REDP_CHAG_TY IS '场外赎回手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.OTC_COVT_OUT_CHAG_TY IS '场外转换出手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.CONTD_SALE_SHAR_TY IS '续作销售份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.CONTD_SALE_AMT_TY IS '续作销售金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_BRH.BRH_ID IS '营业部编码';



ALTER TABLE dm.T_EVT_PROD_TRD_M_BRH
	ADD PRIMARY KEY (YEAR,MTH,BRH_ID,PROD_CD,PROD_TYPE);



CREATE TABLE dm.T_EVT_TRD_D_BRH
(	OCCUR_DT             numeric(8,0) NOT NULL,
	BRH_ID               varchar(30) NOT NULL,
	STKF_TRD_QTY         numeric(38,8) NULL,
	SCDY_TRD_QTY         numeric(38,8) NULL,
	S_REPUR_TRD_QTY      numeric(38,8) NULL,
	R_REPUR_TRD_QTY      numeric(38,8) NULL,
	HGT_TRD_QTY          numeric(38,8) NULL,
	SGT_TRD_QTY          numeric(38,8) NULL,
	STKPLG_TRD_QTY       numeric(38,8) NULL,
	APPTBUYB_TRD_QTY     numeric(38,8) NULL,
	OFFUND_TRD_QTY       numeric(38,8) NULL,
	OPFUND_TRD_QTY       numeric(38,8) NULL,
	BANK_CHRM_TRD_QTY    numeric(38,8) NULL,
	SECU_CHRM_TRD_QTY    numeric(38,8) NULL,
	PSTK_OPTN_TRD_QTY    numeric(38,8) NULL,
	CREDIT_ODI_TRD_QTY   numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY  numeric(38,8) NULL,
	COVR_BUYIN_AMT       numeric(38,8) NULL,
	COVR_SELL_AMT        numeric(38,8) NULL,
	CCB_AMT              numeric(38,8) NULL,
	FIN_SELL_AMT         numeric(38,8) NULL,
	CRDT_STK_BUYIN_AMT   numeric(38,8) NULL,
	CSS_AMT              numeric(38,8) NULL,
	FIN_RTN_AMT          numeric(38,8) NULL,
	STKPLG_INIT_TRD_AMT  numeric(38,8) NULL,
	STKPLG_BUYB_TRD_AMT  numeric(38,8) NULL,
	APPTBUYB_INIT_TRD_AMT numeric(38,8) NULL,
	APPTBUYB_BUYB_TRD_AMT numeric(38,8) NULL
);



COMMENT ON TABLE dm.T_EVT_TRD_D_BRH IS '营业部交易表_日表';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.OCCUR_DT IS '业务日期';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.BRH_ID IS '营业部编码';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.STKF_TRD_QTY IS '股基交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.SCDY_TRD_QTY IS '二级交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.S_REPUR_TRD_QTY IS '正回购交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.R_REPUR_TRD_QTY IS '逆回购交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.HGT_TRD_QTY IS '沪港通交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.SGT_TRD_QTY IS '深港通交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.STKPLG_TRD_QTY IS '股票质押交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.APPTBUYB_TRD_QTY IS '约定购回交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.OFFUND_TRD_QTY IS '场内基金交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.OPFUND_TRD_QTY IS '场外基金交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.BANK_CHRM_TRD_QTY IS '银行理财交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.SECU_CHRM_TRD_QTY IS '证券理财交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.CREDIT_ODI_TRD_QTY IS '信用账户普通交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.CREDIT_CRED_TRD_QTY IS '信用账户信用交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.STKPLG_BUYB_TRD_AMT IS '股票质押购回交易金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.PSTK_OPTN_TRD_QTY IS '个股期权交易量';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.COVR_BUYIN_AMT IS '平仓买入金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.COVR_SELL_AMT IS '平仓卖出金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.CCB_AMT IS '融资买入金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.FIN_SELL_AMT IS '融资卖出金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.CRDT_STK_BUYIN_AMT IS '融券买入金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.CSS_AMT IS '融券卖出金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.FIN_RTN_AMT IS '融资归还金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.STKPLG_INIT_TRD_AMT IS '股票质押初始交易金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.APPTBUYB_INIT_TRD_AMT IS '约定购回初始交易金额';




COMMENT ON COLUMN dm.T_EVT_TRD_D_BRH.APPTBUYB_BUYB_TRD_AMT IS '约定购回购回交易金额';



ALTER TABLE dm.T_EVT_TRD_D_BRH
	ADD PRIMARY KEY (OCCUR_DT,BRH_ID);



CREATE TABLE dm.T_EVT_TRD_M_BRH
(	YEAR                 varchar(4) NOT NULL,
	MTH                  varchar(2) NOT NULL,
	BRH_ID               varchar(30) NOT NULL,
	OCCUR_DT             numeric(8,0) NULL,
	STKF_TRD_QTY_M       numeric(38,8) NULL,
	STKF_TRD_QTY_TY      numeric(38,8) NULL,
	SCDY_TRD_QTY_M       numeric(38,8) NULL,
	SCDY_TRD_QTY_TY      numeric(38,8) NULL,
	S_REPUR_TRD_QTY_M    numeric(38,8) NULL,
	S_REPUR_TRD_QTY_TY   numeric(38,8) NULL,
	R_REPUR_TRD_QTY_M    numeric(38,8) NULL,
	R_REPUR_TRD_QTY_TY   numeric(38,8) NULL,
	HGT_TRD_QTY_M        numeric(38,8) NULL,
	HGT_TRD_QTY_TY       numeric(38,8) NULL,
	HGT_TRD_QTY_YTD      numeric(38,8) NULL,
	SGT_TRD_QTY_M        numeric(38,8) NULL,
	SGT_TRD_QTY_TY       numeric(38,8) NULL,
	STKPLG_TRD_QTY_M     numeric(38,8) NULL,
	STKPLG_TRD_QTY_TY    numeric(38,8) NULL,
	APPTBUYB_TRD_QTY_M   numeric(38,8) NULL,
	APPTBUYB_TRD_QTY_TY  numeric(38,8) NULL,
	OFFUND_TRD_QTY_M     numeric(38,8) NULL,
	OFFUND_TRD_QTY_TY    numeric(38,8) NULL,
	OPFUND_TRD_QTY_M     numeric(38,8) NULL,
	OPFUND_TRD_QTY_TY    numeric(38,8) NULL,
	BANK_CHRM_TRD_QTY_M  numeric(38,8) NULL,
	BANK_CHRM_TRD_QTY_TY numeric(38,8) NULL,
	SECU_CHRM_TRD_QTY_M  numeric(38,8) NULL,
	SECU_CHRM_TRD_QTY_TY numeric(38,8) NULL,
	PSTK_OPTN_TRD_QTY_M  numeric(38,8) NULL,
	PSTK_OPTN_TRD_QTY_TY numeric(38,8) NULL,
	CREDIT_ODI_TRD_QTY_M numeric(38,8) NULL,
	CREDIT_ODI_TRD_QTY_TY numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY_M numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY_TY numeric(38,8) NULL,
	COVR_BUYIN_AMT_M     numeric(38,8) NULL,
	COVR_BUYIN_AMT_TY    numeric(38,8) NULL,
	COVR_SELL_AMT_M      numeric(38,8) NULL,
	COVR_SELL_AMT_TY     numeric(38,8) NULL,
	CCB_AMT_M            numeric(38,8) NULL,
	CCB_AMT_TY           numeric(38,8) NULL,
	FIN_SELL_AMT_M       numeric(38,8) NULL,
	FIN_SELL_AMT_TY      numeric(38,8) NULL,
	CRDT_STK_BUYIN_AMT_M numeric(38,8) NULL,
	CRDT_STK_BUYIN_AMT_TY numeric(38,8) NULL,
	CSS_AMT_M            numeric(38,8) NULL,
	CSS_AMT_TY           numeric(38,8) NULL,
	FIN_RTN_AMT_M        numeric(38,8) NULL,
	FIN_RTN_AMT_TY       numeric(38,8) NULL,
	STKPLG_INIT_TRD_AMT_M numeric(38,8) NULL,
	STKPLG_INIT_TRD_AMT_TY numeric(38,8) NULL,
	STKPLG_REPO_TRD_AMT_M numeric(38,8) NULL,
	STKPLG_REPO_TRD_AMT_TY numeric(38,8) NULL,
	APPTBUYB_INIT_TRD_AMT_M numeric(38,8) NULL,
	APPTBUYB_INIT_TRD_AMT_TY numeric(38,8) NULL,
	APPTBUYB_BUYB_TRD_AMT_M numeric(38,8) NULL,
	APPTBUYB_BUYB_TRD_AMT_TY numeric(38,8) NULL
);



COMMENT ON TABLE dm.T_EVT_TRD_M_BRH IS '营业部交易表_月表';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.BRH_ID IS '营业部编码';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.YEAR IS '年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.MTH IS '月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.SCDY_TRD_QTY_M IS '二级交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.SCDY_TRD_QTY_TY IS '二级交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.STKF_TRD_QTY_M IS '股基交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.STKF_TRD_QTY_TY IS '股基交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.S_REPUR_TRD_QTY_M IS '正回购交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.R_REPUR_TRD_QTY_M IS '逆回购交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.S_REPUR_TRD_QTY_TY IS '正回购交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.R_REPUR_TRD_QTY_TY IS '逆回购交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.HGT_TRD_QTY_YTD IS '沪港通交易量年累计';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.HGT_TRD_QTY_M IS '沪港通交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.SGT_TRD_QTY_M IS '深港通交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.SGT_TRD_QTY_TY IS '深港通交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.HGT_TRD_QTY_TY IS '沪港通交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.OCCUR_DT IS '业务日期';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.APPTBUYB_TRD_QTY_M IS '约定购回交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.APPTBUYB_TRD_QTY_TY IS '约定购回交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.STKPLG_TRD_QTY_M IS '股票质押交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.STKPLG_TRD_QTY_TY IS '股票质押交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.PSTK_OPTN_TRD_QTY_M IS '个股期权交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.PSTK_OPTN_TRD_QTY_TY IS '个股期权交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.OPFUND_TRD_QTY_M IS '场外基金交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.OPFUND_TRD_QTY_TY IS '场外基金交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.BANK_CHRM_TRD_QTY_M IS '银行理财交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.BANK_CHRM_TRD_QTY_TY IS '银行理财交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.SECU_CHRM_TRD_QTY_M IS '证券理财交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.SECU_CHRM_TRD_QTY_TY IS '证券理财交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CREDIT_ODI_TRD_QTY_M IS '信用账户普通交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CREDIT_ODI_TRD_QTY_TY IS '信用账户普通交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CREDIT_CRED_TRD_QTY_M IS '信用账户信用交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CREDIT_CRED_TRD_QTY_TY IS '信用账户信用交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.OFFUND_TRD_QTY_M IS '场内基金交易量_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.OFFUND_TRD_QTY_TY IS '场内基金交易量_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.COVR_BUYIN_AMT_M IS '平仓买入金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.COVR_BUYIN_AMT_TY IS '平仓买入金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.COVR_SELL_AMT_TY IS '平仓卖出金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.COVR_SELL_AMT_M IS '平仓卖出金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CCB_AMT_M IS '融资买入金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CCB_AMT_TY IS '融资买入金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.FIN_SELL_AMT_M IS '融资卖出金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.FIN_SELL_AMT_TY IS '融资卖出金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CRDT_STK_BUYIN_AMT_M IS '融券买入金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CRDT_STK_BUYIN_AMT_TY IS '融券买入金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CSS_AMT_M IS '融券卖出金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.CSS_AMT_TY IS '融券卖出金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.FIN_RTN_AMT_M IS '融资归还金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.FIN_RTN_AMT_TY IS '融资归还金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.STKPLG_INIT_TRD_AMT_M IS '股票质押初始交易金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.STKPLG_INIT_TRD_AMT_TY IS '股票质押初始交易金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.STKPLG_REPO_TRD_AMT_M IS '股票质押回购交易金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.STKPLG_REPO_TRD_AMT_TY IS '股票质押回购交易金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.APPTBUYB_INIT_TRD_AMT_M IS '约定购回初始交易金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.APPTBUYB_INIT_TRD_AMT_TY IS '约定购回初始交易金额_本年';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.APPTBUYB_BUYB_TRD_AMT_M IS '约定购回购回交易金额_本月';




COMMENT ON COLUMN dm.T_EVT_TRD_M_BRH.APPTBUYB_BUYB_TRD_AMT_TY IS '约定购回购回交易金额_本年';



ALTER TABLE dm.T_EVT_TRD_M_BRH
	ADD PRIMARY KEY (YEAR,MTH,BRH_ID);



CREATE INDEX IDX_T_EVT_TRD_M_BRH_MTH ON dm.T_EVT_TRD_M_BRH
(
	MTH                   ASC
);



CREATE INDEX IDX_T_EVT_TRD_M_BRH_YEAR ON dm.T_EVT_TRD_M_BRH
(
	YEAR                  ASC
);











