
CREATE TABLE dm.T_EVT_PROD_TRD_D_EMP
(	OCCUR_DT             numeric(8,0) NOT NULL,
	EMP_ID               varchar(30) NOT NULL,
	PROD_CD              varchar(30) NOT NULL,
	PROD_TYPE            varchar(30) NOT NULL,
	ITC_RETAIN_AMT       numeric(38,8) NULL,
	OTC_RETAIN_AMT       numeric(38,8) NULL,
	ITC_RETAIN_SHAR      numeric(38,8) NULL,
	OTC_RETAIN_SHAR      numeric(38,8) NULL,
	ITC_SUBS_AMT         numeric(38,8) NULL,
	ITC_PURS_AMT         numeric(38,8) NULL,
	ITC_BUYIN_AMT        numeric(38,8) NULL,
	ITC_REDP_AMT         numeric(38,8) NULL,
	ITC_SELL_AMT         numeric(38,8) NULL,
	OTC_SUBS_AMT         numeric(38,8) NULL,
	OTC_PURS_AMT         numeric(38,8) NULL,
	OTC_CASTSL_AMT       numeric(38,8) NULL,
	OTC_COVT_IN_AMT      numeric(38,8) NULL,
	OTC_REDP_AMT         numeric(38,8) NULL,
	OTC_COVT_OUT_AMT     numeric(38,8) NULL,
	ITC_SUBS_SHAR        numeric(38,8) NULL,
	ITC_PURS_SHAR        numeric(38,8) NULL,
	ITC_BUYIN_SHAR       numeric(38,8) NULL,
	ITC_REDP_SHAR        numeric(38,8) NULL,
	ITC_SELL_SHAR        numeric(38,8) NULL,
	OTC_SUBS_SHAR        numeric(38,8) NULL,
	OTC_PURS_SHAR        numeric(38,8) NULL,
	OTC_CASTSL_SHAR      numeric(38,8) NULL,
	OTC_COVT_IN_SHAR     numeric(38,8) NULL,
	OTC_REDP_SHAR        numeric(38,8) NULL,
	OTC_COVT_OUT_SHAR    numeric(38,8) NULL,
	ITC_SUBS_CHAG        numeric(38,8) NULL,
	ITC_PURS_CHAG        numeric(38,8) NULL,
	ITC_BUYIN_CHAG       numeric(38,8) NULL,
	ITC_REDP_CHAG        numeric(38,8) NULL,
	ITC_SELL_CHAG        numeric(38,8) NULL,
	OTC_SUBS_CHAG        numeric(38,8) NULL,
	OTC_PURS_CHAG        numeric(38,8) NULL,
	OTC_CASTSL_CHAG      numeric(38,8) NULL,
	OTC_COVT_IN_CHAG     numeric(38,8) NULL,
	OTC_REDP_CHAG        numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG    numeric(38,8) NULL,
	CONTD_SALE_SHAR      numeric(38,8) NULL,
	CONTD_SALE_AMT       numeric(38,8) NULL
);



COMMENT ON TABLE dm.T_EVT_PROD_TRD_D_EMP IS '员工产品交易_日表';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OCCUR_DT IS '业务日期';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.EMP_ID IS '员工编码';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.PROD_CD IS '产品代码';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.PROD_TYPE IS '产品类型';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_RETAIN_AMT IS '场内保有金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_RETAIN_AMT IS '场外保有金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_RETAIN_SHAR IS '场内保有份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_RETAIN_SHAR IS '场外保有份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_SUBS_AMT IS '场内认购金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_PURS_AMT IS '场内申购金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_BUYIN_AMT IS '场内买入金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_REDP_AMT IS '场内赎回金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_SELL_AMT IS '场内卖出金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_SUBS_AMT IS '场外认购金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_PURS_AMT IS '场外申购金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_CASTSL_AMT IS '场外定投金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_COVT_IN_AMT IS '场外转换入金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_REDP_AMT IS '场外赎回金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_COVT_OUT_AMT IS '场外转换出金额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_SUBS_SHAR IS '场内认购份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_PURS_SHAR IS '场内申购份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_BUYIN_SHAR IS '场内买入份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_REDP_SHAR IS '场内赎回份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_SELL_SHAR IS '场内卖出份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_SUBS_SHAR IS '场外认购份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_PURS_SHAR IS '场外申购份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_CASTSL_SHAR IS '场外定投份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_COVT_IN_SHAR IS '场外转换入份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_REDP_SHAR IS '场外赎回份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_COVT_OUT_SHAR IS '场外转换出份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_SUBS_CHAG IS '场内认购手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_PURS_CHAG IS '场内申购手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_BUYIN_CHAG IS '场内买入手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_REDP_CHAG IS '场内赎回手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.ITC_SELL_CHAG IS '场内卖出手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_SUBS_CHAG IS '场外认购手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_PURS_CHAG IS '场外申购手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_CASTSL_CHAG IS '场外定投手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_COVT_IN_CHAG IS '场外转换入手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_REDP_CHAG IS '场外赎回手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.OTC_COVT_OUT_CHAG IS '场外转换出手续费';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.CONTD_SALE_SHAR IS '续作销售份额';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_D_EMP.CONTD_SALE_AMT IS '续作销售金额';



ALTER TABLE dm.T_EVT_PROD_TRD_D_EMP
	ADD PRIMARY KEY (OCCUR_DT,EMP_ID,PROD_CD,PROD_TYPE);



CREATE TABLE dm.T_EVT_PROD_TRD_M_EMP
(	YEAR                 varchar(4) NOT NULL,
	MTH                  varchar(2) NOT NULL,
	EMP_ID               varchar(30) NOT NULL,
	PROD_CD              varchar(30) NOT NULL,
	PROD_TYPE            varchar(30) NOT NULL,
	OCCUR_DT             numeric(8,0) NULL,
	ITC_RETAIN_AMT_MDA   numeric(38,8) NULL,
	OTC_RETAIN_AMT_MDA   numeric(38,8) NULL,
	ITC_RETAIN_SHAR_MDA  numeric(38,8) NULL,
	OTC_RETAIN_SHAR_MDA  numeric(38,8) NULL,
	ITC_RETAIN_AMT_YDA   numeric(38,8) NULL,
	OTC_RETAIN_AMT_YDA   numeric(38,8) NULL,
	ITC_RETAIN_SHAR_YDA  numeric(38,8) NULL,
	OTC_RETAIN_SHAR_YDA  numeric(38,8) NULL,
	OTC_SUBS_AMT_M       numeric(38,8) NULL,
	ITC_PURS_AMT_M       numeric(38,8) NULL,
	ITC_BUYIN_AMT_M      numeric(38,8) NULL,
	ITC_REDP_AMT_M       numeric(38,8) NULL,
	ITC_SELL_AMT_M       numeric(38,8) NULL,
	OTC_PURS_AMT_M       numeric(38,8) NULL,
	OTC_CASTSL_AMT_M     numeric(38,8) NULL,
	OTC_COVT_IN_AMT_M    numeric(38,8) NULL,
	OTC_REDP_AMT_M       numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_M   numeric(38,8) NULL,
	ITC_SUBS_SHAR_M      numeric(38,8) NULL,
	ITC_PURS_SHAR_M      numeric(38,8) NULL,
	ITC_BUYIN_SHAR_M     numeric(38,8) NULL,
	ITC_REDP_SHAR_M      numeric(38,8) NULL,
	ITC_SELL_SHAR_M      numeric(38,8) NULL,
	OTC_SUBS_SHAR_M      numeric(38,8) NULL,
	OTC_PURS_SHAR_M      numeric(38,8) NULL,
	OTC_CASTSL_SHAR_M    numeric(38,8) NULL,
	OTC_COVT_IN_SHAR_M   numeric(38,8) NULL,
	OTC_REDP_SHAR_M      numeric(38,8) NULL,
	OTC_COVT_OUT_SHAR_M  numeric(38,8) NULL,
	ITC_SUBS_CHAG_M      numeric(38,8) NULL,
	ITC_PURS_CHAG_M      numeric(38,8) NULL,
	ITC_BUYIN_CHAG_M     numeric(38,8) NULL,
	ITC_REDP_CHAG_M      numeric(38,8) NULL,
	ITC_SELL_CHAG_M      numeric(38,8) NULL,
	OTC_SUBS_CHAG_M      numeric(38,8) NULL,
	OTC_PURS_CHAG_M      numeric(38,8) NULL,
	OTC_CASTSL_CHAG_M    numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_M   numeric(38,8) NULL,
	OTC_REDP_CHAG_M      numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_M  numeric(38,8) NULL,
	CONTD_SALE_SHAR_M    numeric(38,8) NULL,
	CONTD_SALE_AMT_M     numeric(38,8) NULL,
	OTC_SUBS_AMT_TY      numeric(38,8) NULL,
	ITC_PURS_AMT_TY      numeric(38,8) NULL,
	ITC_BUYIN_AMT_TY     numeric(38,8) NULL,
	ITC_REDP_AMT_TY      numeric(38,8) NULL,
	ITC_SELL_AMT_TY      numeric(38,8) NULL,
	OTC_PURS_AMT_TY      numeric(38,8) NULL,
	OTC_CASTSL_AMT_TY    numeric(38,8) NULL,
	OTC_COVT_IN_AMT_TY   numeric(38,8) NULL,
	OTC_REDP_AMT_TY      numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_TY  numeric(38,8) NULL,
	ITC_SUBS_SHAR_TY     numeric(38,8) NULL,
	ITC_PURS_SHAR_TY     numeric(38,8) NULL,
	ITC_BUYIN_SHAR_TY    numeric(38,8) NULL,
	ITC_REDP_SHAR_TY     numeric(38,8) NULL,
	ITC_SELL_SHAR_TY     numeric(38,8) NULL,
	OTC_SUBS_SHAR_TY     numeric(38,8) NULL,
	OTC_PURS_SHAR_TY     numeric(38,8) NULL,
	OTC_CASTSL_SHAR_TY   numeric(38,8) NULL,
	OTC_COVT_IN_SHAR_TY  numeric(38,8) NULL,
	OTC_REDP_SHAR_TY     numeric(38,8) NULL,
	OTC_COVT_OUT_SHAR_TY numeric(38,8) NULL,
	ITC_SUBS_CHAG_TY     numeric(38,8) NULL,
	ITC_PURS_CHAG_TY     numeric(38,8) NULL,
	ITC_BUYIN_CHAG_TY    numeric(38,8) NULL,
	ITC_REDP_CHAG_TY     numeric(38,8) NULL,
	ITC_SELL_CHAG_TY     numeric(38,8) NULL,
	OTC_SUBS_CHAG_TY     numeric(38,8) NULL,
	OTC_PURS_CHAG_TY     numeric(38,8) NULL,
	OTC_CASTSL_CHAG_TY   numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_TY  numeric(38,8) NULL,
	OTC_REDP_CHAG_TY     numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_TY numeric(38,8) NULL,
	CONTD_SALE_SHAR_TY   numeric(38,8) NULL,
	CONTD_SALE_AMT_TY    numeric(38,8) NULL
);



COMMENT ON TABLE dm.T_EVT_PROD_TRD_M_EMP IS '员工产品交易_月表';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.YEAR IS '年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.MTH IS '月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.PROD_TYPE IS '产品类型';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.PROD_CD IS '产品代码';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OCCUR_DT IS '业务日期';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_RETAIN_AMT_MDA IS '场内保有金额_月日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_RETAIN_AMT_MDA IS '场外保有金额_月日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_RETAIN_SHAR_MDA IS '场内保有份额_月日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_RETAIN_SHAR_MDA IS '场外保有份额_月日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_RETAIN_AMT_YDA IS '场内保有金额_年日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_RETAIN_AMT_YDA IS '场外保有金额_年日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_RETAIN_SHAR_YDA IS '场内保有份额_年日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_RETAIN_SHAR_YDA IS '场外保有份额_年日均';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_SUBS_AMT_M IS '场外认购金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_PURS_AMT_M IS '场内申购金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_BUYIN_AMT_M IS '场内买入金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_REDP_AMT_M IS '场内赎回金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SELL_AMT_M IS '场内卖出金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_PURS_AMT_M IS '场外申购金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_CASTSL_AMT_M IS '场外定投金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_IN_AMT_M IS '场外转换入金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_REDP_AMT_M IS '场外赎回金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_OUT_AMT_M IS '场外转换出金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SUBS_SHAR_M IS '场内认购份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_PURS_SHAR_M IS '场内申购份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_BUYIN_SHAR_M IS '场内买入份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_REDP_SHAR_M IS '场内赎回份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SELL_SHAR_M IS '场内卖出份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_SUBS_SHAR_M IS '场外认购份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_PURS_SHAR_M IS '场外申购份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_CASTSL_SHAR_M IS '场外定投份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_IN_SHAR_M IS '场外转换入份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_REDP_SHAR_M IS '场外赎回份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_OUT_SHAR_M IS '场外转换出份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SUBS_CHAG_M IS '场内认购手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_PURS_CHAG_M IS '场内申购手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_BUYIN_CHAG_M IS '场内买入手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_REDP_CHAG_M IS '场内赎回手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SELL_CHAG_M IS '场内卖出手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_SUBS_CHAG_M IS '场外认购手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_PURS_CHAG_M IS '场外申购手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_CASTSL_CHAG_M IS '场外定投手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_IN_CHAG_M IS '场外转换入手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_REDP_CHAG_M IS '场外赎回手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_OUT_CHAG_M IS '场外转换出手续费_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.CONTD_SALE_SHAR_M IS '续作销售份额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.CONTD_SALE_AMT_M IS '续作销售金额_本月';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_SUBS_AMT_TY IS '场外认购金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_PURS_AMT_TY IS '场内申购金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_BUYIN_AMT_TY IS '场内买入金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_REDP_AMT_TY IS '场内赎回金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SELL_AMT_TY IS '场内卖出金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_PURS_AMT_TY IS '场外申购金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_CASTSL_AMT_TY IS '场外定投金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_IN_AMT_TY IS '场外转换入金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_REDP_AMT_TY IS '场外赎回金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_OUT_AMT_TY IS '场外转换出金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SUBS_SHAR_TY IS '场内认购份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_PURS_SHAR_TY IS '场内申购份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_BUYIN_SHAR_TY IS '场内买入份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_REDP_SHAR_TY IS '场内赎回份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SELL_SHAR_TY IS '场内卖出份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_SUBS_SHAR_TY IS '场外认购份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_PURS_SHAR_TY IS '场外申购份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_CASTSL_SHAR_TY IS '场外定投份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_IN_SHAR_TY IS '场外转换入份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_REDP_SHAR_TY IS '场外赎回份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_OUT_SHAR_TY IS '场外转换出份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SUBS_CHAG_TY IS '场内认购手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_PURS_CHAG_TY IS '场内申购手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_BUYIN_CHAG_TY IS '场内买入手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_REDP_CHAG_TY IS '场内赎回手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.ITC_SELL_CHAG_TY IS '场内卖出手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_SUBS_CHAG_TY IS '场外认购手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_PURS_CHAG_TY IS '场外申购手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_CASTSL_CHAG_TY IS '场外定投手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_IN_CHAG_TY IS '场外转换入手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_REDP_CHAG_TY IS '场外赎回手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.OTC_COVT_OUT_CHAG_TY IS '场外转换出手续费_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.CONTD_SALE_SHAR_TY IS '续作销售份额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.CONTD_SALE_AMT_TY IS '续作销售金额_本年';




COMMENT ON COLUMN dm.T_EVT_PROD_TRD_M_EMP.EMP_ID IS '员工编码';



ALTER TABLE dm.T_EVT_PROD_TRD_M_EMP
	ADD PRIMARY KEY (YEAR,MTH,EMP_ID,PROD_CD,PROD_TYPE);








