
CREATE TABLE DM.T_BRKBIS_APPTBUYB_M
(	YEAR_MTH             			varchar(6) NOT NULL,
	ORG_NO               			varchar(30) NOT NULL,
	BRH                  			varchar(100) NOT NULL,
	SEPT_CORP            			varchar(100) NOT NULL,
	SEPT_CORP_TYPE       			varchar(100) NOT NULL,
	IF_YEAR_NA           			integer NOT NULL,
	IF_MTH_NA            			integer NOT NULL,
	ACC_CHAR             			varchar(30) NOT NULL,
	IF_SPCA_ACC          			integer NOT NULL,
	AST_SGMTS            			varchar(30) NOT NULL,
	IF_APPTBUYB_CUST_YEAR_NA 		integer NOT NULL,
	IF_APPTBUYB_CUST_MTH_NA 		integer NOT NULL,
	CUST_NUM                     	numeric(30) NULL,
	APPTBUYB_TOTAST_FINAL         	numeric(38,8) NULL,
	APPTBUYB_NET_AST_FINAL          numeric(38,8) NULL,
	APPTBUYB_BAL_FINAL           	numeric(38,8) NULL,
	APPTBUYB_TOTAST_MDA          	numeric(38,8) NULL,
	APPTBUYB_NET_AST_MDA         	numeric(38,8) NULL,
	APPTBUYB_BAL_MDA             	numeric(38,8) NULL,
	APPTBUYB_TOTAST_YDA          	numeric(38,8) NULL,
	APPTBUYB_NET_AST_YDA         	numeric(38,8) NULL,
	APPTBUYB_BAL_YDA             	numeric(38,8) NULL,
	APPTBUYB_NET_CMS_MTD         	numeric(38,8) NULL,
	APPTBUYB_RECE_INT_MTD         	numeric(38,8) NULL,
	APPTBUYB_PAIDINT_MTD         	numeric(38,8) NULL,
	APPTBUYB_CPTL_COST_MTD          numeric(38,8) NULL,
	APPTBUYB_NET_CMS_YTD            numeric(38,8) NULL,
	APPTBUYB_RECE_INT_YTD           numeric(38,8) NULL,
	APPTBUYB_PAIDINT_YTD            numeric(38,8) NULL,
	APPTBUYB_CPTL_COST_YTD          numeric(38,8) NULL
);



COMMENT ON TABLE DM.T_BRKBIS_APPTBUYB_M IS '经纪业务约定购回月报';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.BRH IS '营业部';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.CUST_NUM IS '客户数';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_TOTAST_FINAL IS '约定购回总资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_NET_AST_FINAL IS '约定购回净资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.ACC_CHAR IS '账户性质';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.IF_SPCA_ACC IS '是否特殊账户';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.AST_SGMTS IS '资产段';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.IF_APPTBUYB_CUST_YEAR_NA IS '是否约定购回客户_年新增';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.IF_APPTBUYB_CUST_MTH_NA IS '是否约定购回客户_月新增';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_BAL_FINAL IS '约定购回余额_期末';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_TOTAST_MDA IS '约定购回总资产_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_NET_AST_MDA IS '约定购回净资产_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_BAL_MDA IS '约定购回余额_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_TOTAST_YDA IS '约定购回总资产_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_NET_AST_YDA IS '约定购回净资产_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_BAL_YDA IS '约定购回余额_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_NET_CMS_MTD IS '约定购回净佣金_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_RECE_INT_MTD IS '约定购回应收利息_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_PAIDINT_MTD IS '约定购回实收利息_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_CPTL_COST_MTD IS '约定购回资金成本_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_NET_CMS_YTD IS '约定购回净佣金_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_RECE_INT_YTD IS '约定购回应收利息_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_PAIDINT_YTD IS '约定购回实收利息_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_APPTBUYB_M.APPTBUYB_CPTL_COST_YTD IS '约定购回资金成本_年累计';



ALTER TABLE DM.T_BRKBIS_APPTBUYB_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,IF_YEAR_NA,IF_MTH_NA,ACC_CHAR,IF_SPCA_ACC,AST_SGMTS,IF_APPTBUYB_CUST_YEAR_NA,IF_APPTBUYB_CUST_MTH_NA);



CREATE TABLE T_BRKBIS_AST_TRD_M
(	YEAR_MTH             varchar(6) NOT NULL,
	ORG_NO               varchar(30) NOT NULL,
	BRH                  varchar(100) NOT NULL,
	SEPT_CORP            varchar(100) NOT NULL,
	SEPT_CORP_TYPE       varchar(100) NOT NULL,
	IF_YEAR_NA           integer NOT NULL,
	IF_MTH_NA            integer NOT NULL,
	ACC_CHAR             varchar(100) NOT NULL,
	IF_SPCA_ACC          integer NOT NULL,
	AST_SGMTS            varchar(30) NOT NULL,
	CUST_NUM                     numeric(30) NULL,
	EFF_HOUS                     numeric(30) NULL,
	TOTAST_FINAL                 numeric(38,8) NULL,
	NET_AST_FINAL                numeric(38,8) NULL,
	STKF_MVAL_FINAL              numeric(38,8) NULL,
	NOTS_MVAL_FINAL              numeric(38,8) NULL,
	SPGSMV_FINAL_SCDY_DEDUCT         numeric(38,8) NULL,
	MARG_FINAL                   numeric(38,8) NULL,
	BOND_MVAL_FINAL              numeric(38,8) NULL,
	REPO_MVAL_FINAL              numeric(38,8) NULL,
	PSTK_OPTN_FINAL              numeric(38,8) NULL,
	PROD_MVAL_FINAL              numeric(38,8) NULL,
	CREDIT_TOTAST_FINAL          numeric(38,8) NULL,
	CREDIT_TOT_LIAB_FINAL         numeric(38,8) NULL,
	CREDIT_BAL_FINAL             numeric(38,8) NULL,
	APPTBUYB_TOTAST_FINAL         numeric(38,8) NULL,
	APPTBUYB_BAL_FINAL           numeric(38,8) NULL,
	STKPLG_TOTAST_FINAL          numeric(38,8) NULL,
	STKPLG_BAL_FINAL             numeric(38,8) NULL,
	OTH_AST_FINAL                numeric(38,8) NULL,
	REAL_NO_ARVD_CPTL_FINAL         numeric(38,8) NULL,
	ODI_A_SHR_MVAL_FINAL         numeric(38,8) NULL,
	CRED_A_SHR_MVAL_FINAL         numeric(38,8) NULL,
	TOTAST_MDA                   numeric(38,8) NULL,
	NET_AST_MDA                  numeric(38,8) NULL,
	STKF_MVAL_MDA                numeric(38,8) NULL,
	NOTS_MVAL_MDA                numeric(38,8) NULL,
	SPGSMV_MDA_SCDY_DEDUCT         numeric(38,8) NULL,
	MARG_MDA                     numeric(38,8) NULL,
	BOND_MVAL_MDA                numeric(38,8) NULL,
	REPO_MVAL_MDA                numeric(38,8) NULL,
	PSTK_OPTN_MDA                numeric(38,8) NULL,
	PROD_MVAL_MDA                numeric(38,8) NULL,
	CREDIT_TOTAST_MDA            numeric(38,8) NULL,
	CREDIT_TOT_LIAB_MDA          numeric(38,8) NULL,
	CREDIT_BAL_MDA               numeric(38,8) NULL,
	APPTBUYB_TOTAST_MDA          numeric(38,8) NULL,
	APPTBUYB_BAL_MDA             numeric(38,8) NULL,
	STKPLG_TOTAST_MDA            numeric(38,8) NULL,
	STKPLG_BAL_MDA               numeric(38,8) NULL,
	OTH_AST_MDA                  numeric(38,8) NULL,
	REAL_NO_ARVD_CPTL_MDA         numeric(38,8) NULL,
	ODI_A_SHR_MVAL_MDA           numeric(38,8) NULL,
	CRED_A_SHR_MVAL_MDA          numeric(38,8) NULL,
	TOTAST_YDA                   numeric(38,8) NULL,
	NET_AST_YDA                  numeric(38,8) NULL,
	STKF_MVAL_YDA                numeric(38,8) NULL,
	NOTS_MVAL_YDA                numeric(38,8) NULL,
	SPGSMV_YDA_SCDY_DEDUCT         numeric(38,8) NULL,
	MARG_YDA                     numeric(38,8) NULL,
	BOND_MVAL_YDA                numeric(38,8) NULL,
	REPO_MVAL_YDA                numeric(38,8) NULL,
	PSTK_OPTN_YDA                numeric(38,8) NULL,
	PROD_MVAL_YDA                numeric(38,8) NULL,
	CREDIT_TOTAST_YDA            numeric(38,8) NULL,
	CREDIT_TOT_LIAB_YDA          numeric(38,8) NULL,
	CREDIT_BAL_YDA               numeric(38,8) NULL,
	APPTBUYB_TOTAST_YDA          numeric(38,8) NULL,
	APPTBUYB_BAL_YDA             numeric(38,8) NULL,
	STKPLG_TOTAST_YDA            numeric(38,8) NULL,
	STKPLG_BAL_YDA               numeric(38,8) NULL,
	OTH_AST_YDA                  numeric(38,8) NULL,
	REAL_NO_ARVD_CPTL_YDA         numeric(38,8) NULL,
	ODI_A_SHR_MVAL_YDA           numeric(38,8) NULL,
	CRED_A_SHR_MVAL_YDA          numeric(38,8) NULL,
	STKF_TRD_QTY_MTD             numeric(38,8) NULL,
	HGT_TRD_QTY_MTD              numeric(38,8) NULL,
	SGT_TRD_QTY_MTD              numeric(38,8) NULL,
	SB_TRD_QTY_MTD               numeric(38,8) NULL,
	PSTK_OPTN_TRD_QTY_MTD         numeric(38,8) NULL,
	BOND_TRD_QTY_MTD             numeric(38,8) NULL,
	S_REPUR_TRD_QTY_MTD          numeric(38,8) NULL,
	R_REPUR_TRD_QTY_MTD          numeric(38,8) NULL,
	CREDIT_ODI_TRD_QTY_MTD         numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY_MTD         numeric(38,8) NULL,
	ITC_CRRC_FUND_TRD_QTY_MTD         numeric(38,8) NULL,
	BGDL_QTY_MTD                 numeric(38,8) NULL,
	REPQ_TRD_QTY_MTD             numeric(38,8) NULL,
	STKF_TRD_QTY_YTD             numeric(38,8) NULL,
	HGT_TRD_QTY_YTD              numeric(38,8) NULL,
	SGT_TRD_QTY_YTD              numeric(38,8) NULL,
	SB_TRD_QTY_YTD               numeric(38,8) NULL,
	PSTK_OPTN_TRD_QTY_YTD         numeric(38,8) NULL,
	BOND_TRD_QTY_YTD             numeric(38,8) NULL,
	S_REPUR_TRD_QTY_YTD          numeric(38,8) NULL,
	R_REPUR_TRD_QTY_YTD          numeric(38,8) NULL,
	CREDIT_ODI_TRD_QTY_YTD         numeric(38,8) NULL,
	CREDIT_CRED_TRD_QTY_YTD         numeric(38,8) NULL,
	ITC_CRRC_FUND_TRD_QTY_YTD         numeric(38,8) NULL,
	BGDL_QTY_YTD                 numeric(38,8) NULL,
	REPQ_TRD_QTY_YTD             numeric(38,8) NULL,
	STKF_NET_CMS_MTD             numeric(38,8) NULL,
	HGT_NET_CMS_MTD              numeric(38,8) NULL,
	SGT_NET_CMS_MTD              numeric(38,8) NULL,
	PSTK_OPTN_NET_CMS_MTD         numeric(38,8) NULL,
	S_REPUR_NET_CMS_MTD          numeric(38,8) NULL,
	R_REPUR_NET_CMS_MTD          numeric(38,8) NULL,
	CREDIT_ODI_NET_CMS_MTD         numeric(38,8) NULL,
	CREDIT_CRED_NET_CMS_MTD         numeric(38,8) NULL,
	ITC_CRRC_FUND_NET_CMS_MTD         numeric(38,8) NULL,
	BGDL_NET_CMS_MTD             numeric(38,8) NULL,
	REPQ_NET_CMS_MTD             numeric(38,8) NULL,
	ODI_SPR_INCM_MTD             numeric(38,8) NULL,
	CRED_SPR_INCM_MTD            numeric(38,8) NULL,
	STKF_NET_CMS_YTD             numeric(38,8) NULL,
	HGT_NET_CMS_YTD              numeric(38,8) NULL,
	SGT_NET_CMS_YTD              numeric(38,8) NULL,
	PSTK_OPTN_NET_CMS_YTD         numeric(38,8) NULL,
	S_REPUR_NET_CMS_YTD          numeric(38,8) NULL,
	R_REPUR_NET_CMS_YTD          numeric(38,8) NULL,
	CREDIT_ODI_NET_CMS_YTD         numeric(38,8) NULL,
	CREDIT_CRED_NET_CMS_YTD         numeric(38,8) NULL,
	ITC_CRRC_FUND_NET_CMS_YTD         numeric(38,8) NULL,
	BGDL_NET_CMS_YTD             numeric(38,8) NULL,
	REPQ_NET_CMS_YTD             numeric(38,8) NULL,
	ODI_SPR_INCM_YTD             numeric(38,8) NULL,
	CRED_SPR_INCM_YTD    numeric(38,8) NULL
);



COMMENT ON TABLE T_BRKBIS_AST_TRD_M IS '经纪业务资产交易月报';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CUST_NUM IS '客户数';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.EFF_HOUS IS '有效户数';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.TOTAST_FINAL IS '总资产_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.NET_AST_FINAL IS '净资产_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKF_MVAL_FINAL IS '股基市值_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.NOTS_MVAL_FINAL IS '限售股市值_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SPGSMV_FINAL_SCDY_DEDUCT IS '股票质押担保证券市值_期末_二级扣减';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.MARG_FINAL IS '保证金_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BOND_MVAL_FINAL IS '债券市值_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REPO_MVAL_FINAL IS '回购市值_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PSTK_OPTN_FINAL IS '个股期权_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PROD_MVAL_FINAL IS '产品市值_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_TOTAST_FINAL IS '融资融券总资产_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_TOT_LIAB_FINAL IS '融资融券总负债_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_BAL_FINAL IS '融资融券余额_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.APPTBUYB_TOTAST_FINAL IS '约定购回总资产_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.APPTBUYB_BAL_FINAL IS '约定购回余额_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKPLG_TOTAST_FINAL IS '股票质押总资产_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKPLG_BAL_FINAL IS '股票质押余额_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.OTH_AST_FINAL IS '其他资产_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REAL_NO_ARVD_CPTL_FINAL IS '真实未到账资金_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ODI_A_SHR_MVAL_FINAL IS '普通A股市值_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CRED_A_SHR_MVAL_FINAL IS '信用A股市值_期末';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.TOTAST_MDA IS '总资产_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.NET_AST_MDA IS '净资产_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKF_MVAL_MDA IS '股基市值_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.NOTS_MVAL_MDA IS '限售股市值_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SPGSMV_MDA_SCDY_DEDUCT IS '股票质押担保证券市值_月日均_二级扣减';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.MARG_MDA IS '保证金_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BOND_MVAL_MDA IS '债券市值_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REPO_MVAL_MDA IS '回购市值_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PSTK_OPTN_MDA IS '个股期权_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PROD_MVAL_MDA IS '产品市值_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_TOTAST_MDA IS '融资融券总资产_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_TOT_LIAB_MDA IS '融资融券总负债_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_BAL_MDA IS '融资融券余额_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.APPTBUYB_TOTAST_MDA IS '约定购回总资产_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.APPTBUYB_BAL_MDA IS '约定购回余额_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKPLG_TOTAST_MDA IS '股票质押总资产_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKPLG_BAL_MDA IS '股票质押余额_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.OTH_AST_MDA IS '其他资产_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REAL_NO_ARVD_CPTL_MDA IS '真实未到账资金_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ODI_A_SHR_MVAL_MDA IS '普通A股市值_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CRED_A_SHR_MVAL_MDA IS '信用A股市值_月日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.TOTAST_YDA IS '总资产_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.NET_AST_YDA IS '净资产_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKF_MVAL_YDA IS '股基市值_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.NOTS_MVAL_YDA IS '限售股市值_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SPGSMV_YDA_SCDY_DEDUCT IS '股票质押担保证券市值_年日均_二级扣减';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.MARG_YDA IS '保证金_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BOND_MVAL_YDA IS '债券市值_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REPO_MVAL_YDA IS '回购市值_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PSTK_OPTN_YDA IS '个股期权_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PROD_MVAL_YDA IS '产品市值_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_TOTAST_YDA IS '融资融券总资产_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_TOT_LIAB_YDA IS '融资融券总负债_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_BAL_YDA IS '融资融券余额_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.APPTBUYB_TOTAST_YDA IS '约定购回总资产_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.APPTBUYB_BAL_YDA IS '约定购回余额_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKPLG_TOTAST_YDA IS '股票质押总资产_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKPLG_BAL_YDA IS '股票质押余额_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.OTH_AST_YDA IS '其他资产_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REAL_NO_ARVD_CPTL_YDA IS '真实未到账资金_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ODI_A_SHR_MVAL_YDA IS '普通A股市值_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CRED_A_SHR_MVAL_YDA IS '信用A股市值_年日均';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKF_TRD_QTY_MTD IS '股基交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.HGT_TRD_QTY_MTD IS '沪港通交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SGT_TRD_QTY_MTD IS '深港通交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SB_TRD_QTY_MTD IS '三板交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PSTK_OPTN_TRD_QTY_MTD IS '个股期权交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BOND_TRD_QTY_MTD IS '债券交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.S_REPUR_TRD_QTY_MTD IS '正回购交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.R_REPUR_TRD_QTY_MTD IS '逆回购交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_ODI_TRD_QTY_MTD IS '信用账户普通交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_CRED_TRD_QTY_MTD IS '信用账户信用交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ITC_CRRC_FUND_TRD_QTY_MTD IS '场内货币基金交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BGDL_QTY_MTD IS '大宗交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REPQ_TRD_QTY_MTD IS '报价回购交易量_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKF_TRD_QTY_YTD IS '股基交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.HGT_TRD_QTY_YTD IS '沪港通交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SGT_TRD_QTY_YTD IS '深港通交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SB_TRD_QTY_YTD IS '三板交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PSTK_OPTN_TRD_QTY_YTD IS '个股期权交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BOND_TRD_QTY_YTD IS '债券交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.S_REPUR_TRD_QTY_YTD IS '正回购交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.R_REPUR_TRD_QTY_YTD IS '逆回购交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_ODI_TRD_QTY_YTD IS '信用账户普通交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_CRED_TRD_QTY_YTD IS '信用账户信用交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ITC_CRRC_FUND_TRD_QTY_YTD IS '场内货币基金交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BGDL_QTY_YTD IS '大宗交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REPQ_TRD_QTY_YTD IS '报价回购交易量_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKF_NET_CMS_MTD IS '股基净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.HGT_NET_CMS_MTD IS '沪港通净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SGT_NET_CMS_MTD IS '深港通净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PSTK_OPTN_NET_CMS_MTD IS '个股期权净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.S_REPUR_NET_CMS_MTD IS '正回购净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.R_REPUR_NET_CMS_MTD IS '逆回购净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_ODI_NET_CMS_MTD IS '信用账户普通净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_CRED_NET_CMS_MTD IS '信用账户信用净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ITC_CRRC_FUND_NET_CMS_MTD IS '场内货币基金净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BGDL_NET_CMS_MTD IS '大宗交易净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REPQ_NET_CMS_MTD IS '报价回购净佣金_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ODI_SPR_INCM_MTD IS '普通利差收入_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CRED_SPR_INCM_MTD IS '信用利差收入_月累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.STKF_NET_CMS_YTD IS '股基净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.HGT_NET_CMS_YTD IS '沪港通净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SGT_NET_CMS_YTD IS '深港通净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.PSTK_OPTN_NET_CMS_YTD IS '个股期权净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.S_REPUR_NET_CMS_YTD IS '正回购净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.R_REPUR_NET_CMS_YTD IS '逆回购净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_ODI_NET_CMS_YTD IS '信用账户普通净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CREDIT_CRED_NET_CMS_YTD IS '信用账户信用净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ITC_CRRC_FUND_NET_CMS_YTD IS '场内货币基金净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BGDL_NET_CMS_YTD IS '大宗交易净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.REPQ_NET_CMS_YTD IS '报价回购净佣金_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ODI_SPR_INCM_YTD IS '普通利差收入_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.CRED_SPR_INCM_YTD IS '信用利差收入_年累计';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.BRH IS '营业部';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.ACC_CHAR IS '账户性质';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.IF_SPCA_ACC IS '是否特殊账户';




COMMENT ON COLUMN T_BRKBIS_AST_TRD_M.AST_SGMTS IS '资产段';



ALTER TABLE T_BRKBIS_AST_TRD_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,IF_YEAR_NA,IF_MTH_NA,ACC_CHAR,IF_SPCA_ACC,AST_SGMTS);



CREATE TABLE DM.T_BRKBIS_CREDIT_M
(	YEAR_MTH             			varchar(6) NOT NULL,
	ORG_NO               			varchar(30) NOT NULL,
	BRH                  			varchar(100) NOT NULL,
	SEPT_CORP            			varchar(100) NOT NULL,
	SEPT_CORP_TYPE       			varchar(100) NOT NULL,
	IF_YEAR_NA           			integer NOT NULL,
	IF_MTH_NA            			integer NOT NULL,
	ACC_CHAR             			varchar(100) NOT NULL,
	IF_SPCA_ACC          			integer NOT NULL,
	AST_SGMTS            			varchar(30) NOT NULL,
	IF_CREDIT_YEAR_NA    			integer NOT NULL,
	IF_CREDIT_MTH_NA     			integer NOT NULL,
	CUST_NUM                     numeric(30) NULL,
	CREDIT_EFF_HOUS              numeric(30) NULL,
	CREDIT_CRED_QUO              numeric(38,8) NULL,
	CREDIT_TOTAST_FINAL          numeric(38,8) NULL,
	CREDIT_NET_AST_FINAL         numeric(38,8) NULL,
	CREDIT_TOT_LIAB_FINAL         numeric(38,8) NULL,
	CREDIT_BAL_FINAL             numeric(38,8) NULL,
	CRED_MARG_FINAL              numeric(38,8) NULL,
	CREDIT_TOTAST_MDA            numeric(38,8) NULL,
	CREDIT_NET_AST_MDA           numeric(38,8) NULL,
	CREDIT_TOT_LIAB_MDA          numeric(38,8) NULL,
	CREDIT_BAL_MDA               numeric(38,8) NULL,
	CRED_MARG_MDA                numeric(38,8) NULL,
	CREDIT_TOTAST_YDA            numeric(38,8) NULL,
	CREDIT_NET_AST_YDA           numeric(38,8) NULL,
	CREDIT_TOT_LIAB_YDA          numeric(38,8) NULL,
	CREDIT_BAL_YDA               numeric(38,8) NULL,
	CRED_MARG_YDA                numeric(38,8) NULL,
	CCB_MTD                      numeric(38,8) NULL,
	CSS_MTD                      numeric(38,8) NULL,
	FIN_SELL_MTD                 numeric(38,8) NULL,
	CRDT_STK_BUYIN_MTD           numeric(38,8) NULL,
	CCB_YTD                      numeric(38,8) NULL,
	CSS_YTD                      numeric(38,8) NULL,
	FIN_SELL_YTD                 numeric(38,8) NULL,
	CRDT_STK_BUYIN_YTD           numeric(38,8) NULL,
	CREDIT_TRD_QTY_ODI_MTD         numeric(38,8) NULL,
	CREDIT_TRD_QTY_CRED_MTD         numeric(38,8) NULL,
	CREDIT_TRD_QTY_ODI_YTD         numeric(38,8) NULL,
	CREDIT_TRD_QTY_CRED_YTD         numeric(38,8) NULL,
	CREDIT_NET_CMS_ODI_MTD         numeric(38,8) NULL,
	CREDIT_NET_CMS_CRED_MTD         numeric(38,8) NULL,
	CREDIT_NET_CMS_ODI_YTD         numeric(38,8) NULL,
	CREDIT_NET_CMS_CRED_YTD         numeric(38,8) NULL,
	CREDIT_RECE_INT_MTD          numeric(38,8) NULL,
	CREDIT_PAIDINT_MTD           numeric(38,8) NULL,
	CREDIT_CPTL_COST_MTD         numeric(38,8) NULL,
	CREDIT_MARG_SPR_INCM_MTD         numeric(38,8) NULL,
	CREDIT_RECE_INT_YTD          numeric(38,8) NULL,
	CREDIT_PAIDINT_YTD           numeric(38,8) NULL,
	CREDIT_CPTL_COST_YTD         numeric(38,8) NULL,
	CREDIT_MARG_SPR_INCM_YTD 	numeric(38,8) NULL
);



COMMENT ON TABLE DM.T_BRKBIS_CREDIT_M IS '经纪业务融资融券月报';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.BRH IS '营业部';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.ACC_CHAR IS '账户性质';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.IF_SPCA_ACC IS '是否特殊账户';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.AST_SGMTS IS '资产段';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.IF_CREDIT_YEAR_NA IS '是否融资融券年新增';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.IF_CREDIT_MTH_NA IS '是否融资融券月新增';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CUST_NUM IS '客户数';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_EFF_HOUS IS '融资融券有效户数';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_CRED_QUO IS '融资融券授信额度';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TOTAST_FINAL IS '融资融券总资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_NET_AST_FINAL IS '融资融券净资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TOT_LIAB_FINAL IS '融资融券总负债_期末';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_BAL_FINAL IS '融资融券余额_期末';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CRED_MARG_FINAL IS '信用保证金_期末';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TOTAST_MDA IS '融资融券总资产_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_NET_AST_MDA IS '融资融券净资产_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TOT_LIAB_MDA IS '融资融券总负债_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_BAL_MDA IS '融资融券余额_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CRED_MARG_MDA IS '信用保证金_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TOTAST_YDA IS '融资融券总资产_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_NET_AST_YDA IS '融资融券净资产_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TOT_LIAB_YDA IS '融资融券总负债_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_BAL_YDA IS '融资融券余额_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CRED_MARG_YDA IS '信用保证金_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CCB_MTD IS '融资买入_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CSS_MTD IS '融券卖出_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.FIN_SELL_MTD IS '融资卖出_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CRDT_STK_BUYIN_MTD IS '融券买入_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CCB_YTD IS '融资买入_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CSS_YTD IS '融券卖出_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.FIN_SELL_YTD IS '融资卖出_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CRDT_STK_BUYIN_YTD IS '融券买入_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TRD_QTY_ODI_MTD IS '融资融券交易量_普通_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TRD_QTY_CRED_MTD IS '融资融券交易量_信用_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TRD_QTY_ODI_YTD IS '融资融券交易量_普通_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_TRD_QTY_CRED_YTD IS '融资融券交易量_信用_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_NET_CMS_ODI_MTD IS '融资融券净佣金_普通_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_NET_CMS_CRED_MTD IS '融资融券净佣金_信用_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_NET_CMS_ODI_YTD IS '融资融券净佣金_普通_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_NET_CMS_CRED_YTD IS '融资融券净佣金_信用_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_RECE_INT_MTD IS '融资融券应收利息_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_PAIDINT_MTD IS '融资融券实收利息_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_CPTL_COST_MTD IS '融资融券资金成本_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_MARG_SPR_INCM_MTD IS '融资融券保证金利差收入_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_RECE_INT_YTD IS '融资融券应收利息_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_PAIDINT_YTD IS '融资融券实收利息_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_CPTL_COST_YTD IS '融资融券资金成本_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_CREDIT_M.CREDIT_MARG_SPR_INCM_YTD IS '融资融券保证金利差收入_年累计';



ALTER TABLE DM.T_BRKBIS_CREDIT_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,IF_YEAR_NA,IF_MTH_NA,ACC_CHAR,IF_SPCA_ACC,AST_SGMTS,IF_CREDIT_YEAR_NA,IF_CREDIT_MTH_NA);



CREATE TABLE T_BRKBIS_FUTR_IB_M
(	YEAR_MTH             varchar(6) NOT NULL,
	ORG_NO               varchar(30) NOT NULL,
	BRH                  varchar(100) NOT NULL,
	SEPT_CORP            varchar(100) NOT NULL,
	SEPT_CORP_TYPE       varchar(100) NOT NULL,
	IF_YEAR_NA           integer NOT NULL,
	IF_MTH_NA            integer NOT NULL,
	CUST_NUM                     numeric(30) NULL,
	IB_AST_FINAL                 numeric(38,8) NULL,
	IB_AST_MDA                   numeric(38,8) NULL,
	NET_RETAN_CHAG_MTD   numeric(38,8) NULL
);



COMMENT ON TABLE T_BRKBIS_FUTR_IB_M IS '经纪业务期货IB月报';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.BRH IS '营业部';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.CUST_NUM IS '客户数';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.IB_AST_FINAL IS 'IB资产_期末';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.IB_AST_MDA IS 'IB资产_月日均';




COMMENT ON COLUMN T_BRKBIS_FUTR_IB_M.NET_RETAN_CHAG_MTD IS '净留存手续费_月累计';



ALTER TABLE T_BRKBIS_FUTR_IB_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,IF_YEAR_NA,IF_MTH_NA);



CREATE TABLE DM.T_BRKBIS_HKSTOCK_M
(	YEAR_MTH             varchar(6) NOT NULL,
	ORG_NO               varchar(30) NOT NULL,
	BRH                  varchar(100) NOT NULL,
	SEPT_CORP            varchar(100) NOT NULL,
	SEPT_CORP_TYPE       varchar(100) NOT NULL,
	IF_YEAR_NA           integer NOT NULL,
	IF_MTH_NA            integer NOT NULL,
	CUST_NUM                     numeric(30) NULL,
	HKSTOCK_AST_FINAL            numeric(38,8) NULL,
	HKSTOCK_AST_MDA      numeric(38,8) NULL
);



COMMENT ON TABLE DM.T_BRKBIS_HKSTOCK_M IS '经纪业务港股月报';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.BRH IS '营业部';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.CUST_NUM IS '客户数';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.HKSTOCK_AST_FINAL IS '港股资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_HKSTOCK_M.HKSTOCK_AST_MDA IS '港股资产_月日均';



ALTER TABLE DM.T_BRKBIS_HKSTOCK_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,IF_YEAR_NA,IF_MTH_NA);



CREATE TABLE T_BRKBIS_OUTMARK_PROD_M
(	YEAR_MTH             varchar(6) NOT NULL,
	ORG_NO               varchar(30) NOT NULL,
	BRH                  varchar(100) NOT NULL,
	SEPT_CORP            varchar(100) NOT NULL,
	SEPT_CORP_TYPE       varchar(100) NOT NULL,
	PROD_CD              varchar(100) NOT NULL,
	PROD_NAME            varchar(100) NOT NULL,
	PROD_TYPE            varchar(30) NOT NULL,
	RETAIN_AMT_FINAL             numeric(38,8) NULL,
	RETAIN_AMT_MDA               numeric(38,8) NULL,
	RETAIN_AMT_YDA               numeric(38,8) NULL,
	SALE_AMT_MTD                 numeric(38,8) NULL,
	REDP_AMT_MTD                 numeric(38,8) NULL,
	SALE_AMT_YTD                 numeric(38,8) NULL,
	REDP_AMT_YTD         numeric(38,8) NULL
);



COMMENT ON TABLE T_BRKBIS_OUTMARK_PROD_M IS '经纪业务体外产品月报';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.BRH IS '营业部';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.PROD_CD IS '产品代码';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.PROD_NAME IS '产品名称';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.PROD_TYPE IS '产品类型';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.RETAIN_AMT_FINAL IS '保有金额_期末';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.RETAIN_AMT_MDA IS '保有金额_月日均';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.RETAIN_AMT_YDA IS '保有金额_年日均';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.SALE_AMT_MTD IS '销售金额_月累计';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.REDP_AMT_MTD IS '赎回金额_月累计';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.SALE_AMT_YTD IS '销售金额_年累计';




COMMENT ON COLUMN T_BRKBIS_OUTMARK_PROD_M.REDP_AMT_YTD IS '赎回金额_年累计';



ALTER TABLE T_BRKBIS_OUTMARK_PROD_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,PROD_CD,PROD_NAME,PROD_TYPE);



CREATE TABLE T_BRKBIS_PROD_DTL_M
(	YEAR_MTH             varchar(6) NOT NULL,
	ORG_NO               varchar(30) NOT NULL,
	BRH                  varchar(100) NOT NULL,
	SEPT_CORP            varchar(100) NOT NULL,
	SEPT_CORP_TYPE       varchar(100) NOT NULL,
	PROD_CD              varchar(100) NOT NULL,
	PROD_NAME            varchar(100) NOT NULL,
	PROD_MNG_PSN         varchar(100) NOT NULL,
	PROD_TYPE            varchar(30) NOT NULL,
	PAYF_FETUR_TYPE      varchar(30) NOT NULL,
	IF_KEY_PROD          varchar(20) NOT NULL,
	RETAIN_AMT_FINAL             numeric(38,8) NULL,
	RETAIN_AMT_MDA               numeric(38,8) NULL,
	RETAIN_AMT_YDA               numeric(38,8) NULL,
	PROD_SALE_AMT_MTD            numeric(38,8) NULL,
	TF_PROD_SALE_AMT_MTD         numeric(38,8) NULL,
	ITC_SUBS_AMT_MTD             numeric(38,8) NULL,
	OTC_SUBS_AMT_MTD             numeric(38,8) NULL,
	OTC_PURS_AMT_MTD             numeric(38,8) NULL,
	OTC_CASTSL_AMT_MTD           numeric(38,8) NULL,
	OTC_COVT_IN_AMT_MTD          numeric(38,8) NULL,
	SFT_CSTD_IN_AMT_MTD          numeric(38,8) NULL,
	CONTD_SALE_AMT_MTD           numeric(38,8) NULL,
	PROD_REDP_AMT_MTD            numeric(38,8) NULL,
	OTC_REDP_AMT_MTD             numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_MTD         numeric(38,8) NULL,
	SFT_CSTD_OUT_AMT_MTD         numeric(38,8) NULL,
	PROD_SALE_AMT_YTD            numeric(38,8) NULL,
	TF_PROD_SALE_AMT_YTD         numeric(38,8) NULL,
	ITC_SUBS_AMT_YTD             numeric(38,8) NULL,
	OTC_SUBS_AMT_YTD             numeric(38,8) NULL,
	OTC_PURS_AMT_YTD             numeric(38,8) NULL,
	OTC_CASTSL_AMT_YTD           numeric(38,8) NULL,
	OTC_COVT_IN_AMT_YTD          numeric(38,8) NULL,
	SFT_CSTD_IN_AMT_YTD          numeric(38,8) NULL,
	CONTD_SALE_AMT_YTD           numeric(38,8) NULL,
	PROD_REDP_AMT_YTD            numeric(38,8) NULL,
	OTC_REDP_AMT_YTD             numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_YTD         numeric(38,8) NULL,
	SFT_CSTD_OUT_AMT_YTD         numeric(38,8) NULL,
	PROD_SALE_CHAG_MTD           numeric(38,8) NULL,
	ITC_SUBS_CHAG_MTD            numeric(38,8) NULL,
	OTC_SUBS_CHAG_MTD            numeric(38,8) NULL,
	OTC_PURS_CHAG_MTD            numeric(38,8) NULL,
	OTC_CASTSL_CHAG_MTD          numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_MTD         numeric(38,8) NULL,
	SFT_CSTD_IN_CHAG_MTD         numeric(38,8) NULL,
	PROD_REDP_CHAG_MTD           numeric(38,8) NULL,
	OTC_REDP_CHAG_MTD            numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_MTD         numeric(38,8) NULL,
	SFT_CSTD_OUT_CHAG_MTD         numeric(38,8) NULL,
	PROD_SALE_CHAG_YTD           numeric(38,8) NULL,
	ITC_SUBS_CHAG_YTD            numeric(38,8) NULL,
	OTC_SUBS_CHAG_YTD            numeric(38,8) NULL,
	OTC_PURS_CHAG_YTD            numeric(38,8) NULL,
	OTC_CASTSL_CHAG_YTD          numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_YTD         numeric(38,8) NULL,
	SFT_CSTD_IN_CHAG_YTD         numeric(38,8) NULL,
	PROD_REDP_CHAG_YTD           numeric(38,8) NULL,
	OTC_REDP_CHAG_YTD            numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_YTD         numeric(38,8) NULL,
	SFT_CSTD_OUT_CHAG_YTD numeric(38,8) NULL
);



COMMENT ON TABLE T_BRKBIS_PROD_DTL_M IS '经纪业务产品明细月报';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.BRH IS '营业部';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_CD IS '产品代码';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_NAME IS '产品名称';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_MNG_PSN IS '产品管理人';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_TYPE IS '产品类型';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PAYF_FETUR_TYPE IS '收益特征类型';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.IF_KEY_PROD IS '是否重点产品';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.RETAIN_AMT_FINAL IS '保有金额_期末';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.RETAIN_AMT_MDA IS '保有金额_月日均';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.RETAIN_AMT_YDA IS '保有金额_年日均';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_SALE_AMT_MTD IS '产品销售金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.TF_PROD_SALE_AMT_MTD IS '首发产品销售金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.ITC_SUBS_AMT_MTD IS '场内认购金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_SUBS_AMT_MTD IS '场外认购金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_PURS_AMT_MTD IS '场外申购金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_CASTSL_AMT_MTD IS '场外定投金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_COVT_IN_AMT_MTD IS '场外转换入金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SFT_CSTD_IN_AMT_MTD IS '转托管入金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.CONTD_SALE_AMT_MTD IS '续作销售金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_REDP_AMT_MTD IS '产品赎回金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_REDP_AMT_MTD IS '场外赎回金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_COVT_OUT_AMT_MTD IS '场外转换出金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SFT_CSTD_OUT_AMT_MTD IS '转托管出金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_SALE_AMT_YTD IS '产品销售金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.TF_PROD_SALE_AMT_YTD IS '首发产品销售金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.ITC_SUBS_AMT_YTD IS '场内认购金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_SUBS_AMT_YTD IS '场外认购金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_PURS_AMT_YTD IS '场外申购金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_CASTSL_AMT_YTD IS '场外定投金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_COVT_IN_AMT_YTD IS '场外转换入金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SFT_CSTD_IN_AMT_YTD IS '转托管入金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.CONTD_SALE_AMT_YTD IS '续作销售金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_REDP_AMT_YTD IS '产品赎回金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_REDP_AMT_YTD IS '场外赎回金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_COVT_OUT_AMT_YTD IS '场外转换出金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SFT_CSTD_OUT_AMT_YTD IS '转托管出金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_SALE_CHAG_MTD IS '产品销售手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.ITC_SUBS_CHAG_MTD IS '场内认购手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_SUBS_CHAG_MTD IS '场外认购手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_PURS_CHAG_MTD IS '场外申购手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_CASTSL_CHAG_MTD IS '场外定投手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_COVT_IN_CHAG_MTD IS '场外转换入手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SFT_CSTD_IN_CHAG_MTD IS '转托管入手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_REDP_CHAG_MTD IS '产品赎回手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_REDP_CHAG_MTD IS '场外赎回手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_COVT_OUT_CHAG_MTD IS '场外转换出手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SFT_CSTD_OUT_CHAG_MTD IS '转托管出手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_SALE_CHAG_YTD IS '产品销售手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.ITC_SUBS_CHAG_YTD IS '场内认购手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_SUBS_CHAG_YTD IS '场外认购手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_PURS_CHAG_YTD IS '场外申购手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_CASTSL_CHAG_YTD IS '场外定投手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_COVT_IN_CHAG_YTD IS '场外转换入手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SFT_CSTD_IN_CHAG_YTD IS '转托管入手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.PROD_REDP_CHAG_YTD IS '产品赎回手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_REDP_CHAG_YTD IS '场外赎回手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.OTC_COVT_OUT_CHAG_YTD IS '场外转换出手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_DTL_M.SFT_CSTD_OUT_CHAG_YTD IS '转托管出手续费_年累计';



ALTER TABLE T_BRKBIS_PROD_DTL_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,PROD_CD,PROD_NAME,PROD_MNG_PSN,PROD_TYPE,PAYF_FETUR_TYPE,IF_KEY_PROD);



CREATE TABLE T_BRKBIS_PROD_M
(	YEAR_MTH             varchar(6) NOT NULL,
	ORG_NO               varchar(30) NOT NULL,
	BRH                  varchar(100) NOT NULL,
	SEPT_CORP            varchar(100) NOT NULL,
	SEPT_CORP_TYPE       varchar(100) NOT NULL,
	IF_YEAR_NA           integer NOT NULL,
	IF_MTH_NA            integer NOT NULL,
	ACC_CHAR             varchar(100) NOT NULL,
	IF_SPCA_ACC          integer NOT NULL,
	AST_SGMTS            varchar(30) NOT NULL,
	IF_PROD_NEW_CUST     integer NOT NULL,
	PROD_TYPE            varchar(30) NOT NULL,
	PAYF_FETUR_TYPE      varchar(30) NOT NULL,
	IF_KEY_PROD          varchar(20) NOT NULL,
	RETAIN_AMT_FINAL             numeric(38,8) NULL,
	RETAIN_AMT_MDA               numeric(38,8) NULL,
	RETAIN_AMT_YDA               numeric(38,8) NULL,
	PROD_SALE_AMT_MTD            numeric(38,8) NULL,
	TF_PROD_SALE_AMT_MTD         numeric(38,8) NULL,
	ITC_SUBS_AMT_MTD             numeric(38,8) NULL,
	OTC_SUBS_AMT_MTD             numeric(38,8) NULL,
	OTC_PURS_AMT_MTD             numeric(38,8) NULL,
	OTC_CASTSL_AMT_MTD           numeric(38,8) NULL,
	OTC_COVT_IN_AMT_MTD          numeric(38,8) NULL,
	SFT_CSTD_IN_AMT_MTD          numeric(38,8) NULL,
	CONTD_SALE_AMT_MTD           numeric(38,8) NULL,
	PROD_REDP_AMT_MTD            numeric(38,8) NULL,
	OTC_REDP_AMT_MTD             numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_MTD         numeric(38,8) NULL,
	SFT_CSTD_OUT_AMT_MTD         numeric(38,8) NULL,
	PROD_SALE_AMT_YTD            numeric(38,8) NULL,
	TF_PROD_SALE_AMT_YTD         numeric(38,8) NULL,
	ITC_SUBS_AMT_YTD             numeric(38,8) NULL,
	OTC_SUBS_AMT_YTD             numeric(38,8) NULL,
	OTC_PURS_AMT_YTD             numeric(38,8) NULL,
	OTC_CASTSL_AMT_YTD           numeric(38,8) NULL,
	OTC_COVT_IN_AMT_YTD          numeric(38,8) NULL,
	SFT_CSTD_IN_AMT_YTD          numeric(38,8) NULL,
	CONTD_SALE_AMT_YTD           numeric(38,8) NULL,
	PROD_REDP_AMT_YTD            numeric(38,8) NULL,
	OTC_REDP_AMT_YTD             numeric(38,8) NULL,
	OTC_COVT_OUT_AMT_YTD         numeric(38,8) NULL,
	SFT_CSTD_OUT_AMT_YTD         numeric(38,8) NULL,
	PROD_SALE_CHAG_MTD           numeric(38,8) NULL,
	ITC_SUBS_CHAG_MTD            numeric(38,8) NULL,
	OTC_SUBS_CHAG_MTD            numeric(38,8) NULL,
	OTC_PURS_CHAG_MTD            numeric(38,8) NULL,
	OTC_CASTSL_CHAG_MTD          numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_MTD         numeric(38,8) NULL,
	SFT_CSTD_IN_CHAG_MTD         numeric(38,8) NULL,
	PROD_REDP_CHAG_MTD           numeric(38,8) NULL,
	OTC_REDP_CHAG_MTD            numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_MTD         numeric(38,8) NULL,
	SFT_CSTD_OUT_CHAG_MTD         numeric(38,8) NULL,
	PROD_SALE_CHAG_YTD           numeric(38,8) NULL,
	ITC_SUBS_CHAG_YTD            numeric(38,8) NULL,
	OTC_SUBS_CHAG_YTD            numeric(38,8) NULL,
	OTC_PURS_CHAG_YTD            numeric(38,8) NULL,
	OTC_CASTSL_CHAG_YTD          numeric(38,8) NULL,
	OTC_COVT_IN_CHAG_YTD         numeric(38,8) NULL,
	SFT_CSTD_IN_CHAG_YTD         numeric(38,8) NULL,
	PROD_REDP_CHAG_YTD           numeric(38,8) NULL,
	OTC_REDP_CHAG_YTD            numeric(38,8) NULL,
	OTC_COVT_OUT_CHAG_YTD         numeric(38,8) NULL,
	SFT_CSTD_OUT_CHAG_YTD numeric(38,8) NULL
);



COMMENT ON TABLE T_BRKBIS_PROD_M IS '经纪业务产品月报';




COMMENT ON COLUMN T_BRKBIS_PROD_M.IF_PROD_NEW_CUST IS '是否产品新客户';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_TYPE IS '产品类型';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PAYF_FETUR_TYPE IS '收益特征类型';




COMMENT ON COLUMN T_BRKBIS_PROD_M.IF_KEY_PROD IS '是否重点产品';




COMMENT ON COLUMN T_BRKBIS_PROD_M.RETAIN_AMT_FINAL IS '保有金额_期末';




COMMENT ON COLUMN T_BRKBIS_PROD_M.RETAIN_AMT_MDA IS '保有金额_月日均';




COMMENT ON COLUMN T_BRKBIS_PROD_M.RETAIN_AMT_YDA IS '保有金额_年日均';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_SALE_AMT_MTD IS '产品销售金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.TF_PROD_SALE_AMT_MTD IS '首发产品销售金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.ITC_SUBS_AMT_MTD IS '场内认购金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_SUBS_AMT_MTD IS '场外认购金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_PURS_AMT_MTD IS '场外申购金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_CASTSL_AMT_MTD IS '场外定投金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_COVT_IN_AMT_MTD IS '场外转换入金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SFT_CSTD_IN_AMT_MTD IS '转托管入金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.CONTD_SALE_AMT_MTD IS '续作销售金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_REDP_AMT_MTD IS '产品赎回金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_REDP_AMT_MTD IS '场外赎回金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_COVT_OUT_AMT_MTD IS '场外转换出金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SFT_CSTD_OUT_AMT_MTD IS '转托管出金额_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_SALE_AMT_YTD IS '产品销售金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.TF_PROD_SALE_AMT_YTD IS '首发产品销售金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.ITC_SUBS_AMT_YTD IS '场内认购金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_SUBS_AMT_YTD IS '场外认购金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_PURS_AMT_YTD IS '场外申购金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_CASTSL_AMT_YTD IS '场外定投金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_COVT_IN_AMT_YTD IS '场外转换入金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SFT_CSTD_IN_AMT_YTD IS '转托管入金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.CONTD_SALE_AMT_YTD IS '续作销售金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_REDP_AMT_YTD IS '产品赎回金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_REDP_AMT_YTD IS '场外赎回金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_COVT_OUT_AMT_YTD IS '场外转换出金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SFT_CSTD_OUT_AMT_YTD IS '转托管出金额_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_SALE_CHAG_MTD IS '产品销售手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.ITC_SUBS_CHAG_MTD IS '场内认购手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_SUBS_CHAG_MTD IS '场外认购手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_PURS_CHAG_MTD IS '场外申购手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_CASTSL_CHAG_MTD IS '场外定投手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_COVT_IN_CHAG_MTD IS '场外转换入手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SFT_CSTD_IN_CHAG_MTD IS '转托管入手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_REDP_CHAG_MTD IS '产品赎回手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_REDP_CHAG_MTD IS '场外赎回手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_COVT_OUT_CHAG_MTD IS '场外转换出手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SFT_CSTD_OUT_CHAG_MTD IS '转托管出手续费_月累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_SALE_CHAG_YTD IS '产品销售手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.ITC_SUBS_CHAG_YTD IS '场内认购手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_SUBS_CHAG_YTD IS '场外认购手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_PURS_CHAG_YTD IS '场外申购手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_CASTSL_CHAG_YTD IS '场外定投手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_COVT_IN_CHAG_YTD IS '场外转换入手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SFT_CSTD_IN_CHAG_YTD IS '转托管入手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.PROD_REDP_CHAG_YTD IS '产品赎回手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_REDP_CHAG_YTD IS '场外赎回手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.OTC_COVT_OUT_CHAG_YTD IS '场外转换出手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SFT_CSTD_OUT_CHAG_YTD IS '转托管出手续费_年累计';




COMMENT ON COLUMN T_BRKBIS_PROD_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN T_BRKBIS_PROD_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN T_BRKBIS_PROD_M.BRH IS '营业部';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN T_BRKBIS_PROD_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN T_BRKBIS_PROD_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN T_BRKBIS_PROD_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN T_BRKBIS_PROD_M.ACC_CHAR IS '账户性质';




COMMENT ON COLUMN T_BRKBIS_PROD_M.IF_SPCA_ACC IS '是否特殊账户';




COMMENT ON COLUMN T_BRKBIS_PROD_M.AST_SGMTS IS '资产段';



ALTER TABLE T_BRKBIS_PROD_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,IF_YEAR_NA,IF_MTH_NA,ACC_CHAR,IF_SPCA_ACC,AST_SGMTS,IF_PROD_NEW_CUST,PROD_TYPE,PAYF_FETUR_TYPE,IF_KEY_PROD);



CREATE TABLE DM.T_BRKBIS_STKPLG_AGGR_M
(	YEAR_MTH                     varchar(6) NOT NULL,
	ORG_NO                       varchar(30) NOT NULL,
	BRH                          varchar(100) NOT NULL,
	SEPT_CORP                    varchar(100) NOT NULL,
	SEPT_CORP_TYPE               varchar(100) NOT NULL,
	IF_YEAR_NA                   integer NOT NULL,
	IF_MTH_NA                    integer NOT NULL,
	ACC_CHAR                     varchar(100) NOT NULL,
	IF_SPCA_ACC                  integer NOT NULL,
	AST_SGMTS                    varchar(30) NOT NULL,
	IF_STKPLG_CUST_YEAR_NA       integer NOT NULL,
	IF_STKPLG_CUST_MTH_NA        integer NOT NULL,
	CUST_NUM                     numeric(30) NULL,
	STKPLG_TOTAST_FINAL          numeric(38,8) NULL,
	STKPLG_NET_AST_FINAL         numeric(38,8) NULL,
	STKPLG_BAL_FINAL             numeric(38,8) NULL,
	PROP_FINOS_BAL_FINAL         numeric(38,8) NULL,
	ASSM_FINOS_BAL_FINAL         numeric(38,8) NULL,
	MINO_AMT_FINOS_BAL_FINAL     numeric(38,8) NULL,
	STKPLG_TOTAST_MDA            numeric(38,8) NULL,
	STKPLG_NET_AST_MDA           numeric(38,8) NULL,
	STKPLG_BAL_MDA               numeric(38,8) NULL,
	PROP_FINOS_BAL_MDA           numeric(38,8) NULL,
	ASSM_FINOS_BAL_MDA           numeric(38,8) NULL,
	MINO_AMT_FINOS_BAL_MDA       numeric(38,8) NULL,
	STKPLG_TOTAST_YDA            numeric(38,8) NULL,
	STKPLG_NET_AST_YDA           numeric(38,8) NULL,
	STKPLG_BAL_YDA               numeric(38,8) NULL,
	PROP_FINOS_BAL_YDA           numeric(38,8) NULL,
	ASSM_FINOS_BAL_YDA           numeric(38,8) NULL,
	MINO_AMT_FINOS_BAL_YDA       numeric(38,8) NULL,
	STKPLG_NET_CMS_MTD           numeric(38,8) NULL,
	STKPLG_RECE_INT_MTD          numeric(38,8) NULL,
	STKPLG_PAIDINT_MTD           numeric(38,8) NULL,
	STKPLG_CPTL_COST_MTD         numeric(38,8) NULL,
	STKPLG_NET_CMS_YTD           numeric(38,8) NULL,
	STKPLG_RECE_INT_YTD          numeric(38,8) NULL,
	STKPLG_PAIDINT_YTD           numeric(38,8) NULL,
	STKPLG_CPTL_COST_YTD 		 numeric(38,8) NULL
);



COMMENT ON TABLE DM.T_BRKBIS_STKPLG_AGGR_M IS '经纪业务股票质押汇总月报';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.BRH IS '营业部';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.ACC_CHAR IS '账户性质';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.IF_SPCA_ACC IS '是否特殊账户';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.AST_SGMTS IS '资产段';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.IF_STKPLG_CUST_YEAR_NA IS '是否股票质押客户_年新增';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.IF_STKPLG_CUST_MTH_NA IS '是否股票质押客户_月新增';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.CUST_NUM IS '客户数';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_TOTAST_FINAL IS '股票质押总资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_NET_AST_FINAL IS '股票质押净资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_BAL_FINAL IS '股票质押余额_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.PROP_FINOS_BAL_FINAL IS '自营融出方余额_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.ASSM_FINOS_BAL_FINAL IS '资管融出方余额_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.MINO_AMT_FINOS_BAL_FINAL IS '小额融出方余额_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_TOTAST_MDA IS '股票质押总资产_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_NET_AST_MDA IS '股票质押净资产_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_BAL_MDA IS '股票质押余额_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.PROP_FINOS_BAL_MDA IS '自营融出方余额_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.ASSM_FINOS_BAL_MDA IS '资管融出方余额_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.MINO_AMT_FINOS_BAL_MDA IS '小额融出方余额_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_TOTAST_YDA IS '股票质押总资产_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_NET_AST_YDA IS '股票质押净资产_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_BAL_YDA IS '股票质押余额_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.PROP_FINOS_BAL_YDA IS '自营融出方余额_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.ASSM_FINOS_BAL_YDA IS '资管融出方余额_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.MINO_AMT_FINOS_BAL_YDA IS '小额融出方余额_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_NET_CMS_MTD IS '股票质押净佣金_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_RECE_INT_MTD IS '股票质押应收利息_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_PAIDINT_MTD IS '股票质押实收利息_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_CPTL_COST_MTD IS '股票质押资金成本_月累计';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_NET_CMS_YTD IS '股票质押净佣金_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_RECE_INT_YTD IS '股票质押应收利息_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_PAIDINT_YTD IS '股票质押实收利息_年累计';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_AGGR_M.STKPLG_CPTL_COST_YTD IS '股票质押资金成本_年累计';



ALTER TABLE DM.T_BRKBIS_STKPLG_AGGR_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,IF_YEAR_NA,IF_MTH_NA,ACC_CHAR,IF_SPCA_ACC,AST_SGMTS,IF_STKPLG_CUST_YEAR_NA,IF_STKPLG_CUST_MTH_NA);



CREATE TABLE DM.T_BRKBIS_STKPLG_CTR_DTL_M
(	YEAR_MTH             		varchar(6) NOT NULL,
	ORG_NO               		varchar(30) NOT NULL,
	BRH                  		varchar(100) NOT NULL,
	SEPT_CORP            		varchar(100) NOT NULL,
	SEPT_CORP_TYPE       		varchar(100) NOT NULL,
	IF_YEAR_NA           		integer NOT NULL,
	IF_MTH_NA            		integer NOT NULL,
	ACC_CHAR             		varchar(100) NOT NULL,
	IF_SPCA_ACC          		integer NOT NULL,
	AST_SGMTS            		varchar(30) NOT NULL,
	IF_STKPLG_CUST_YEAR_NA 		integer NOT NULL,
	IF_STKPLG_CUST_MTH_NA 			integer NOT NULL,
	CTR_NO               		varchar(100) NOT NULL,
	ORDR_DT              		varchar(8) NOT NULL,
	ACTL_BUYB_DT         		varchar(8) NOT NULL,
	SECU_CD              		varchar(30) NOT NULL,
	IF_LS                		integer NOT NULL,
	STKPLG_TOTAST_FINAL          numeric(38,8) NULL,
	STKPLG_NET_AST_FINAL         numeric(38,8) NULL,
	STKPLG_BAL_FINAL             numeric(38,8) NULL,
	STKPLG_TOTAST_MDA            numeric(38,8) NULL,
	STKPLG_NET_AST_MDA           numeric(38,8) NULL,
	STKPLG_BAL_MDA               numeric(38,8) NULL,
	STKPLG_TOTAST_YDA            numeric(38,8) NULL,
	STKPLG_NET_AST_YDA           numeric(38,8) NULL,
	STKPLG_BAL_YDA               numeric(38,8) NULL,
	FINOS_NO             			varchar(100) NULL,
	FINOS_NAME           			varchar(100) NULL,
	FINOS_TYPE           			varchar(30) NULL
);



COMMENT ON TABLE DM.T_BRKBIS_STKPLG_CTR_DTL_M IS '经纪业务股票质押合同明细月报';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.YEAR_MTH IS '年月';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.ORG_NO IS '机构编号';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.BRH IS '营业部';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.SEPT_CORP IS '分公司';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.SEPT_CORP_TYPE IS '分公司类型';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.IF_YEAR_NA IS '是否年新增';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.IF_MTH_NA IS '是否月新增';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.ACC_CHAR IS '账户性质';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.IF_SPCA_ACC IS '是否特殊账户';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.AST_SGMTS IS '资产段';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.IF_STKPLG_CUST_YEAR_NA IS '是否股票质押客户_年新增';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.IF_STKPLG_CUST_MTH_NA IS '是否股票质押客户_月新增';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.CTR_NO IS '合同编号';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.ORDR_DT IS '委托日期';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.ACTL_BUYB_DT IS '实际购回日期';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.SECU_CD IS '证券代码';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.IF_LS IS '是否限售';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_TOTAST_FINAL IS '股票质押总资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_NET_AST_FINAL IS '股票质押净资产_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_BAL_FINAL IS '股票质押余额_期末';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_TOTAST_MDA IS '股票质押总资产_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_NET_AST_MDA IS '股票质押净资产_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_BAL_MDA IS '股票质押余额_月日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_TOTAST_YDA IS '股票质押总资产_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_NET_AST_YDA IS '股票质押净资产_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.STKPLG_BAL_YDA IS '股票质押余额_年日均';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.FINOS_NO IS '融出方编号';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.FINOS_NAME IS '融出方名称';




COMMENT ON COLUMN DM.T_BRKBIS_STKPLG_CTR_DTL_M.FINOS_TYPE IS '融出方类型';



ALTER TABLE DM.T_BRKBIS_STKPLG_CTR_DTL_M
	ADD PRIMARY KEY (YEAR_MTH,ORG_NO,BRH,SEPT_CORP,SEPT_CORP_TYPE,IF_YEAR_NA,IF_MTH_NA,ACC_CHAR,IF_SPCA_ACC,AST_SGMTS,IF_STKPLG_CUST_YEAR_NA,IF_STKPLG_CUST_MTH_NA,CTR_NO,ORDR_DT,ACTL_BUYB_DT,SECU_CD,IF_LS);

